import { canPerformModuleOperation, getTenantContextForModule } from "@/lib/platform/tenant-context";
import FiscalizacaoClient from "./FiscalizacaoClient";
export const dynamic="force-dynamic";
export default async function FiscalizacaoPage(){
 const {prisma,user}=await getTenantContextForModule("TRIBUTACAO"); const canManage=canPerformModuleOperation(user,"TRIBUTACAO","update");
 const [rawTaxpayers,properties,employees,plans,orders,findings,periods,templates,rules]=await Promise.all([
  prisma.taxpayer.findMany({where:{status:"Ativo"},include:{person:{include:{addresses:{include:{neighborhood:true}}}},company:{include:{addresses:{include:{neighborhood:true}}}},economicRegistrations:true},orderBy:{createdAt:"asc"},take:300}),
  prisma.realEstate.findMany({include:{neighborhood:true},orderBy:{createdAt:"asc"},take:300}),prisma.employee.findMany({where:{isActive:true},orderBy:{name:"asc"},take:200}),
  prisma.fiscalAuditPlan.findMany({include:{selections:true,inspectors:true,events:{orderBy:{createdAt:"desc"},take:5},_count:{select:{orders:true}}},orderBy:{createdAt:"desc"},take:100}),
  prisma.fiscalServiceOrder.findMany({include:{events:{orderBy:{createdAt:"desc"},take:8},documents:{orderBy:{issuedAt:"desc"}},requests:{orderBy:{createdAt:"asc"}},assessmentMaps:{orderBy:{version:"desc"}}},orderBy:{issuedAt:"desc"},take:200}),
  prisma.fiscalMeshFinding.findMany({include:{orderLinks:true},orderBy:[{differenceDecimal:"desc"},{updatedAt:"desc"}],take:200}),
  prisma.fiscalProductivityPeriod.findMany({where:canManage?{}:{employeeId:user.employeeId??"SEM_VINCULO"},include:{ledger:{orderBy:{createdAt:"asc"}}},orderBy:{createdAt:"desc"},take:100}),
  prisma.fiscalDocumentTemplate.findMany({orderBy:[{code:"asc"},{version:"desc"}],take:100}),prisma.fiscalPenaltyRule.findMany({orderBy:{effectiveFrom:"desc"},take:100})]);
 const taxpayers=rawTaxpayers.map(row=>{const address=row.company?.addresses[0]??row.person?.addresses[0];return{id:row.id,name:row.company?.corporateName??row.person?.fullName??row.id,document:row.company?.cnpj??row.person?.cpf??"",cnae:row.economicRegistrations[0]?.primaryCnae??"",serviceItem:row.economicActivities??"",neighborhood:address?.neighborhood?.name??"",street:address?.streetName??""}});const taxpayerNames=new Map(taxpayers.map(row=>[row.id,row.name]));const employeeNames=new Map(employees.map(row=>[row.id,row.name]));const propertyNames=new Map(properties.map(row=>[row.id,`Imóvel ${row.municipalInsc??row.registration??row.id}`]));
 return <FiscalizacaoClient data={{taxpayers,properties:properties.map(row=>({id:row.id,name:propertyNames.get(row.id)!,taxpayerId:row.taxpayerId,propertyType:row.propertyType??"",street:row.streetName??"",neighborhood:row.neighborhood?.name??"",fiscalZone:row.fiscalZone??"",fiscalSector:row.block??""})),employees:employees.map(row=>({id:row.id,name:row.name,registration:row.registration??"",salaryBase:row.salaryBase})),
 plans:plans.map(row=>({id:row.id,year:row.year,name:row.name,type:row.planType,status:row.status,selections:row.selections.length,inspectors:row.inspectors.map(item=>employeeNames.get(item.employeeId)??item.employeeId),orders:row._count.orders,filters:row.filterSnapshot,events:row.events.map(event=>`${event.eventType}: ${event.description}`)})),
 orders:orders.map(row=>({id:row.id,number:row.orderNumber,origin:row.originType,status:row.status,subject:row.taxpayerId?taxpayerNames.get(row.taxpayerId)??row.taxpayerId:row.realEstateId?propertyNames.get(row.realEstateId)??row.realEstateId:"—",taxpayerId:row.taxpayerId,realEstateId:row.realEstateId,employee:employeeNames.get(row.responsibleEmployeeId)??row.responsibleEmployeeId,employeeId:row.responsibleEmployeeId,reason:row.reason,issuedAt:row.issuedAt.toISOString(),readAt:row.readAt?.toISOString()??null,closedAt:row.closedAt?.toISOString()??null,documents:row.documents.map(item=>({id:item.id,kind:item.documentKind,number:item.documentNumber,status:item.status,issuedAt:item.issuedAt.toISOString()})),requests:row.requests.map(item=>({id:item.id,description:item.description,status:item.status,deadline:item.deadlineAt.toISOString(),receivedBy:item.receivedBy,returnedTo:item.returnedTo})),maps:row.assessmentMaps.map(item=>({id:item.id,version:item.version,type:item.obligationType,status:item.status,competence:item.competence,base:Number(item.assessedBaseDecimal)-Number(item.originalBaseDecimal),principal:Number(item.principalDecimal),penalty:Number(item.penaltyDecimal),additions:Number(item.interestDecimal)+Number(item.correctionDecimal),discount:Number(item.discountDecimal),total:Number(item.totalDecimal)})),events:row.events.map(event=>`${event.eventType}: ${event.description}`)})),
 findings:findings.map(row=>({id:row.id,taxpayer:taxpayerNames.get(row.taxpayerId)??row.taxpayerId,competence:row.competence,status:row.status,nfse:Number(row.nfseDecimal),simples:Number(row.simplesDeclaredDecimal),cards:Number(row.cardDecimal),desif:Number(row.desifDecimal),difference:Number(row.differenceDecimal),rate:Number(row.rate),potential:Number(row.potentialTaxDecimal),causes:Array.isArray(row.causes)?row.causes.map(String):[],hasOrder:row.orderLinks.length>0})),
 productivity:periods.map(row=>({id:row.id,employee:employeeNames.get(row.employeeId)??row.employeeId,employeeId:row.employeeId,competence:row.competence,status:row.status,points:Number(row.pointsDecimal),pointValue:Number(row.pointValueDecimal),gross:Number(row.grossAmountDecimal),cap:Number(row.cappedAmountDecimal),excess:Number(row.excessAmountDecimal),adjustment:Number(row.adjustmentDecimal),final:Number(row.finalAmountDecimal),ledger:row.ledger.map(item=>({type:item.movementType,amount:Number(item.amountDecimal),description:item.description}))})),
 templates:templates.map(row=>({id:row.id,code:row.code,name:row.name,kind:row.documentKind,version:row.version,status:row.status})),rules:rules.map(row=>({id:row.id,code:row.code,name:row.name,type:row.obligationType,penalty:Number(row.penaltyRate),discount:Number(row.discountRate),interest:Number(row.interestRate),correction:Number(row.correctionRate),legalBasis:row.legalBasis}))}}/>;
}
