import { BookOpenCheck } from "lucide-react";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import { EducationListClient } from "../EducationListClient";
import { S1ActionForm } from "../S1ActionForm";
import { assignTeacherSubjectAction, createAcademicPeriodAction, createCurriculumMatrixAction, createScheduleEntryAction, createSchoolClassAction } from "../s1-actions";

export const dynamic = "force-dynamic";

export default async function AcademicCorePage() {
  const { prisma } = await getTenantContextForModule("EDUCACAO");
  const [schools, periods, matrices, classes, teachers, subjects] = await Promise.all([
    prisma.school.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.academicPeriod.findMany({ include: { school: true }, orderBy: [{ year: "desc" }, { name: "asc" }] }),
    prisma.curriculumMatrix.findMany({ include: { school: true, period: true, _count: { select: { subjects: true } } }, orderBy: { name: "asc" } }),
    prisma.schoolClass.findMany({ include: { school: true, period: true, matrix: true, _count: { select: { enrollments: { where: { status: "Matriculado" } }, teacherAssignments: true, scheduleBoards: true } } }, orderBy: [{ year: "desc" }, { name: "asc" }] }),
    prisma.teacher.findMany({ include: { employee: true }, orderBy: { employee: { name: "asc" } } }),
    prisma.schoolSubject.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
  ]);
  const periodOptions = periods.map((item) => ({ value: item.id, label: `${item.school.name} · ${item.name}` }));
  const classOptions = classes.map((item) => ({ value: item.id, label: `${item.school.name} · ${item.name}` }));
  return <PageFrame className="flex h-full min-h-0 flex-1 flex-col gap-2 overflow-hidden">
    <PageHeader title="Núcleo acadêmico" icon={<BookOpenCheck className="size-4 text-indigo-600" />} />
    <div className="grid shrink-0 gap-2 xl:grid-cols-2">
      <S1ActionForm title="Novo período letivo" submitLabel="Criar período" action={createAcademicPeriodAction} fields={[{ name: "schoolId", label: "Escola", type: "select", required: true, options: schools.map((item) => ({ value: item.id, label: item.name })) }, { name: "code", label: "Código", required: true, placeholder: "2026-REG" }, { name: "name", label: "Nome", required: true, placeholder: "Ano letivo 2026" }, { name: "year", label: "Ano", type: "number", required: true, defaultValue: String(new Date().getFullYear()) }, { name: "modality", label: "Modalidade", type: "select", required: true, options: ["Regular", "EJA", "AEE"].map((value) => ({ value, label: value })) }, { name: "startDate", label: "Início", type: "date", required: true }, { name: "endDate", label: "Término", type: "date", required: true }, { name: "minimumSchoolDays", label: "Dias letivos mínimos", type: "number", defaultValue: "200" }, { name: "resolution", label: "Resolução" }]} />
      <S1ActionForm title="Nova matriz curricular" submitLabel="Criar matriz" action={createCurriculumMatrixAction} fields={[{ name: "schoolId", label: "Escola", type: "select", required: true, options: schools.map((item) => ({ value: item.id, label: item.name })) }, { name: "periodId", label: "Período", type: "select", required: true, options: periodOptions }, { name: "name", label: "Matriz", required: true }, { name: "stage", label: "Etapa", required: true }, { name: "grade", label: "Série/Ano", required: true }, { name: "annualWorkload", label: "Carga anual", type: "number", defaultValue: "800" }, { name: "subjectCode", label: "Código do componente" }, { name: "subjectName", label: "Primeiro componente", required: true }, { name: "subjectWorkload", label: "Carga do componente", type: "number", defaultValue: "80" }, { name: "weeklyLessons", label: "Aulas semanais", type: "number", defaultValue: "2" }]} />
      <S1ActionForm title="Nova turma" submitLabel="Criar turma" action={createSchoolClassAction} fields={[{ name: "periodId", label: "Período", type: "select", required: true, options: periodOptions }, { name: "matrixId", label: "Matriz curricular", type: "select", options: matrices.map((item) => ({ value: item.id, label: item.name })) }, { name: "name", label: "Turma", required: true }, { name: "stage", label: "Etapa", required: true }, { name: "grade", label: "Série/Ano", required: true }, { name: "shift", label: "Turno", type: "select", required: true, options: ["Manhã", "Tarde", "Integral", "Noite"].map((value) => ({ value, label: value })) }, { name: "classType", label: "Tipo", type: "select", required: true, options: ["Regular", "Multisseriada", "EJA", "AEE"].map((value) => ({ value, label: value })) }, { name: "groupingType", label: "Organização", type: "select", options: ["Disciplina", "Área de conhecimento", "Regência"].map((value) => ({ value, label: value })) }, { name: "room", label: "Sala" }, { name: "capacity", label: "Capacidade", type: "number", defaultValue: "30" }, { name: "annualWorkload", label: "Carga anual", type: "number" }, { name: "annualLessons", label: "Aulas anuais", type: "number" }, { name: "lessonMinutes", label: "Minutos por aula", type: "number" }]} />
      <S1ActionForm title="Vincular professor, componente e turma" submitLabel="Vincular" action={assignTeacherSubjectAction} fields={[{ name: "classId", label: "Turma", type: "select", required: true, options: classOptions }, { name: "teacherId", label: "Professor", type: "select", required: true, options: teachers.map((item) => ({ value: item.id, label: item.employee.name })) }, { name: "subjectId", label: "Componente", type: "select", required: true, options: subjects.map((item) => ({ value: item.id, label: item.name })) }, { name: "role", label: "Função", defaultValue: "Docente" }, { name: "startDate", label: "Início", type: "date", required: true }]} />
      <S1ActionForm title="Adicionar aula ao quadro de horários" submitLabel="Adicionar aula" action={createScheduleEntryAction} fields={[{ name: "classId", label: "Turma", type: "select", required: true, options: classOptions }, { name: "subjectId", label: "Componente", type: "select", required: true, options: subjects.map((item) => ({ value: item.id, label: item.name })) }, { name: "teacherId", label: "Professor", type: "select", options: teachers.map((item) => ({ value: item.id, label: item.employee.name })) }, { name: "weekday", label: "Dia", type: "select", required: true, options: [[1, "Segunda"], [2, "Terça"], [3, "Quarta"], [4, "Quinta"], [5, "Sexta"]].map(([value, label]) => ({ value: String(value), label: String(label) })) }, { name: "lessonOrder", label: "Ordem", type: "number", required: true }, { name: "startTime", label: "Início", type: "time", required: true }, { name: "endTime", label: "Término", type: "time", required: true }]} />
    </div>
    <div className="min-h-0 flex-1"><EducationListClient rows={classes.map((item) => ({ id: item.id, cells: { school: item.school.name, period: item.period?.name || "Sem período", class: item.name, type: item.classType, occupancy: `${item._count.enrollments}/${item.capacity}`, links: `${item._count.teacherAssignments} docentes · ${item._count.scheduleBoards} quadros`, status: item.status }, detail: { Escola: item.school.name, Período: item.period?.name || "Não vinculado", Matriz: item.matrix?.name || "Não vinculada", Etapa: item.stage, Série: item.grade, Turno: item.shift, Tipo: item.classType, Capacidade: String(item.capacity), Situação: item.status } }))} columns={[{ key: "school", label: "Escola" }, { key: "period", label: "Período", responsive: "lg" }, { key: "class", label: "Turma" }, { key: "type", label: "Tipo", width: "medium" }, { key: "occupancy", label: "Alunos/Vagas", width: "medium", align: "center" }, { key: "links", label: "Vínculos", responsive: "lg" }, { key: "status", label: "Situação", width: "medium" }]} searchPlaceholder="Buscar escola, período ou turma..." label="turmas" filterKey="status" statusKey="status" detailTitleKey="class" actions={false} /></div>
  </PageFrame>;
}
