export const healthAdministrativeReportOptions = [
  { type: "CID_LIST", requirement: "SAU-ADM-051", label: "Relação de CIDs", filters: ["cid", "status"] },
  { type: "PROCEDURES_BY_FINANCING", requirement: "SAU-ADM-052", label: "Procedimentos por tipo de financiamento", filters: ["procedure", "financing", "status"] },
  { type: "PROCEDURE_LIST", requirement: "SAU-ADM-053", label: "Relação de procedimentos", filters: ["procedure", "financing", "status"] },
  { type: "COVENANT_LIST", requirement: "SAU-ADM-054", label: "Convênios", filters: ["period", "covenant", "status"] },
  { type: "ADDRESS_LIST", requirement: "SAU-ADM-055", label: "Endereços", filters: ["municipality", "query"] },
  { type: "UNIT_LIST", requirement: "SAU-ADM-056", label: "Unidades de Saúde", filters: ["unit", "status"] },
  { type: "SPECIALTIES_BY_UNIT", requirement: "SAU-ADM-057", label: "Especialidades por Unidade", filters: ["unit", "specialty", "status"] },
  { type: "SPECIALTY_GROUPS_BY_UNIT", requirement: "SAU-ADM-058", label: "Grupos de especialidades por Unidade", filters: ["unit", "status"] },
  { type: "PROFESSIONALS_BY_UNIT", requirement: "SAU-ADM-059", label: "Profissionais por Unidade", filters: ["unit", "professional", "specialty", "status"] },
  { type: "EXTERNAL_DEMAND_BY_SPECIALTY", requirement: "SAU-ADM-060", label: "Fluxo de pacientes de outros municípios por especialidade", filters: ["period", "unit", "specialty", "municipality", "status"] },
  { type: "ATTENDANCE_PERCENTAGE_BY_CITY", requirement: "SAU-ADM-061", label: "Percentual de atendimentos por município", filters: ["period", "unit", "municipality"] },
  { type: "PROFESSIONAL_RECORD", requirement: "SAU-ADM-062", label: "Ficha profissional", filters: ["professional", "status"] },
  { type: "PROFESSIONALS_BY_TEAM", requirement: "SAU-ADM-063", label: "Profissionais por equipe", filters: ["unit", "team", "professional", "status"] },
  { type: "PROFESSIONALS_BY_SPECIALTY", requirement: "SAU-ADM-064", label: "Profissionais por especialidade", filters: ["unit", "specialty", "professional", "status"] },
  { type: "PHARMACY_STOCK_BALANCE", requirement: "SAU-FAR-058", label: "Balanço de estoque farmacêutico", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_UNMET_DEMAND", requirement: "SAU-FAR-059", label: "Demanda não atendida por paciente", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_ENTRY_CONSUMPTION", requirement: "SAU-FAR-060", label: "Entradas, consumo e saldos", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_EXPIRY_LOCATION", requirement: "SAU-FAR-061", label: "Saldo, validade e localização", filters: ["unit", "query"] },
  { type: "PHARMACY_RESTRICTED_MOVEMENTS", requirement: "SAU-FAR-062", label: "Manipulados e controlados", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_CONTROLLED_BY_PATIENT", requirement: "SAU-FAR-063", label: "Controlados por paciente", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_FINANCIAL", requirement: "SAU-FAR-064", label: "Posição financeira da Farmácia", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_FULFILLED_REQUEST_COST", requirement: "SAU-FAR-065", label: "Pedidos atendidos por unidade", filters: ["period", "unit"] },
  { type: "PHARMACY_CONTROLLED_BOOK", requirement: "SAU-FAR-066", label: "Livro de medicamentos controlados", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_PATIENT_CONSUMPTION", requirement: "SAU-FAR-067", label: "Histórico de consumo do paciente", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_ABC", requirement: "SAU-FAR-068", label: "Curva ABC de consumo", filters: ["period", "unit"] },
  { type: "PHARMACY_INVOICE_ENTRIES", requirement: "SAU-FAR-069", label: "Entradas por nota fiscal", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_STOCK_POSITION", requirement: "SAU-FAR-070", label: "Posição de estoque", filters: ["unit", "query"] },
  { type: "PHARMACY_STOCK_VALUE", requirement: "SAU-FAR-071", label: "Valor em estoque", filters: ["unit", "query"] },
  { type: "PHARMACY_TRANSFERS", requirement: "SAU-FAR-072", label: "Transferências de produtos", filters: ["period", "unit", "query"] },
  { type: "PHARMACY_EXIT_TYPES", requirement: "SAU-FAR-073", label: "Estoque por tipo de saída", filters: ["period", "unit", "query"] },
  { type: "VACCINATION_BY_PROFESSIONAL", requirement: "SAU-SIS-121", label: "Produção vacinal por profissional", filters: ["period", "unit", "professional"] },
  { type: "VACCINATION_BY_PATIENT", requirement: "SAU-SIS-122", label: "Ficha de vacinação por cidadão", filters: ["period", "unit", "query"] },
  { type: "VACCINATION_OVERDUE", requirement: "SAU-SIS-123", label: "Vacinas atrasadas por paciente", filters: ["unit", "query"] },
  { type: "VACCINATION_CARD", requirement: "SAU-SIS-124", label: "Caderneta de vacinação", filters: ["period", "unit", "query"] },
  { type: "VACCINATION_COVERAGE", requirement: "SAU-SIS-125", label: "Cobertura vacinal registrada", filters: ["period", "unit"] },
  { type: "LAB_SCHEDULE_MAP", requirement: "SAU-LAB-050", label: "Mapa de exames agendados", filters: ["period", "unit", "query"] },
  { type: "LAB_COMPLETED_COUNT", requirement: "SAU-LAB-051", label: "Quantitativo de exames realizados", filters: ["period", "unit"] },
  { type: "LAB_DAILY_SCHEDULE", requirement: "SAU-LAB-052", label: "Agendamentos diários por exame e paciente", filters: ["period", "unit", "query"] },
  { type: "LAB_PERCENTAGE", requirement: "SAU-LAB-053", label: "Percentual de exames", filters: ["period", "unit"] },
  { type: "LAB_FIXED_SCHEDULE", requirement: "SAU-LAB-054", label: "Cronograma por unidade", filters: ["unit"] },
  { type: "LAB_BY_COLLECTION_UNIT", requirement: "SAU-LAB-055", label: "Atendimentos por unidade de coleta", filters: ["period", "unit"] },
  { type: "LAB_RESULTS_COLLECTION_UNIT", requirement: "SAU-LAB-056", label: "Resultados por unidade de coleta", filters: ["period", "unit", "query"] },
  { type: "LAB_REQUESTED_COUNT", requirement: "SAU-LAB-057", label: "Exames solicitados no período", filters: ["period", "unit"] },
  { type: "LAB_PATIENT_COST", requirement: "SAU-LAB-058", label: "Histórico de valores por paciente", filters: ["period", "unit", "query"] },
  { type: "LAB_PATIENT_HISTORY", requirement: "SAU-LAB-059", label: "Histórico laboratorial do paciente", filters: ["period", "unit", "query"] },
  { type: "LAB_DELIVERY_BOOK", requirement: "SAU-LAB-060", label: "Livro de entrega de resultados", filters: ["period", "unit", "query"] },
  { type: "LAB_DAILY_COLLECTION", requirement: "SAU-LAB-061", label: "Mapa diário de coleta", filters: ["period", "unit"] },
  { type: "LAB_RESULTS_REQUEST_UNIT", requirement: "SAU-LAB-062", label: "Resultados por unidade solicitante", filters: ["period", "unit"] },
  { type: "LAB_PREGNANT_STATISTICS", requirement: "SAU-LAB-063", label: "Produção registrada para gestantes", filters: ["period", "unit"] },
  { type: "LAB_REQUEST_UNIT_STATISTICS", requirement: "SAU-LAB-064", label: "Atendimentos por unidade solicitante", filters: ["period", "unit"] },
  { type: "LAB_RESOURCE_PRICES", requirement: "SAU-LAB-065", label: "Valores de referência dos recursos", filters: ["unit", "query"] },
  { type: "LAB_RESOURCES_BY_UNIT", requirement: "SAU-LAB-066", label: "Recursos por unidade", filters: ["unit"] },
  { type: "LAB_EXAMS_BY_PATIENT", requirement: "SAU-LAB-067", label: "Exames realizados por paciente", filters: ["period", "unit", "query"] },
  { type: "LAB_EXAMS_BY_UNIT", requirement: "SAU-LAB-068", label: "Exames realizados por unidade", filters: ["period", "unit"] },
  { type: "LAB_PATIENTS_BY_RESULT", requirement: "SAU-LAB-069", label: "Pacientes por exame com resultado", filters: ["period", "unit", "query"] },
  { type: "LAB_COVID_RESULT", requirement: "SAU-LAB-070", label: "Resultados de exame COVID", filters: ["period", "unit", "query"] },
  { type: "LAB_REQUEST_COLLECTION_DECLARATION", requirement: "SAU-LAB-071", label: "Declaração de solicitação ou coleta", filters: ["period", "unit", "query"] },
  { type: "SPECIALIZED_PATIENT_FINANCIAL", requirement: "SAU-ESP-050", label: "Valores de referência por paciente", filters: ["period", "unit", "query"] },
  { type: "SPECIALIZED_PATIENT_HISTORY", requirement: "SAU-ESP-051", label: "Histórico especializado por paciente", filters: ["period", "unit", "query"] },
  { type: "SPECIALIZED_PATIENTS_BY_TEAM", requirement: "SAU-ESP-052", label: "Pacientes por equipe", filters: ["period", "unit", "team"] },
  { type: "SPECIALIZED_SUPPLIES_BY_PATIENT", requirement: "SAU-ESP-053", label: "Insumos por paciente", filters: ["period", "unit", "query"] },
  { type: "SPECIALIZED_PRODUCTS_BY_PATIENT", requirement: "SAU-ESP-054", label: "Produtos por paciente", filters: ["period", "unit", "query"] },
  { type: "SPECIALIZED_BATCHES_BY_PRODUCT", requirement: "SAU-ESP-055", label: "Lotes por produto", filters: ["period", "unit", "query"] },
  { type: "AGENDA_BIRTHDAYS", requirement: "SAU-AGE-073", label: "Aniversariantes do período", filters: ["period", "unit", "query"] },
  { type: "AGENDA_REGISTRATIONS", requirement: "SAU-AGE-074", label: "Pacientes cadastrados no período", filters: ["period", "unit", "query"] },
  { type: "AGENDA_BY_SPECIALTY", requirement: "SAU-AGE-076", label: "Agendamentos por especialidade", filters: ["period", "unit", "specialty"] },
  { type: "AGENDA_BY_PROFESSIONAL", requirement: "SAU-AGE-077", label: "Agendamentos por profissional", filters: ["period", "unit", "professional"] },
  { type: "AGENDA_WAIT_BY_SCHEDULE", requirement: "SAU-AGE-078", label: "Esperas por cronograma", filters: ["period", "unit", "specialty"] },
  { type: "AGENDA_WAIT_BY_SPECIALTY", requirement: "SAU-AGE-079", label: "Esperas por especialidade", filters: ["period", "unit"] },
  { type: "AGENDA_MISSED", requirement: "SAU-AGE-081", label: "Faltosos no período", filters: ["period", "unit", "query"] },
  { type: "AGENDA_QTY_VALUE", requirement: "SAU-AGE-082", label: "Quantitativo e percentual", filters: ["period", "unit"] },
  { type: "AGENDA_QTY_UNIT", requirement: "SAU-AGE-083", label: "Quantitativo por unidade", filters: ["period", "unit"] },
  { type: "AGENDA_SCHEDULE_FIXED", requirement: "SAU-AGE-007", label: "Cronogramas fixos", filters: ["unit"] },
  { type: "AGENDA_SCHEDULE_DAILY", requirement: "SAU-AGE-012", label: "Cronogramas diários", filters: ["period", "unit"] },
  { type: "AGENDA_STATS", requirement: "SAU-AGE-022", label: "Programadas, agendadas, disponíveis e espera", filters: ["period", "unit"] },
  { type: "AGENDA_MAPS", requirement: "SAU-AGE-026", label: "Mapas e listas da agenda", filters: ["period", "unit"] },
  { type: "AGENDA_AUDIT", requirement: "SAU-AGE-075", label: "Auditoria de alterações da agenda", filters: ["period"] },
  { type: "AGENDA_TRIAGE_PROF", requirement: "SAU-AGE-088", label: "Acolhimentos por profissional", filters: ["period", "unit", "professional"] },
  { type: "PRODSTAT_CID", requirement: "SAU-PRO-040", label: "Produção por CID", filters: ["unit", "professional", "cid", "municipality"] },
  { type: "PRODSTAT_CBO", requirement: "SAU-PRO-047", label: "Produção por CBO", filters: ["unit", "procedure"] },
  { type: "PRODSTAT_PROC_COMP", requirement: "SAU-PRO-048", label: "Produção por procedimento e competência", filters: ["unit", "procedure"] },
  { type: "PRODSTAT_PROF_UNIT", requirement: "SAU-PRO-049", label: "Produção por profissional e unidade", filters: ["unit", "professional"] },
  { type: "PRODSTAT_UNIT", requirement: "SAU-PRO-050", label: "Produção por unidade", filters: ["unit"] },
  { type: "PRODSTAT_VALUES", requirement: "SAU-PRO-051", label: "Produção e valores mensais", filters: ["unit"] },
  { type: "PRODSTAT_FINANCING", requirement: "SAU-PRO-052", label: "Produção por financiamento", filters: ["unit"] },
  { type: "PRODSTAT_EXAMS", requirement: "SAU-PRO-053", label: "Produção de exames", filters: ["period", "unit"] },
  { type: "PRODSTAT_PROC_GENERAL", requirement: "SAU-PRO-055", label: "Produção geral de procedimentos", filters: ["unit", "procedure"] },
  { type: "PRODSTAT_SEX", requirement: "SAU-PRO-056", label: "Produção por sexo", filters: ["unit"] },
  { type: "PRODSTAT_AGE", requirement: "SAU-PRO-042", label: "Produção por faixa de idade", filters: ["unit"] },
  { type: "PRODSTAT_TYPED", requirement: "SAU-PRO-059", label: "Produção digitada por competência", filters: ["unit"] },
  { type: "PRODSTAT_INDIVIDUAL", requirement: "SAU-PRO-064", label: "Produção individualizada", filters: ["unit", "professional", "procedure", "status"] },
  { type: "PRODSTAT_CHART_PROC", requirement: "SAU-PRO-060", label: "Gráfico comparativo por procedimento", filters: ["unit"] },
  { type: "PRODSTAT_CHART_VALUES", requirement: "SAU-PRO-061", label: "Gráfico de valores", filters: ["unit"] },
  { type: "PRODSTAT_CHART_UNIT", requirement: "SAU-PRO-062", label: "Gráfico por unidade e período", filters: ["unit"] },
  { type: "PRODSTAT_CHART_CBO", requirement: "SAU-PRO-063", label: "Gráfico por CBO e unidade", filters: ["unit"] },
  { type: "PAREP_ATTENDED", requirement: "SAU-PA-044", label: "Pacientes atendidos", filters: ["period", "unit", "professional", "query"] },
  { type: "PAREP_PROC_DAY", requirement: "SAU-PA-047", label: "Procedimentos do dia e triagens", filters: ["period", "unit"] },
  { type: "PAREP_BILLED", requirement: "SAU-PA-053", label: "Atendimentos realizados e faturados", filters: ["unit"] },
  { type: "PAREP_UNBILLED", requirement: "SAU-PA-054", label: "Atendimentos não faturados", filters: ["unit"] },
  { type: "PAREP_PROF_HOUR", requirement: "SAU-PA-057", label: "Atendimentos por profissional e hora", filters: ["period", "unit"] },
  { type: "PAREP_TRIAGE", requirement: "SAU-PA-058", label: "Triagens por unidade e data", filters: ["period", "unit", "query"] },
  { type: "PEPREP_ATT_PROF", requirement: "SAU-PEP-047", label: "Atendimentos por profissional", filters: ["period", "unit", "professional"] },
  { type: "PEPREP_PROC_PAT", requirement: "SAU-PEP-048", label: "Procedimentos por paciente", filters: ["period", "unit", "professional", "query"] },
  { type: "PEPREP_EXAM_MED", requirement: "SAU-PEP-055", label: "Exames por médico", filters: ["period", "unit", "professional", "query"] },
  { type: "PEPREP_PROC_QTY", requirement: "SAU-PEP-059", label: "Procedimentos por unidade e profissional", filters: ["period", "unit", "professional"] },
  { type: "LABREP_DAILY", requirement: "SAU-LAB-052", label: "Agendamentos diários e mapa de coleta", filters: ["period", "unit"] },
  { type: "LABREP_QTY", requirement: "SAU-LAB-057", label: "Exames solicitados quantitativo", filters: ["period", "unit"] },
  { type: "LABREP_PCT", requirement: "SAU-LAB-053", label: "Percentual de exames", filters: ["period", "unit"] },
  { type: "LABREP_FIXED", requirement: "SAU-LAB-054", label: "Cronograma por unidade de coleta", filters: ["period", "unit"] },
  { type: "LABREP_COLLECTION_UNIT", requirement: "SAU-LAB-055", label: "Atendimentos por unidade de coleta", filters: ["period", "unit"] },
  { type: "LABREP_REQUEST_UNIT", requirement: "SAU-LAB-062", label: "Resultados por unidade solicitante", filters: ["period", "unit"] },
  { type: "LABREP_PATIENT", requirement: "SAU-LAB-067", label: "Exames realizados por paciente", filters: ["period", "unit", "query"] },
  { type: "LABREP_RESULT", requirement: "SAU-LAB-069", label: "Pacientes com resultado", filters: ["period", "unit", "query"] },
  { type: "LABREP_DECL", requirement: "SAU-LAB-071", label: "Declarações de solicitação e coleta", filters: ["period", "unit", "query"] },
  { type: "LABREP_COVID", requirement: "SAU-LAB-070", label: "Resultados de exame COVID", filters: ["period", "unit", "query"] },
  { type: "LABREP_COST", requirement: "SAU-LAB-058", label: "Gastos por paciente", filters: ["period", "unit", "query"] },
  { type: "LABREP_PRICES", requirement: "SAU-LAB-065", label: "Tabela de preços de recursos", filters: ["query"] },
  { type: "LABREP_MAPTECH", requirement: "SAU-LAB-050", label: "Mapa de exames para técnicos", filters: ["period", "unit"] },
  { type: "REGREP_REQUESTS", requirement: "SAU-REG-087", label: "Solicitações por situação", filters: ["period", "unit", "professional", "status", "query"] },
  { type: "REGREP_WAIT", requirement: "SAU-REG-088", label: "Espera por serviço", filters: ["period", "unit"] },
  { type: "REGREP_URGENT", requirement: "SAU-REG-089", label: "Urgentes em aberto", filters: ["unit"] },
  { type: "REGREP_PATIENT", requirement: "SAU-REG-090", label: "Pacientes por município", filters: ["period", "unit", "municipality"] },
  { type: "REGREP_COST", requirement: "SAU-REG-092", label: "Gasto por prestador", filters: ["period", "unit"] },
  { type: "REGREP_TRIPS", requirement: "SAU-REG-093", label: "Viagens por motorista", filters: ["period"] },
  { type: "REGREP_AUDIT", requirement: "SAU-REG-094", label: "Auditoria de viagens e regulação", filters: ["period", "unit"] },
  { type: "REGREP_QTY", requirement: "SAU-REG-095", label: "Quantitativo por situação", filters: ["period", "unit"] },
  { type: "REGREP_THIRD", requirement: "SAU-REG-096", label: "Terceiros por período e cotas", filters: ["unit"] },
  { type: "REGREP_EXAMS", requirement: "SAU-REG-098", label: "Exames agendados", filters: ["period", "unit"] },
  { type: "REGREP_REQUEST_UNIT", requirement: "SAU-REG-099", label: "Solicitações por unidade", filters: ["period", "unit"] },
  { type: "REGREP_STATS", requirement: "SAU-REG-102", label: "Mais solicitados", filters: ["period", "unit"] },
  { type: "REGREP_FIN", requirement: "SAU-REG-104", label: "Serviços por prestador financeiro", filters: ["period", "unit"] },
  { type: "SISREP_AGENTS", requirement: "SAU-SIS-107", label: "Agentes por área e equipe", filters: ["period", "unit", "team"] },
  { type: "SISREP_PROD", requirement: "SAU-SIS-109", label: "Produção individual e equipe", filters: ["period", "unit", "team", "professional"] },
  { type: "SISREP_ISSUE", requirement: "SAU-SIS-110", label: "Problemas por profissional", filters: ["period", "unit"] },
  { type: "SISREP_SPEC", requirement: "SAU-SIS-111", label: "Percentual por ficha", filters: ["period", "unit"] },
  { type: "SISREP_GEST", requirement: "SAU-SIS-113", label: "Gestantes acompanhadas", filters: ["period", "unit"] },
  { type: "SISREP_ODONTO", requirement: "SAU-SIS-114", label: "Produção odontológica por equipe", filters: ["period", "unit", "team"] },
  { type: "SISREP_HOME", requirement: "SAU-SIS-116", label: "Produção domiciliar por equipe", filters: ["period", "unit", "team"] },
  { type: "SISREP_VISIT", requirement: "SAU-SIS-117", label: "Produção de visitas por equipe", filters: ["period", "unit", "team"] },
  { type: "SISREP_COLLECTIVE", requirement: "SAU-SIS-119", label: "Atividade coletiva por profissional", filters: ["period", "unit", "professional"] },
  { type: "SISREP_PROCPROF", requirement: "SAU-SIS-126", label: "Procedimentos por profissional", filters: ["period", "unit", "professional"] },
  { type: "SISREP_FAMILIES", requirement: "SAU-SIS-131", label: "Famílias por agente", filters: ["query"] },
  { type: "SISREP_HOUSE", requirement: "SAU-SIS-134", label: "Moradia sintético e Coelho", filters: ["query"] },
  { type: "SISREP_ATT_UNIT", requirement: "SAU-SIS-139", label: "Atendimentos por unidade", filters: ["period", "unit"] },
  { type: "SISREP_VISITS", requirement: "SAU-SIS-140", label: "Visitas por profissional e data", filters: ["period", "unit", "professional"] },
  { type: "SISREP_EXPORT", requirement: "SAU-SIS-142", label: "Resumo da exportação e-SUS", filters: [] },
  { type: "VIGREP_RISK", requirement: "SAU-VIG-014", label: "Inspeções por grau de risco", filters: [] },
  { type: "VIGREP_STATUS", requirement: "SAU-VIG-015", label: "Estabelecimentos por situação", filters: ["status", "query"] },
  { type: "VIGREP_CNAE", requirement: "SAU-VIG-016", label: "Estabelecimentos por CNAE", filters: [] },
  { type: "VIGREP_QTY", requirement: "SAU-VIG-017", label: "Quantitativo por risco e situação", filters: [] },
  { type: "VIGREP_COMPLAINTS", requirement: "SAU-VIG-018", label: "Denúncias cadastradas", filters: ["query"] },
  { type: "VIGREP_INSPECTIONS", requirement: "SAU-VIG-019", label: "Inspeções cadastradas", filters: ["query"] },
  { type: "VIGREP_TECH", requirement: "SAU-VIG-021", label: "Relatório técnico sanitário", filters: ["query"] },
  { type: "AUDIT_ACCESS_DETAIL", requirement: "SAU-TEC-017", label: "Acessos detalhados por usuário", filters: ["period"] },
  { type: "AUDIT_PATIENT_CHANGES", requirement: "SAU-AGE-075", label: "Alterações de cadastro de paciente", filters: ["period"] },
  { type: "DOC_DISPENSATION", requirement: "SAU-FAR-031", label: "Comprovante de dispensação", filters: ["record"] },
  { type: "DOC_TRANSFER_RECEIPT", requirement: "SAU-FAR-033", label: "Recibo de transferência", filters: ["record"] },
  { type: "DOC_APPOINTMENT", requirement: "SAU-AGE-046", label: "Comprovante de agendamento", filters: ["record"] },
  { type: "DOC_LAB_COLLECTION", requirement: "SAU-LAB-033", label: "Comprovante de coleta", filters: ["record"] },
  { type: "DOC_REGULATION_GUIDE", requirement: "SAU-REG-024", label: "Guia de autorização", filters: ["record"] },
  { type: "DOC_REGULATION_SCHEDULE", requirement: "SAU-REG-035", label: "Comprovante de agendamento regulado", filters: ["record"] },
  { type: "DOC_TFD_LIST", requirement: "SAU-REG-059", label: "Lista de passageiros TFD", filters: ["record"] },
  { type: "DOC_TFD_PUBLIC", requirement: "SAU-REG-101", label: "Comprovante de transporte", filters: ["record"] },
  { type: "DOC_TFD_AUTH", requirement: "SAU-REG-076", label: "Autorização de TFD", filters: ["record"] },
  { type: "DOC_PA_BAU", requirement: "SAU-PA-026", label: "Boletim de atendimento", filters: ["record"] },
  { type: "DOC_PA_DISCHARGE", requirement: "SAU-PA-031", label: "Declaração de alta", filters: ["record"] },
  { type: "DOC_PATIENT_CARD", requirement: "SAU-AGE-054", label: "Carteirinha do paciente", filters: ["record"] },
  { type: "DOC_LICENSE", requirement: "SAU-VIG-011", label: "Alvará sanitário", filters: ["record"] },
] as const;

export type HealthAdministrativeReportType = (typeof healthAdministrativeReportOptions)[number]["type"];
export type HealthReportFilter = (typeof healthAdministrativeReportOptions)[number]["filters"][number];

export function isHealthAdministrativeReportType(value: string | null | undefined): value is HealthAdministrativeReportType {
  return healthAdministrativeReportOptions.some(option => option.type === value);
}

export function getHealthReportOption(type: HealthAdministrativeReportType) {
  return healthAdministrativeReportOptions.find(option => option.type === type)!;
}
