"use client";

import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, HeartPulse, Megaphone, UserPlus, X } from "lucide-react";
import { ErpListFrame } from "@/components/app-ui/erp/ErpListFrame";
import { callHealthAppointmentAction, createSpontaneousCareAction, registerHealthTriageAction } from "./actions";

type Appointment = { id: string; date: string; origin: string; status: string; priority: string; arrivedAt: string | null; calledAt: string | null; patient: { person: { fullName: string } }; unit: { name: string }; triage: { riskClassification: string; chiefComplaint: string } | null };
type Patient = { id: string; cns: string | null; person: { fullName: string } };
type Unit = { id: string; name: string };
const riskOrder: Record<string, number> = { Emergência: 0, "Muita urgência": 1, Urgente: 2, "Pouco urgente": 3, "Não urgente": 4 };
const field = "min-h-10 w-full rounded border border-slate-300 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/15";

export default function AcolhimentoClient({ appointments, patients, units, canCreate, canUpdate, hasProfessional }: { appointments: Appointment[]; patients: Patient[]; units: Unit[]; canCreate: boolean; canUpdate: boolean; hasProfessional: boolean }) {
  const router = useRouter();
  const locked = useRef(false);
  const [pending, startTransition] = useTransition();
  const [dialog, setDialog] = useState<"arrival" | "triage" | null>(null);
  const [selected, setSelected] = useState("");
  const [error, setError] = useState("");
  const queue = [...appointments].sort((a, b) => (riskOrder[a.triage?.riskClassification || ""] ?? 9) - (riskOrder[b.triage?.riskClassification || ""] ?? 9) || new Date(a.arrivedAt || a.date).getTime() - new Date(b.arrivedAt || b.date).getTime());

  function execute(operation: () => Promise<{ error?: string }>, close = true) {
    if (locked.current) return;
    locked.current = true; setError("");
    startTransition(async () => { try { const result = await operation(); if (result.error) { setError(result.error); return; } if (close) setDialog(null); router.refresh(); } catch { setError("Não foi possível consultar a confirmação. Tente novamente."); } finally { locked.current = false; } });
  }

  function arrival(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    execute(() => createSpontaneousCareAction({ patientId: data.get("patientId"), unitId: data.get("unitId"), professionalId: null, specialtyId: null, serviceId: null, arrivalNotes: data.get("arrivalNotes"), priority: data.get("priority") }));
  }

  function triage(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const number = (key: string) => data.get(key) ? Number(String(data.get(key)).replace(",", ".")) : null;
    execute(() => registerHealthTriageAction({ appointmentId: selected, chiefComplaint: data.get("chiefComplaint"), bloodPressure: data.get("bloodPressure") || null, temperature: number("temperature"), weight: number("weight"), height: number("height"), heartRate: number("heartRate"), respiratoryRate: number("respiratoryRate"), oxygenSaturation: number("oxygenSaturation"), bloodGlucose: number("bloodGlucose"), observedConditions: data.get("observedConditions") || null, riskClassification: data.get("riskClassification"), priorityLabel: data.get("riskClassification"), notes: data.get("notes") || null }));
  }

  return <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-hidden">
    {error && <div role="alert" className="flex items-center gap-2 rounded border border-red-200 bg-red-50 p-2 text-sm text-red-800"><AlertCircle className="size-4" />{error}</div>}
    <div className="flex shrink-0 flex-wrap items-center justify-between gap-2 rounded border bg-white p-2"><div><h2 className="text-sm font-semibold">Fila da unidade</h2><p className="text-xs text-slate-500">Ordenação por risco e horário de chegada.</p></div><div className="flex gap-2">{canCreate && <button disabled={pending || !patients.length || !units.length} onClick={() => setDialog("arrival")} className="inline-flex min-h-10 items-center gap-2 rounded bg-rose-700 px-3 text-sm font-semibold text-white disabled:opacity-50"><UserPlus className="size-4" />Demanda espontânea</button>}</div></div>
    {canUpdate && !hasProfessional && <p className="rounded border border-amber-200 bg-amber-50 p-2 text-sm text-amber-900">O acolhimento clínico exige vínculo ativo do usuário com um profissional de saúde.</p>}
    <ErpListFrame><table className="w-full table-fixed text-left text-xs"><thead className="sticky top-0 z-10 bg-slate-100 text-[10px] uppercase text-slate-600"><tr><th className="w-20 p-2">Chegada</th><th className="p-2">Paciente</th><th className="hidden p-2 md:table-cell">Unidade</th><th className="w-32 p-2">Risco</th><th className="hidden p-2 lg:table-cell">Queixa</th><th className="w-44 p-2 text-right">Ações</th></tr></thead><tbody className="divide-y">{queue.length ? queue.map(item => <tr key={item.id} className="h-10 hover:bg-slate-50"><td className="p-2">{new Date(item.arrivedAt || item.date).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</td><td className="truncate p-2 font-medium">{item.patient.person.fullName}<span className="ml-1 text-[10px] text-slate-400">{item.origin === "SPONTANEOUS" ? "PA" : "Agenda"}</span></td><td className="hidden truncate p-2 md:table-cell">{item.unit.name}</td><td className="p-2"><span className="rounded bg-slate-100 px-1.5 py-1">{item.triage?.riskClassification || "Aguardando"}</span></td><td className="hidden truncate p-2 lg:table-cell">{item.triage?.chiefComplaint || "-"}</td><td className="p-2"><div className="flex justify-end gap-1">{canUpdate && hasProfessional && <button disabled={pending} onClick={() => { setSelected(item.id); setDialog("triage"); }} className="rounded border px-2 py-1 font-medium"><HeartPulse className="mr-1 inline size-3" />Acolher</button>}{canUpdate && item.triage && <button disabled={pending} onClick={() => execute(() => callHealthAppointmentAction(item.id), false)} className="rounded border border-emerald-300 px-2 py-1 font-medium text-emerald-800"><Megaphone className="mr-1 inline size-3" />Chamar</button>}</div></td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-slate-500">Nenhum paciente aguardando.</td></tr>}</tbody></table></ErpListFrame>
    {dialog === "arrival" && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={arrival} className="w-full max-w-xl rounded-lg bg-white shadow-xl"><header className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Entrada por demanda espontânea</h2><p className="text-sm text-slate-500">Registre a procura para inclusão imediata na fila.</p></div><button type="button" onClick={() => setDialog(null)}><X className="size-5" /></button></header><div className="grid gap-4 p-4 md:grid-cols-2"><label className="md:col-span-2 text-sm font-medium">Paciente<select required name="patientId" className={`mt-1 ${field}`}><option value="">Selecione</option>{patients.map(item => <option key={item.id} value={item.id}>{item.person.fullName}{item.cns ? ` · CNS ${item.cns}` : ""}</option>)}</select></label><label className="text-sm font-medium">Unidade<select required name="unitId" className={`mt-1 ${field}`}><option value="">Selecione</option>{units.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Prioridade administrativa<select name="priority" className={`mt-1 ${field}`}><option>Normal</option><option>Prioridade</option><option>Urgência</option></select></label><label className="md:col-span-2 text-sm font-medium">Motivo da procura<textarea required name="arrivalNotes" rows={4} maxLength={2000} className={`mt-1 py-2 ${field}`} /></label></div><footer className="flex justify-end gap-2 border-t p-3"><button type="button" onClick={() => setDialog(null)} className="min-h-10 rounded border px-3">Cancelar</button><button disabled={pending} className="min-h-10 rounded bg-rose-700 px-4 font-semibold text-white">Incluir na fila</button></footer></form></div>}
    {dialog === "triage" && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={triage} className="max-h-[92dvh] w-full max-w-3xl overflow-y-auto rounded-lg bg-white shadow-xl"><header className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Ficha de acolhimento</h2><p className="text-sm text-slate-500">Sinais vitais e classificação de risco ficam vinculados ao episódio.</p></div><button type="button" onClick={() => setDialog(null)}><X className="size-5" /></button></header><div className="grid gap-3 p-4 md:grid-cols-4"><label className="md:col-span-4 text-sm font-medium">Queixa principal<textarea required name="chiefComplaint" rows={3} maxLength={2000} className={`mt-1 py-2 ${field}`} /></label>{[["bloodPressure", "Pressão arterial"], ["temperature", "Temperatura (°C)"], ["weight", "Peso (kg)"], ["height", "Altura (m)"], ["heartRate", "Freq. cardíaca"], ["respiratoryRate", "Freq. respiratória"], ["oxygenSaturation", "Saturação (%)"], ["bloodGlucose", "Glicemia"]].map(([name, label]) => <label key={name} className="text-sm font-medium">{label}<input name={name} inputMode="decimal" className={`mt-1 ${field}`} /></label>)}<label className="md:col-span-2 text-sm font-medium">Classificação de risco<select required name="riskClassification" className={`mt-1 ${field}`}><option>Não urgente</option><option>Pouco urgente</option><option>Urgente</option><option>Muita urgência</option><option>Emergência</option></select></label><label className="md:col-span-2 text-sm font-medium">Condições observadas<input name="observedConditions" maxLength={5000} className={`mt-1 ${field}`} /></label><label className="md:col-span-4 text-sm font-medium">Observações<textarea name="notes" rows={3} maxLength={5000} className={`mt-1 py-2 ${field}`} /></label></div><footer className="flex justify-end gap-2 border-t p-3"><button type="button" onClick={() => setDialog(null)} className="min-h-10 rounded border px-3">Cancelar</button><button disabled={pending} className="min-h-10 rounded bg-emerald-700 px-4 font-semibold text-white">Salvar acolhimento</button></footer></form></div>}
  </div>;
}
