"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Save } from "lucide-react";
import { saveDiaryAction, saveGradesAction } from "./actions";

type Student = { id: string; name: string; code: string; status: string; enrollmentDate: string };
type ClassData = { id: string; label: string; subjects: { id: string; name: string }[]; students: Student[] };
type Assessment = { id: string; label: string; mode: string; maxScore: number | null; students: Student[]; grades: Record<string, { value: number | null; concept: string; absent: boolean; recoveryValue: number | null; feedback: string }> };
const field = "h-8 rounded border border-slate-200 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-950";

export function ProfessorEntryGrids({ teacherId, classes, assessments }: { teacherId: string; classes: ClassData[]; assessments: Assessment[] }) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [notice,setNotice]=useState("");
  const [classId,setClassId]=useState(classes[0]?.id||""); const activeClass=classes.find((item)=>item.id===classId); const [presence,setPresence]=useState<Record<string,boolean>>({});
  const [assessmentId,setAssessmentId]=useState(assessments[0]?.id||""); const activeAssessment=assessments.find((item)=>item.id===assessmentId); const [gradeDraft,setGradeDraft]=useState<Record<string,{value?:string;concept?:string;absent?:boolean;recoveryValue?:string;feedback?:string}>>({});
  const attendanceRows=useMemo(()=>activeClass?.students||[],[activeClass]);
  const submit=(action:(data:FormData)=>Promise<{error:string|null;message?:string}>,data:FormData)=>startTransition(async()=>{const result=await action(data);setNotice(result.error||result.message||"");if(!result.error)router.refresh();});
  return <div className="grid gap-2 xl:grid-cols-2">
    <details className="rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-blue-700">Registrar chamada e conteúdo</summary><form className="space-y-2 border-t p-3" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);data.set("teacherId",teacherId);data.set("attendances",JSON.stringify(attendanceRows.map((student)=>({studentId:student.id,isPresent:presence[student.id]!==false}))));submit(saveDiaryAction,data)}}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><select name="classId" value={classId} onChange={(e)=>setClassId(e.target.value)} className={field}>{classes.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><select name="subjectId" required className={field}>{activeClass?.subjects.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="date" type="date" required className={field}/><select name="stage" className={field}>{["1º Bimestre","2º Bimestre","3º Bimestre","4º Bimestre","Final"].map((x)=><option key={x}>{x}</option>)}</select><input name="lessonCount" type="number" min="1" defaultValue="1" className={field}/><input name="contentTaught" required placeholder="Conteúdo ministrado" className={`${field} lg:col-span-3`}/></div><div className="max-h-52 overflow-y-auto rounded border"><table className="w-full table-fixed text-xs"><thead className="sticky top-0 bg-slate-100 text-[10px] uppercase"><tr><th className="w-12 p-2">Ordem</th><th className="p-2 text-left">Aluno</th><th className="w-24 p-2">Presente</th></tr></thead><tbody>{attendanceRows.map((student,index)=><tr key={student.id} className="h-8 border-t"><td className="text-center">{index+1}</td><td className="truncate px-2">{student.name}</td><td className="text-center"><input type="checkbox" checked={presence[student.id]!==false} onChange={(e)=>setPresence({...presence,[student.id]:e.target.checked})}/></td></tr>)}</tbody></table></div><input name="observations" placeholder="Observações da aula" className={`${field} w-full`}/><button disabled={pending} className="inline-flex h-8 items-center gap-1 rounded bg-blue-600 px-3 text-xs font-semibold text-white">{pending?<Loader2 className="size-3 animate-spin"/>:<Save className="size-3"/>}Salvar diário</button></form></details>
    <details className="rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-blue-700">Lançar notas, conceitos e recuperação</summary><form className="space-y-2 border-t p-3" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);data.set("teacherId",teacherId);data.set("assessmentId",assessmentId);data.set("grades",JSON.stringify((activeAssessment?.students||[]).map((student)=>{const old=activeAssessment?.grades[student.id],draft=gradeDraft[student.id]||{};return {studentId:student.id,value:draft.value===""?null:Number(draft.value??old?.value??0),concept:draft.concept??old?.concept??"",absent:draft.absent??old?.absent??false,recoveryValue:draft.recoveryValue?Number(draft.recoveryValue):old?.recoveryValue??null,feedback:draft.feedback??old?.feedback??""}})));submit(saveGradesAction,data)}}><select value={assessmentId} onChange={(e)=>{setAssessmentId(e.target.value);setGradeDraft({})}} className={`${field} w-full`}>{assessments.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><div className="max-h-64 overflow-y-auto rounded border"><table className="w-full table-fixed text-xs"><thead className="sticky top-0 bg-slate-100 text-[10px] uppercase"><tr><th className="p-2 text-left">Aluno</th><th className="w-20 p-2">Nota</th><th className="w-20 p-2">Conceito</th><th className="w-16 p-2">Ausente</th><th className="w-20 p-2">Recup.</th></tr></thead><tbody>{activeAssessment?.students.map((student)=>{const old=activeAssessment.grades[student.id],draft=gradeDraft[student.id]||{};const update=(part:object)=>setGradeDraft({...gradeDraft,[student.id]:{...draft,...part}});return <tr key={student.id} className="h-9 border-t"><td className="truncate px-2">{student.name}</td><td><input type="number" step="0.01" max={activeAssessment.maxScore||undefined} value={draft.value??old?.value??""} onChange={(e)=>update({value:e.target.value})} className="h-7 w-16 rounded border px-1"/></td><td><input value={draft.concept??old?.concept??""} onChange={(e)=>update({concept:e.target.value})} className="h-7 w-16 rounded border px-1"/></td><td className="text-center"><input type="checkbox" checked={draft.absent??old?.absent??false} onChange={(e)=>update({absent:e.target.checked})}/></td><td><input type="number" step="0.01" value={draft.recoveryValue??old?.recoveryValue??""} onChange={(e)=>update({recoveryValue:e.target.value})} className="h-7 w-16 rounded border px-1"/></td></tr>})}</tbody></table></div><button disabled={pending||!activeAssessment} className="inline-flex h-8 items-center gap-1 rounded bg-blue-600 px-3 text-xs font-semibold text-white disabled:opacity-50"><Save className="size-3"/>Salvar resultados</button></form></details>
    {notice&&<p className="text-xs text-slate-600 xl:col-span-2" role="status">{notice}</p>}
  </div>;
}
