import PDFDocument from "pdfkit";
import { Prisma } from "@prisma/client";
export type Party={name:string;document:string;municipalInsc:string;phone:string;email:string;address:string};
export type Danfse={number:number;code:string;status:string;competence:string;issuedAt:Date;institution:{name:string;cnpj:string;phone:string;email:string;city:string;state:string};provider:Party;taker:Party;description:string;serviceLocation:string;serviceValue:string;deductions:string;base:string;rate:string;iss:string;retention:string;authenticity:string};
const brl=(value:string)=>Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function renderPdf(input:Danfse){return new Promise<Uint8Array>((resolve,reject)=>{const doc=new PDFDocument({size:"A4",margin:18,info:{Title:`DANFSe NFS-e ${input.number}`,Author:input.institution.name}});const chunks:Buffer[]=[];doc.on("data",(chunk:Buffer)=>chunks.push(chunk));doc.on("end",()=>resolve(new Uint8Array(Buffer.concat(chunks))));doc.on("error",reject);const left=18,width=559;const line=()=>doc.moveTo(left,doc.y).lineTo(left+width,doc.y).strokeColor("#111827").lineWidth(.6).stroke();const section=(title:string)=>{line();const y=doc.y+2;doc.font("Helvetica-Bold").fontSize(9).fillColor("#111827").text(title.toUpperCase(),left+3,y,{width:553});doc.y=y+12;};const row=(items:{label:string;value:string;width:number}[])=>{const y=doc.y+2;doc.font("Helvetica-Bold").fontSize(6.5);const labelHeight=Math.max(...items.map(item=>doc.heightOfString(item.label,{width:item.width-6})));const valueY=y+labelHeight+2;let x=left+3;let height=labelHeight+14;for(const item of items){doc.font("Helvetica-Bold").fontSize(6.5).text(item.label,x,y,{width:item.width-6});doc.font("Helvetica").fontSize(8).text(item.value||"-",x,valueY,{width:item.width-6});height=Math.max(height,labelHeight+doc.heightOfString(item.value||"-",{width:item.width-6})+5);x+=item.width;}doc.y=y+height;};doc.rect(8,8,579,826).lineWidth(1).stroke("#111827");
  doc.font("Helvetica-Bold").fontSize(20).fillColor("#059669").text("NFS-e",left+4,18,{width:100});doc.fillColor("#111827").fontSize(12).text("DANFSe v1.0",170,18,{width:220,align:"center"}).fontSize(10).text("Documento Auxiliar da NFS-e",170,33,{width:220,align:"center"});doc.font("Helvetica-Bold").fontSize(9).text(input.institution.name.toUpperCase(),400,18,{width:165,align:"right"});doc.font("Helvetica").fontSize(7).text([input.institution.cnpj,input.institution.phone,input.institution.email,`${input.institution.city} - ${input.institution.state}`].filter(Boolean).join("\n"),400,30,{width:165,align:"right"});doc.y=64;line();
  row([{label:"CHAVE / CÓDIGO DE ACESSO DA NFS-e",value:input.code,width:410},{label:"AUTENTICIDADE",value:"Consulta pelo código\nQR: configuração pendente",width:149}]);row([{label:"NÚMERO DA NFS-e",value:String(input.number),width:140},{label:"COMPETÊNCIA",value:input.competence,width:140},{label:"DATA E HORA DA EMISSÃO",value:input.issuedAt.toLocaleString("pt-BR"),width:279}]);
  section("Emitente da NFS-e");row([{label:"PRESTADOR DO SERVIÇO",value:input.provider.name,width:260},{label:"CPF/CNPJ",value:input.provider.document,width:150},{label:"INSCRIÇÃO MUNICIPAL",value:input.provider.municipalInsc,width:149}]);row([{label:"ENDEREÇO",value:input.provider.address,width:260},{label:"E-MAIL",value:input.provider.email,width:150},{label:"TELEFONE",value:input.provider.phone,width:149}]);
  section("Tomador do serviço");row([{label:"NOME / NOME EMPRESARIAL",value:input.taker.name,width:260},{label:"CPF/CNPJ",value:input.taker.document,width:150},{label:"INSCRIÇÃO MUNICIPAL",value:input.taker.municipalInsc,width:149}]);row([{label:"ENDEREÇO",value:input.taker.address,width:260},{label:"E-MAIL",value:input.taker.email,width:150},{label:"TELEFONE",value:input.taker.phone,width:149}]);
  section("Serviço prestado");row([{label:"CÓDIGO DE TRIBUTAÇÃO NACIONAL",value:"Configuração pendente",width:190},{label:"CÓDIGO DE TRIBUTAÇÃO MUNICIPAL",value:"Configuração pendente",width:190},{label:"LOCAL DA PRESTAÇÃO",value:input.serviceLocation,width:179}]);row([{label:"DESCRIÇÃO DO SERVIÇO",value:input.description,width:559}]);
  section("Tributação municipal");row([{label:"TRIBUTAÇÃO DO ISSQN",value:"Operação tributável",width:140},{label:"MUNICÍPIO DE INCIDÊNCIA",value:input.serviceLocation,width:140},{label:"REGIME ESPECIAL",value:"Configuração pendente",width:140},{label:"RETENÇÃO DO ISSQN",value:input.retention==="RETIDO"?"Retido":"Não retido",width:139}]);row([{label:"VALOR DO SERVIÇO",value:brl(input.serviceValue),width:112},{label:"DEDUÇÕES / REDUÇÕES",value:brl(input.deductions),width:112},{label:"BASE DE CÁLCULO",value:brl(input.base),width:112},{label:"ALÍQUOTA APLICADA",value:`${input.rate}%`,width:111},{label:"ISSQN APURADO",value:brl(input.iss),width:112}]);
  section("Tributação federal");row([{label:"IRRF",value:"Configuração pendente",width:112},{label:"CONTRIBUIÇÃO PREVIDENCIÁRIA",value:"Configuração pendente",width:112},{label:"PIS",value:"Configuração pendente",width:112},{label:"COFINS",value:"Configuração pendente",width:111},{label:"CSLL",value:"Configuração pendente",width:112}]);
  const liquid=new Prisma.Decimal(input.serviceValue).minus(input.deductions).minus(input.retention==="RETIDO"?input.iss:0).toFixed(2);section("Valor total da NFS-e");row([{label:"VALOR DO SERVIÇO",value:brl(input.serviceValue),width:140},{label:"TOTAL DE DEDUÇÕES",value:brl(input.deductions),width:140},{label:"ISSQN RETIDO",value:input.retention==="RETIDO"?brl(input.iss):"R$ 0,00",width:140},{label:"VALOR LÍQUIDO",value:brl(liquid),width:139}]);
  section("Informações complementares");doc.font("Helvetica").fontSize(7.5).text(`Situação: ${input.status}. Autenticidade: ${input.authenticity}. Documento municipal demonstrativo; campos oficiais pendentes estão identificados para configuração e homologação.`,left+3,doc.y+3,{width:553});doc.y+=35;line();doc.fontSize(6.5).fillColor("#475569").text("O layout segue a organização do DANFSe nacional fornecido como referência, sem reproduzir brasão, chave, QR ou validação oficial de outro município.",left+3,doc.y+4,{width:553});doc.end();});}
