import { Prisma } from "@prisma/client";

export class TributarioS7Error extends Error {}
function decimal(value: Prisma.Decimal | string | number, label: string, signed = false) { const result = new Prisma.Decimal(String(value)); if (!result.isFinite() || (!signed && result.lessThan(0))) throw new TributarioS7Error(`${label} inválido.`); return result.toDecimalPlaces(2); }

export function calculateFiscalAssessment(input: { originalBase?: number | string | Prisma.Decimal; assessedBase: number | string | Prisma.Decimal; rate: number | string | Prisma.Decimal; penaltyRate?: number | string | Prisma.Decimal; interestRate?: number | string | Prisma.Decimal; correctionRate?: number | string | Prisma.Decimal; discountRate?: number | string | Prisma.Decimal }) {
  const originalBase = decimal(input.originalBase ?? 0, "Base original"); const assessedBase = decimal(input.assessedBase, "Base apurada"); const rate = decimal(input.rate, "Alíquota"); if (assessedBase.lessThan(originalBase)) throw new TributarioS7Error("A base apurada deve representar a base total comparável.");
  const differenceBase = assessedBase.minus(originalBase).toDecimalPlaces(2); const principal = differenceBase.mul(rate).div(100).toDecimalPlaces(2); const penalty = principal.mul(decimal(input.penaltyRate ?? 0, "Multa")).div(100).toDecimalPlaces(2); const interest = principal.mul(decimal(input.interestRate ?? 0, "Juros")).div(100).toDecimalPlaces(2); const correction = principal.mul(decimal(input.correctionRate ?? 0, "Correção")).div(100).toDecimalPlaces(2); const discount = penalty.mul(decimal(input.discountRate ?? 0, "Desconto")).div(100).toDecimalPlaces(2); const total = principal.plus(penalty).plus(interest).plus(correction).minus(discount).toDecimalPlaces(2);
  return { originalBase, assessedBase, differenceBase, rate, principal, penalty, interest, correction, discount, total };
}

export function pointsForValue(input: { value: number; defaultPoints: number; ranges?: { min: number; max?: number | null; points: number }[] }) { const value = decimal(input.value, "Valor da tarefa"); const matches = (input.ranges ?? []).filter(range => value.greaterThanOrEqualTo(range.min) && (range.max == null || value.lessThanOrEqualTo(range.max))); if (matches.length > 1) throw new TributarioS7Error("As faixas de pontos se sobrepõem."); return decimal(matches[0]?.points ?? input.defaultPoints, "Pontos"); }

export function calculateFiscalProductivity(input: { taskPoints: (number | string | Prisma.Decimal)[]; pointValue: number | string | Prisma.Decimal; cap: number | string | Prisma.Decimal; adjustment?: number | string | Prisma.Decimal }) {
  const points = input.taskPoints.reduce<Prisma.Decimal>((sum, value) => sum.plus(decimal(value, "Pontos")), new Prisma.Decimal(0)).toDecimalPlaces(2); const pointValue = decimal(input.pointValue, "Valor do ponto"); const cap = decimal(input.cap, "Teto"); const adjustment = decimal(input.adjustment ?? 0, "Ajuste", true); const gross = points.mul(pointValue).toDecimalPlaces(2); const capped = Prisma.Decimal.min(gross, cap).toDecimalPlaces(2); const excess = Prisma.Decimal.max(gross.minus(cap), 0).toDecimalPlaces(2); const result = capped.plus(adjustment).toDecimalPlaces(2); if (result.lessThan(0)) throw new TributarioS7Error("O ajuste não pode tornar a produtividade negativa."); return { points, pointValue, gross, cap, capped, excess, adjustment, result };
}

export function classifyFiscalFinding(input: { observed: number; declared: number; rate: number }) { const observed = decimal(input.observed, "Valor observado"); const declared = decimal(input.declared, "Valor declarado"); const difference = Prisma.Decimal.max(observed.minus(declared), 0).toDecimalPlaces(2); return { observed, declared, difference, potentialTax: difference.mul(decimal(input.rate, "Alíquota")).div(100).toDecimalPlaces(2), status: difference.greaterThan(0) ? "INDICIO" : "SEM_DIVERGENCIA" as const }; }
