"use server";

import PDFDocument from "pdfkit";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation, isSystemAdministrator } from "@/lib/platform/tenant-context";

export type S3ActionResult={error:string|null;message?:string};
export type DocumentActionResult=S3ActionResult&{download?:{fileName:string;base64:string}};
const v=(d:FormData,k:string)=>String(d.get(k)||"").trim(); const dt=(x:string)=>new Date(`${x}T12:00:00.000Z`); const msg=(e:unknown)=>e instanceof Error?e.message:"Não foi possível concluir a operação.";
const refresh=()=>{revalidatePath("/educacao/documentos");revalidatePath("/educacao/pre-matricula");revalidatePath("/educacao/portal-responsavel");};
function pdf(title:string,lines:string[]):Promise<Buffer>{return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:"A4",margin:42,info:{Title:title,Author:"CeleriFlow"}}),chunks:Buffer[]=[];doc.on("data",(c:Buffer)=>chunks.push(c));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);doc.font("Helvetica-Bold").fontSize(16).text(title).moveDown();doc.font("Helvetica").fontSize(10);for(const line of lines)doc.text(line).moveDown(.35);doc.end()})}

export async function generateAcademicDocumentAction(data:FormData):Promise<DocumentActionResult>{try{const {prisma,user}=await getTenantContextForModuleOperation("EDUCACAO","issueReports");const studentId=v(data,"studentId"),type=v(data,"type");const student=await prisma.student.findUnique({where:{id:studentId},include:{person:true,enrollments:{include:{school:true,schoolClass:true,period:true},orderBy:{year:"desc"}},grades:{where:{publishedAt:{not:null}},include:{schoolSubject:true},orderBy:{period:"asc"}},attendances:{include:{diary:true}}}});if(!student)throw new Error("Aluno não encontrado.");const enrollment=student.enrollments[0];const absences=student.attendances.filter(x=>!x.isPresent).length;const lines=[`Aluno: ${student.person.fullName}`,`CPF: ${student.person.cpf}`,`Código: ${student.studentCode}`,`Escola: ${enrollment?.school.name||"Não informada"}`,`Período: ${enrollment?.period?.name||enrollment?.year||"Não informado"}`,`Turma: ${enrollment?.schoolClass?.name||"Não informada"}`,`Situação: ${enrollment?.status||student.status}`,`Faltas registradas: ${absences}`,...student.grades.map(g=>`${g.period} · ${g.schoolSubject.name}: ${g.value??g.concept??"Sem resultado"}${g.recoveryValue!=null?` · Recuperação ${g.recoveryValue}`:""}`)];const title=type==="Boletim"?"Boletim escolar":type==="Histórico"?"Histórico escolar":"Declaração escolar";const buffer=await pdf(title,lines);const fileName=`${type.toLowerCase().replace(/\s/g,"-")}-${student.studentCode}.pdf`;await prisma.academicDocumentIssue.create({data:{type,fileName,studentId,filters:{year:enrollment?.year},generatedContent:lines.join("\n"),actorName:user.name}});refresh();return{error:null,message:"Documento gerado.",download:{fileName,base64:buffer.toString("base64")}}}catch(e){return{error:msg(e)}}}

export async function createPreEnrollmentProcessAction(data:FormData):Promise<S3ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","create");await prisma.preEnrollmentProcess.create({data:{name:v(data,"name"),schoolId:v(data,"schoolId"),year:Number(v(data,"year")),stage:v(data,"stage"),shift:v(data,"shift")||null,capacity:Number(v(data,"capacity")),startDate:dt(v(data,"startDate")),endDate:dt(v(data,"endDate")),status:"Aberto",criteria:{priority:v(data,"priority")||"Data da solicitação"}}});refresh();return{error:null,message:"Processo de pré-matrícula aberto."}}catch(e){return{error:msg(e)}}}

export async function submitPreEnrollmentAction(data:FormData):Promise<S3ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","create");const process=await prisma.preEnrollmentProcess.findUnique({where:{id:v(data,"processId")}});if(!process||process.status!=="Aberto"||new Date()>process.endDate)throw new Error("Processo indisponível para solicitação.");const studentId=v(data,"studentId");const duplicate=await prisma.preEnrollment.findFirst({where:{processId:process.id,studentId,status:{not:"Cancelada"}}});if(duplicate)throw new Error("Já existe solicitação do aluno neste processo.");const count=await prisma.preEnrollment.count({where:{processId:process.id}});const protocol=`PM-${process.year}-${String(count+1).padStart(5,"0")}`;await prisma.preEnrollment.create({data:{processId:process.id,studentId,schoolId:process.schoolId,year:process.year,stage:process.stage,grade:v(data,"grade"),shift:process.shift||v(data,"shift")||"A definir",protocol,rankingScore:Number(v(data,"rankingScore"))||0,history:[{date:new Date().toISOString(),status:"Pendente"}]}});refresh();return{error:null,message:`Solicitação registrada: ${protocol}.`}}catch(e){return{error:msg(e)}}}

export async function classifyPreEnrollmentsAction(data:FormData):Promise<S3ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","update");const processId=v(data,"processId");const items=await prisma.preEnrollment.findMany({where:{processId,status:{in:["Pendente","Classificado","Lista de espera"]}},orderBy:[{rankingScore:"desc"},{createdAt:"asc"}]});const process=await prisma.preEnrollmentProcess.findUnique({where:{id:processId}});if(!process)throw new Error("Processo não encontrado.");await prisma.$transaction(items.map((item,index)=>prisma.preEnrollment.update({where:{id:item.id},data:{position:index+1,status:index<process.capacity?"Classificado":"Lista de espera",history:[{date:new Date().toISOString(),status:index<process.capacity?"Classificado":"Lista de espera",position:index+1}]}})));refresh();return{error:null,message:`${items.length} candidato(s) classificados.`}}catch(e){return{error:msg(e)}}}

export async function allocatePreEnrollmentAction(data:FormData):Promise<S3ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","update");const item=await prisma.preEnrollment.findUnique({where:{id:v(data,"applicationId")},include:{process:true}});if(!item||item.status!=="Classificado")throw new Error("Somente candidato classificado pode ser alocado.");await prisma.preEnrollment.update({where:{id:item.id},data:{status:"Alocado",allocatedAt:new Date(),history:[{date:new Date().toISOString(),status:"Alocado"}]}});refresh();return{error:null,message:"Candidato alocado. A matrícula definitiva permanece pendente de confirmação."}}catch(e){return{error:msg(e)}}}

export async function submitLearningActivityAction(data:FormData):Promise<S3ActionResult>{try{const {prisma,user}=await getTenantContextForModuleOperation("EDUCACAO","create");const studentId=v(data,"studentId"),activityId=v(data,"activityId");if(!isSystemAdministrator(user)){const person=await prisma.person.findFirst({where:{email:user.email,guardianFor:{some:{studentId}}}});if(!person)throw new Error("Responsável sem autorização para este aluno.");}await prisma.learningSubmission.upsert({where:{activityId_studentId:{activityId,studentId}},create:{activityId,studentId,answer:v(data,"answer"),attachmentUrl:v(data,"attachmentUrl")||null},update:{answer:v(data,"answer"),attachmentUrl:v(data,"attachmentUrl")||null,status:"Entregue",submittedAt:new Date(),feedback:null,score:null,reviewedAt:null}});refresh();return{error:null,message:"Atividade enviada."}}catch(e){return{error:msg(e)}}}
