"use server";

import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";

export type S4ActionResult = { error: string | null; message?: string };
const value = (data: FormData, key: string) => String(data.get(key) || "").trim();
const date = (raw: string) => new Date(`${raw}T12:00:00.000Z`);
const error = (cause: unknown): S4ActionResult => ({ error: cause instanceof Error ? cause.message : "Não foi possível concluir a operação." });
const refresh = () => ["biblioteca", "merenda", "recursos-escolares", "transporte"].forEach((path) => revalidatePath(`/educacao/${path}`));

export async function createLibraryTitleAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationLibraryTitle.create({ data: { schoolId: value(data,"schoolId"), title: value(data,"title"), author: value(data,"author"), isbn: value(data,"isbn") || null, category: value(data,"category") } }); refresh(); return { error:null, message:"Título incluído no acervo." }; } catch (cause) { return error(cause); } }
export async function createLibraryCopyAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationLibraryCopy.create({ data: { titleId:value(data,"titleId"), assetCode:value(data,"assetCode") } }); refresh(); return { error:null, message:"Exemplar registrado." }; } catch (cause) { return error(cause); } }
export async function createLoanAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); const copyId=value(data,"copyId"); await prisma.$transaction([prisma.educationLibraryLoan.create({data:{copyId,studentId:value(data,"studentId"),dueAt:date(value(data,"dueAt"))}}),prisma.educationLibraryCopy.update({where:{id:copyId},data:{status:"Emprestado"}})]); refresh(); return { error:null, message:"Empréstimo registrado." }; } catch (cause) { return error(cause); } }
export async function updateLoanAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "update"); const loan=await prisma.educationLibraryLoan.findUnique({where:{id:value(data,"loanId")}}); if(!loan) throw new Error("Empréstimo não encontrado."); const operation=value(data,"operation"); if(operation==="Renovar") await prisma.educationLibraryLoan.update({where:{id:loan.id},data:{dueAt:date(value(data,"dueAt")),renewals:{increment:1}}}); else await prisma.$transaction([prisma.educationLibraryLoan.update({where:{id:loan.id},data:{status:"Devolvido",returnedAt:new Date()}}),prisma.educationLibraryCopy.update({where:{id:loan.copyId},data:{status:"Disponível"}})]); refresh(); return { error:null, message:`Empréstimo ${operation.toLowerCase()}.` }; } catch (cause) { return error(cause); } }
export async function reserveTitleAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); const titleId=value(data,"titleId"); const position=(await prisma.educationLibraryReservation.count({where:{titleId,status:"Aguardando"}}))+1; await prisma.educationLibraryReservation.upsert({where:{titleId_studentId:{titleId,studentId:value(data,"studentId")}},create:{titleId,studentId:value(data,"studentId"),position},update:{status:"Aguardando",position}}); refresh(); return { error:null, message:"Reserva registrada." }; } catch (cause) { return error(cause); } }

export async function createSchoolMenuAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationSchoolMenu.create({data:{schoolId:value(data,"schoolId"),name:value(data,"name"),weekStart:date(value(data,"weekStart")),shift:value(data,"shift"),servingsPlanned:Number(value(data,"servingsPlanned")),items:{description:value(data,"items")}}}); refresh(); return {error:null,message:"Cardápio planejado."}; } catch(cause){return error(cause);} }
export async function createFoodMovementAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationFoodMovement.create({data:{schoolId:value(data,"schoolId"),materialId:value(data,"materialId"),warehouseId:value(data,"warehouseId")||null,type:value(data,"type"),quantity:Number(value(data,"quantity")),unitCost:value(data,"unitCost")||null,notes:value(data,"notes")||null}}); refresh(); return {error:null,message:"Movimentação de alimentação registrada."}; } catch(cause){return error(cause);} }

export async function createEducationAccountAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationFinancialAccount.create({data:{schoolId:value(data,"schoolId"),name:value(data,"name"),bankAccountId:value(data,"bankAccountId")||null}}); refresh(); return {error:null,message:"Conta escolar vinculada."}; } catch(cause){return error(cause);} }
export async function createEducationMovementAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationFinancialMovement.create({data:{accountId:value(data,"accountId"),type:value(data,"type"),value:value(data,"amount"),description:value(data,"description")}}); refresh(); return {error:null,message:"Movimento financeiro registrado."}; } catch(cause){return error(cause);} }
export async function createApplicationPlanAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationApplicationPlan.create({data:{schoolId:value(data,"schoolId"),accountId:value(data,"accountId")||null,title:value(data,"title"),total:value(data,"total"),items:{description:value(data,"items")},status:value(data,"status")||"Rascunho",submittedAt:value(data,"status")==="Enviado"?new Date():null}}); refresh(); return {error:null,message:"Plano de aplicação registrado."}; } catch(cause){return error(cause);} }

export async function createTransportRouteAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationTransportRoute.create({data:{schoolId:value(data,"schoolId"),code:value(data,"code"),name:value(data,"name"),fleetRouteId:value(data,"fleetRouteId")||null,fleetUnitId:value(data,"fleetUnitId")||null}}); refresh(); return {error:null,message:"Rota escolar registrada."}; } catch(cause){return error(cause);} }
export async function addTransportStopAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationTransportStop.create({data:{routeId:value(data,"routeId"),name:value(data,"name"),address:value(data,"address"),sequence:Number(value(data,"sequence")),latitude:value(data,"latitude")?Number(value(data,"latitude")):null,longitude:value(data,"longitude")?Number(value(data,"longitude")):null}}); refresh(); return {error:null,message:"Ponto incluído."}; } catch(cause){return error(cause);} }
export async function addTransportStudentAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationTransportStudent.upsert({where:{routeId_studentId:{routeId:value(data,"routeId"),studentId:value(data,"studentId")}},create:{routeId:value(data,"routeId"),studentId:value(data,"studentId"),boardingStop:value(data,"boardingStop")||null},update:{status:"Ativo",boardingStop:value(data,"boardingStop")||null}}); refresh(); return {error:null,message:"Aluno vinculado à rota."}; } catch(cause){return error(cause);} }
export async function createJourneyAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "create"); await prisma.educationTransportJourney.create({data:{routeId:value(data,"routeId"),fleetUnitId:value(data,"fleetUnitId")||null,notes:value(data,"notes")||null}}); refresh(); return {error:null,message:"Viagem iniciada."}; } catch(cause){return error(cause);} }
export async function updateJourneyAction(data: FormData): Promise<S4ActionResult> { try { const { prisma } = await getTenantContextForModuleOperation("EDUCACAO", "update"); const journeyId=value(data,"journeyId"),operation=value(data,"operation"); if(operation==="Finalizar") await prisma.educationTransportJourney.update({where:{id:journeyId},data:{status:"Concluída",endedAt:new Date()}}); else await prisma.educationTransportEvent.create({data:{journeyId,type:value(data,"type"),latitude:value(data,"latitude")?Number(value(data,"latitude")):null,longitude:value(data,"longitude")?Number(value(data,"longitude")):null,notes:value(data,"notes")||null}}); refresh(); return {error:null,message:operation==="Finalizar"?"Viagem finalizada.":"Evento registrado no histórico."}; } catch(cause){return error(cause);} }
