"use server";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";
export type S5ActionResult={error:string|null;message?:string};
const v=(d:FormData,k:string)=>String(d.get(k)||"").trim();const fail=(e:unknown):S5ActionResult=>({error:e instanceof Error?e.message:"Não foi possível concluir a operação."});const refresh=()=>{revalidatePath("/educacao/portal-interativo");revalidatePath("/educacao/suporte")};
export async function createCatalogItemAction(data:FormData):Promise<S5ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","create");const questions=v(data,"questions").split("\n").map((line,index)=>{const [statement,answer,...options]=line.split("|").map(x=>x.trim());return{id:index+1,statement,answer,options:options.length?options:[answer]}}).filter(x=>x.statement&&x.answer);if(!questions.length)throw new Error("Informe ao menos uma questão no formato solicitado.");await prisma.pedagogicalCatalogItem.create({data:{title:v(data,"title"),description:v(data,"description"),schoolYear:v(data,"schoolYear"),type:v(data,"type"),instructions:v(data,"instructions"),durationSeconds:Number(v(data,"durationSeconds"))||null,subjectId:v(data,"subjectId")||null,content:{questions}}});refresh();return{error:null,message:"Atividade incluída no catálogo."}}catch(e){return fail(e)}}
export async function releaseCatalogItemAction(data:FormData):Promise<S5ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","create");const classId=v(data,"classId")||null,studentId=v(data,"studentId")||null;if(!classId&&!studentId)throw new Error("Selecione uma turma ou um aluno.");await prisma.pedagogicalRelease.create({data:{catalogItemId:v(data,"catalogItemId"),teacherId:v(data,"teacherId"),classId,studentId}});refresh();return{error:null,message:"Atividade liberada."}}catch(e){return fail(e)}}
export async function completePedagogicalAttemptAction(data:FormData):Promise<S5ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","create");const studentId=v(data,"studentId");const release=await prisma.pedagogicalRelease.findUnique({where:{id:v(data,"releaseId")},include:{catalogItem:true}});if(!release)throw new Error("Liberação não encontrada.");if(release.studentId&&release.studentId!==studentId)throw new Error("Atividade não liberada para este aluno.");if(!release.studentId&&release.classId&&!await prisma.enrollment.findFirst({where:{studentId,classId:release.classId,status:"Matriculado"}}))throw new Error("Aluno não pertence à turma autorizada.");const content=release.catalogItem.content as {questions?:Array<{id:number;answer:string}>};const answers=JSON.parse(v(data,"answers")||"{}") as Record<string,string>;const questions=content.questions||[];const correct=questions.filter(q=>String(answers[q.id]||"").localeCompare(q.answer,"pt-BR",{sensitivity:"base"})===0).length;const score=questions.length?Math.round(correct/questions.length*100):0;await prisma.pedagogicalAttempt.create({data:{releaseId:release.id,studentId,answers,completedAt:new Date(),score,correctAnswers:correct,incorrectAnswers:questions.length-correct}});refresh();return{error:null,message:`Atividade concluída: ${score} pontos.`}}catch(e){return fail(e)}}
export async function createSupportRequestAction(data:FormData):Promise<S5ActionResult>{try{const {prisma,user}=await getTenantContextForModuleOperation("EDUCACAO","create");const count=await prisma.educationSupportRequest.count();const protocol=`EDU-${new Date().getFullYear()}-${String(count+1).padStart(5,"0")}`;await prisma.educationSupportRequest.create({data:{protocol,requesterName:user.name,requesterEmail:user.email,subject:v(data,"subject"),description:v(data,"description")}});refresh();return{error:null,message:`Solicitação registrada: ${protocol}.`}}catch(e){return fail(e)}}
export async function updateSupportRequestAction(data:FormData):Promise<S5ActionResult>{try{const {prisma}=await getTenantContextForModuleOperation("EDUCACAO","update");await prisma.educationSupportRequest.update({where:{id:v(data,"requestId")},data:{status:v(data,"status"),response:v(data,"response")||null}});refresh();return{error:null,message:"Solicitação atualizada."}}catch(e){return fail(e)}}

