"use server";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";
import { applyInstallmentPayment, changeInstallmentStatus, completeCollectionAction, createBenefitRule, createCollectionPortfolio, createInstallmentAgreement, createPrizeDraw, executePrizeDraw, grantBenefit, grantPortalAccess, issuePrizeCoupon, reparcelInstallment, reviseInstallmentOrigin, scheduleCollectionAction } from "@/lib/tributacao/s8-service";
const path="/tributacao/cobranca"; const done=(error?:unknown)=>({error:error instanceof Error?error.message:error?"Não foi possível concluir a operação.":undefined});
async function ctx(operation:"create"|"update"){return getTenantContextForModuleOperation("TRIBUTACAO",operation)} const actor=(c:Awaited<ReturnType<typeof ctx>>)=>({usuarioId:c.user.id});
export async function createPortfolioAction(input:Parameters<typeof createCollectionPortfolio>[2]){try{const c=await ctx("create");await createCollectionPortfolio(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function scheduleCollectionActionAction(input:Parameters<typeof scheduleCollectionAction>[2]){try{const c=await ctx("create");await scheduleCollectionAction(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function completeCollectionActionAction(input:Parameters<typeof completeCollectionAction>[2]){try{const c=await ctx("update");await completeCollectionAction(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function createMandatoryInstallmentAction(taxpayerId:string){try{const c=await ctx("create");const rule=await c.prisma.taxInstallmentRule.findFirstOrThrow({where:{active:true},orderBy:{effectiveFrom:"desc"}});const agreement=await createInstallmentAgreement(c.prisma,actor(c),{taxpayerId,ruleId:rule.id,total:1000,count:3,dueDay:10,sourceType:"DEMO_FISCAL",originLabel:"Cenário obrigatório TRIB-S8"});revalidatePath(path);return{...done(),agreementId:agreement.id}}catch(e){return{...done(e),agreementId:undefined}}}
export async function payMandatoryInstallmentAction(agreementId:string){try{const c=await ctx("update");await applyInstallmentPayment(c.prisma,actor(c),{agreementId,paymentKey:`S8-DEMO-400-${agreementId}`,amount:400});revalidatePath(path);return done()}catch(e){return done(e)}}
export async function anticipateInstallmentAction(agreementId:string,amount:number){try{const c=await ctx("update");await applyInstallmentPayment(c.prisma,actor(c),{agreementId,paymentKey:`ANTECIPACAO-${agreementId}-${Date.now()}`,amount,paymentMode:"ANTECIPACAO"});revalidatePath(path);return done()}catch(e){return done(e)}}
export async function reviseInstallmentOriginAction(agreementId:string,debtId:string,revisedAmount:number){try{const c=await ctx("update");await reviseInstallmentOrigin(c.prisma,actor(c),{agreementId,debtId,revisedAmount,reason:"Revisão demonstrativa da origem com ajuste na última cota aberta."});revalidatePath(path);return done()}catch(e){return done(e)}}
export async function reparcelInstallmentAction(agreementId:string){try{const c=await ctx("create");await reparcelInstallment(c.prisma,actor(c),{agreementId,count:3,dueDay:10});revalidatePath(path);return done()}catch(e){return done(e)}}
export async function changeInstallmentStatusAction(input:Parameters<typeof changeInstallmentStatus>[2]){try{const c=await ctx("update");await changeInstallmentStatus(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function grantPortalAccessAction(taxpayerId:string){try{const c=await ctx("update");await grantPortalAccess(c.prisma,actor(c),taxpayerId);revalidatePath(path);revalidatePath("/portal/tributario");return done()}catch(e){return done(e)}}
export async function createBenefitRuleAction(input:Parameters<typeof createBenefitRule>[2]){try{const c=await ctx("create");await createBenefitRule(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function grantBenefitAction(input:Parameters<typeof grantBenefit>[2]){try{const c=await ctx("create");await grantBenefit(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function createPrizeDrawAction(input:Parameters<typeof createPrizeDraw>[2]){try{const c=await ctx("create");await createPrizeDraw(c.prisma,actor(c),input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function issuePrizeCouponAction(input:Parameters<typeof issuePrizeCoupon>[1]){try{const c=await ctx("create");await issuePrizeCoupon(c.prisma,input);revalidatePath(path);return done()}catch(e){return done(e)}}
export async function executePrizeDrawAction(drawId:string){try{const c=await ctx("create");await executePrizeDraw(c.prisma,actor(c),drawId);revalidatePath(path);return done()}catch(e){return done(e)}}
