import { getTenantContextForModule } from "@/lib/platform/tenant-context";
export const dynamic = "force-dynamic";
const esc = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { prisma } = await getTenantContextForModule("TRIBUTACAO");
  const item = await prisma.itbiDeclaration.findUnique({ where: { id }, include: { transactionType: true, parties: true, events: { orderBy: { createdAt: "asc" } } } });
  if (!item?.documentId) return new Response("Documento de ITBI não encontrado.", { status: 404 });
  const taxpayers = await prisma.taxpayer.findMany({ where: { id: { in: item.parties.map((party) => party.taxpayerId) } }, include: { person: true, company: true } });
  const names = new Map(taxpayers.map((taxpayer) => [taxpayer.id, taxpayer.company?.corporateName ?? taxpayer.person?.fullName ?? taxpayer.id]));
  const rows = item.parties.map((party) => `<tr><td>${esc(party.role)}</td><td>${esc(names.get(party.taxpayerId))}</td><td>${esc(party.participationPercent ? `${party.participationPercent}%` : "—")}</td></tr>`).join("");
  const history = item.events.map((event) => `<li>${esc(event.createdAt.toLocaleString("pt-BR"))} — <b>${esc(event.eventType)}</b>: ${esc(event.description)}</li>`).join("");
  const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(item.declarationNumber)}</title><style>body{font-family:Arial;color:#172033;margin:24px}.sheet{max-width:850px;margin:auto;border:1px solid #cbd5e1;padding:24px}h1{font-size:21px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{border-bottom:1px solid #e2e8f0;padding:7px}.field b{display:block;font-size:10px;color:#64748b;text-transform:uppercase}table{width:100%;border-collapse:collapse;margin-top:18px}td,th{border:1px solid #cbd5e1;padding:7px;text-align:left}.warning{margin-top:18px;padding:10px;background:#fffbeb;border:1px solid #fde68a;font-size:12px}.actions{text-align:right;max-width:850px;margin:auto auto 12px}@media print{.actions{display:none}.sheet{border:0}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir</button></div><main class="sheet"><h1>Documento Municipal de Transmissão — ITBI</h1><p>${esc(item.declarationNumber)} · protocolo ${esc(item.protocolNumber)}</p><div class="grid"><div class="field"><b>Tipo</b>${esc(item.transactionType.name)}</div><div class="field"><b>Cartório informado</b>${esc(item.registryOffice)}</div><div class="field"><b>Fração transmitida</b>${esc(item.transmittedFraction)}%</div><div class="field"><b>Valor declarado</b>R$ ${esc(item.declaredPropertyValue)}</div><div class="field"><b>Base transmitida</b>R$ ${esc(item.taxableBase)}</div><div class="field"><b>Alíquota / ITBI</b>${esc(item.appliedRate)}% · R$ ${esc(item.taxAmount)}</div></div><table><thead><tr><th>Papel</th><th>Parte</th><th>Participação</th></tr></thead><tbody>${rows}</tbody></table><h2>Histórico</h2><ul>${history}</ul><div class="warning">Documento municipal interno. A emissão do ITBI não altera, por si só, o registro civil da propriedade. Assinaturas oficiais dependem da política e do provedor configurados no GED.</div></main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="${item.declarationNumber}.html"` } });
}
