"use server";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";
import { createEstimate, importIndices, importMovements, importRepasse, linkCompanyAccountant, markNotificationRead, notifyCorrection, processCompetency, resolveCrossCheck, seedMandatoryScenario, upsertAccountant, upsertCompany, upsertRule } from "@/lib/tributacao/s10-service";
const path = "/tributacao/vaf";
const done = (error?: unknown) => ({ error: error instanceof Error ? error.message : error ? "Não foi possível concluir a operação." : undefined });
async function ctx(op: "create" | "update") { return getTenantContextForModuleOperation("TRIBUTACAO", op); }
const actor = (c: Awaited<ReturnType<typeof ctx>>) => ({ usuarioId: c.user.id });
export async function seedScenarioAction() { try { const c = await ctx("create"); const r = await seedMandatoryScenario(c.prisma, actor(c)); revalidatePath(path); return { ...done(), summary: `VAF total ${r.total} em ${r.companies} empresas (${r.omitted} omissas).` }; } catch (e) { return { ...done(e), summary: undefined as unknown as string }; } }
export async function upsertAccountantAction(input: Parameters<typeof upsertAccountant>[1]) { try { const c = await ctx("create"); await upsertAccountant(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function upsertCompanyAction(input: Parameters<typeof upsertCompany>[1]) { try { const c = await ctx("create"); await upsertCompany(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function linkAccountantAction(companyId: string, accountantId: string | null) { try { const c = await ctx("update"); await linkCompanyAccountant(c.prisma, companyId, accountantId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function upsertRuleAction(input: { exerciseId: string; cfop: string; cfopDescription?: string; composesVaf?: boolean; formula: string; contrapartidaCfop?: string; effectiveFrom: string }) { try { const c = await ctx("create"); await upsertRule(c.prisma, { ...input, effectiveFrom: new Date(input.effectiveFrom) }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function importMovementsAction(kind: "EFD" | "GIA", input: { companyId: string; exerciseId: string; competency: string; fileName: string; movements: { cfop: string; operationType: "ENTRADA" | "SAIDA"; value: number }[] }) { try { const c = await ctx("create"); await importMovements(c.prisma, actor(c), kind, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function processCompetencyAction(input: { exerciseId: string; competency: string }) { try { const c = await ctx("update"); const r = await processCompetency(c.prisma, actor(c), input); revalidatePath(path); return { ...done(), summary: `Apurado VAF ${r.total} (${r.companies} empresas).` }; } catch (e) { return { ...done(e), summary: undefined as unknown as string }; } }
export async function importRepasseAction(input: { exerciseId: string; competency: string; weekNumber?: number; municipalValue: number; stateTotalValue: number }) { try { const c = await ctx("create"); await importRepasse(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function importIndicesAction(input: Parameters<typeof importIndices>[1]) { try { const c = await ctx("create"); await importIndices(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function notifyCorrectionAction(input: Parameters<typeof notifyCorrection>[1]) { try { const c = await ctx("create"); await notifyCorrection(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function markNotificationReadAction(id: string) { try { const c = await ctx("update"); await markNotificationRead(c.prisma, id); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function resolveCrossCheckAction(id: string, status: "CORRIGIDA" | "IGNORADA") { try { const c = await ctx("update"); await resolveCrossCheck(c.prisma, actor(c), id, status); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createEstimateAction(input: { exerciseId: string; competency: string; method: "LINEAR" | "MEDIA_MOVEL"; realizedMonths: number; realizedValue: number }) { try { const c = await ctx("create"); await createEstimate(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
