import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import { assertDesifReceipt } from "@/lib/tributacao/s6-service";
const esc = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { prisma } = await getTenantContextForModule("TRIBUTACAO"); const batch = await prisma.desifImportBatch.findUnique({ where: { id }, include: { institution: true, agency: true, _count: { select: { assessments: true, trialBalances: true, packageMovements: true } } } });
  if (!batch) return new Response("Importação não encontrada.", { status: 404 }); try { assertDesifReceipt(batch); } catch (error) { return new Response(error instanceof Error ? error.message : "Recibo indisponível.", { status: 409 }); }
  const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Recibo ${esc(batch.receiptNumber)}</title><style>body{font-family:Arial;color:#172033;margin:30px}.sheet{max-width:800px;margin:auto;border:1px solid #cbd5e1;padding:28px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.f{border-bottom:1px solid #e2e8f0;padding:8px}.f b{display:block;font-size:10px;color:#64748b;text-transform:uppercase}.ok{margin-top:22px;background:#ecfdf5;border:1px solid #6ee7b7;padding:12px}.warn{font-size:11px;color:#64748b}.actions{text-align:right;max-width:800px;margin:auto auto 10px}@media print{.actions{display:none}.sheet{border:0}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir</button></div><main class="sheet"><h1>Recibo de processamento DES-IF</h1><p><b>${esc(batch.receiptNumber)}</b></p><div class="grid"><div class="f"><b>Instituição</b>${esc(batch.institution.name)}</div><div class="f"><b>Agência</b>${esc(batch.agency?.name ?? "Todas")}</div><div class="f"><b>Competência</b>${esc(batch.competence)}</div><div class="f"><b>Leiaute</b>${esc(batch.abrasfVersion)}</div><div class="f"><b>Arquivo</b>${esc(batch.fileName)}</div><div class="f"><b>Processado em</b>${esc(batch.processedAt?.toLocaleString("pt-BR"))}</div></div><div class="ok">Validado e processado pelo CeleriFlow. Apurações: ${batch._count.assessments}; balancetes: ${batch._count.trialBalances}; pacotes: ${batch._count.packageMovements}.</div><p class="warn">Origem ${esc(batch.originMode)}. Assinatura: ${esc(batch.signaturePolicy)} / ${esc(batch.signatureStatus)}. Este recibo não declara certificação ICP-Brasil.</p></main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="recibo-desif-${batch.id}.html"` } });
}
