import { FlaskConical } from "lucide-react";
import type { Prisma } from "@prisma/client";
import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { HealthSimpleListClient } from "../HealthSimpleListClient";
import { collectSampleAction, createReportAction, enterResultAction, recollectAction, releaseReportAction, reviewReportAction, saveAssistentialDeviceAction, saveExamModelAction, saveExamScheduleAction, saveProviderQuotaAction, scheduleOrderAction } from "./actions";

const field = "h-8 min-w-0 rounded border border-slate-200 bg-white px-2 text-xs";
const PAGE_SIZE = 20;
type Params = { q?: string | string[]; filter?: string | string[]; page?: string | string[] };
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const positivePage = (value: string | undefined) => value && /^\d+$/.test(value) && Number(value) > 0 ? Number(value) : 1;

export default async function LaboratoryPage({ searchParams }: { searchParams: Promise<Params> }) {
  const context = await getTenantContextForModule("SAUDE");
  const { prisma } = context;
  const unitIds = context.user.hasHealthAccessScope ? context.user.allowedHealthUnitIds || [] : undefined;
  const orderScope: Prisma.HealthLabOrderWhereInput = unitIds ? { OR: [{ collectionUnitId: { in: unitIds } }, { collectionUnitId: null, requestUnitId: { in: unitIds } }] } : {};
  const params = await searchParams;
  const q = (first(params.q) || "").trim().slice(0, 120);
  const filter = (first(params.filter) || "").trim().slice(0, 40);
  const orderFilters: Prisma.HealthLabOrderWhereInput[] = [orderScope];
  if (filter) orderFilters.push({ status: filter });
  if (q) orderFilters.push({ OR: [{ patient: { person: { fullName: { contains: q, mode: "insensitive" } } } }, { examRequest: { examName: { contains: q, mode: "insensitive" } } }, { examModel: { name: { contains: q, mode: "insensitive" } } }, { requestUnit: { name: { contains: q, mode: "insensitive" } } }, { collectionUnit: { name: { contains: q, mode: "insensitive" } } }] });
  const orderWhere: Prisma.HealthLabOrderWhereInput = { AND: orderFilters };
  const total = await prisma.healthLabOrder.count({ where: orderWhere });
  const page = Math.min(positivePage(first(params.page)), Math.max(1, Math.ceil(total / PAGE_SIZE)));
  const [orders, orderOptions, units, providers, reports, examModels, materials, procedures] = await Promise.all([
    prisma.healthLabOrder.findMany({ where: orderWhere, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, orderBy: { createdAt: "desc" }, include: { patient: { include: { person: true } }, examRequest: true, examModel: true, requestUnit: true, collectionUnit: true, results: { select: { status: true } } } }),
    prisma.healthLabOrder.findMany({ where: orderScope, take: 500, orderBy: { createdAt: "desc" }, include: { patient: { include: { person: true } }, examRequest: true, examModel: true, results: { select: { status: true } } } }),
    prisma.healthUnit.findMany({ where: { isActive: true, ...(unitIds ? { id: { in: unitIds } } : {}) }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.supplier.findMany({ where: { status: "Ativo" }, take: 200, select: { id: true, person: { select: { fullName: true } }, company: { select: { corporateName: true } } } }),
    prisma.healthLabReport.findMany({ where: unitIds ? { order: orderScope } : {}, orderBy: { createdAt: "desc" }, include: { order: { include: { patient: { include: { person: true } }, examRequest: true } }, document: true } }),
    prisma.healthLabExamModel.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.material.findMany({ where: { isActive: true }, orderBy: { name: "asc" }, take: 500 }),
    prisma.healthSusProcedure.findMany({ where: { isActive: true, isCurrent: true }, orderBy: { description: "asc" }, take: 500 }),
  ]);
  const requested = orderOptions.filter(x => ["REQUESTED", "RECOLLECT"].includes(x.status));
  const scheduled = orderOptions.filter(x => ["SCHEDULED", "RECOLLECT"].includes(x.status));
  const collected = orderOptions.filter(x => ["COLLECTED", "RECEIVED", "ENTERED"].includes(x.status));
  const finalOrders = orderOptions.filter(x => x.status === "ENTERED" && x.results.some(result => result.status === "FINAL"));
  return <PageFrame className="flex h-[calc(100dvh-7.5rem)] min-h-0 flex-col gap-2 overflow-hidden px-1 py-1 md:px-2">
    <PageHeader title="Laboratório Municipal" icon={<FlaskConical className="size-4 text-cyan-700"/>}/>
    <div className="grid shrink-0 gap-2 lg:grid-cols-4">
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cadastrar exame</summary><form action={saveExamModelAction} className="mt-2 grid gap-1"><input name="code" required placeholder="Código" className={field}/><input name="name" required placeholder="Nome" className={field}/><select name="procedureId" className={field}><option value="">Procedimento SUS</option>{procedures.map(x => <option key={x.id} value={x.id}>{x.code} · {x.description}</option>)}</select><input name="bench" placeholder="Bancada" className={field}/><input name="preparation" placeholder="Preparo informado" className={field}/><select name="materialId" className={field}><option value="">Sem material vinculado</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="materialQuantity" type="number" min="0.001" step="0.001" defaultValue="1" className={field}/><input name="deliveryDays" type="number" min="0" defaultValue="0" className={field}/><input name="duplicateWindowDays" type="number" min="0" defaultValue="0" className={field}/><label><input name="performedInternally" type="checkbox" defaultChecked/> Execução municipal</label><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Salvar exame</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cronograma e vagas</summary><form action={saveExamScheduleAction} className="mt-2 grid gap-1"><select name="examModelId" required className={field}><option value="">Exame</option>{examModels.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="date" type="date" className={field}/><select name="weekday" className={field}><option value="">Ou dia da semana</option>{["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"].map((x, i) => <option key={x} value={i}>{x}</option>)}</select><input name="capacity" type="number" min="1" required placeholder="Vagas" className={field}/><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Salvar cronograma</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cota de prestador</summary><form action={saveProviderQuotaAction} className="mt-2 grid gap-1"><select name="providerSupplierId" required className={field}><option value="">Prestador</option>{providers.map(x => <option key={x.id} value={x.id}>{x.company?.corporateName || x.person?.fullName}</option>)}</select><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="examModelId" required className={field}><option value="">Exame</option>{examModels.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="period" type="month" required className={field}/><input name="allowedQuantity" type="number" min="1" required placeholder="Cota" className={field}/><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Definir cota</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Equipamento</summary><form action={saveAssistentialDeviceAction} className="mt-2 grid gap-1"><input name="code" required placeholder="Código" className={field}/><input name="name" required placeholder="Nome" className={field}/><select name="deviceType" required className={field}><option value="ANALYZER">Analisador</option><option value="PRINTER">Impressora</option></select><select name="protocol" required className={field}><option>A15</option><option>HL7</option><option>ZPL</option></select><select name="unitId" className={field}><option value="">Sem unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Salvar equipamento</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Agendar coleta</summary><form action={scheduleOrderAction} className="mt-2 grid gap-1"><select name="orderId" required className={field}><option value="">Solicitação</option>{requested.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.examRequest?.examName || x.examModel?.name}</option>)}</select><select name="collectionUnitId" required className={field}><option value="">Unidade de coleta</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="providerSupplierId" className={field}><option value="">Execução municipal</option>{providers.map(x => <option key={x.id} value={x.id}>{x.company?.corporateName || x.person?.fullName}</option>)}</select><input name="scheduledAt" type="datetime-local" required className={field}/><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Agendar</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Registrar coleta</summary><form action={collectSampleAction} className="mt-2 grid gap-1"><select name="orderId" required className={field}><option value="">Exame agendado</option>{scheduled.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.examRequest?.examName || x.examModel?.name}</option>)}</select><input name="sampleBarcode" required placeholder="Código da amostra" className={field}/><label className="flex items-center gap-2"><input name="collectionByThirdParty" type="checkbox"/>Coleta por terceiro</label><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Confirmar coleta</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Digitar resultado</summary><form action={enterResultAction} className="mt-2 grid gap-1"><select name="orderId" required className={field}><option value="">Amostra</option>{collected.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.examRequest?.examName || x.examModel?.name}</option>)}</select><input name="value" required placeholder="Resultado" className={field}/><input name="unitOfMeasure" placeholder="Unidade de medida" className={field}/><textarea name="interpretation" placeholder="Interpretação técnica" className="min-h-16 rounded border p-2"/><select name="status" className={field}><option value="PARTIAL">Parcial</option><option value="FINAL">Final</option></select><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Registrar versão</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Emitir laudo</summary><form action={createReportAction} className="mt-2 grid gap-1"><select name="orderId" required className={field}><option value="">Resultado final</option>{finalOrders.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.examRequest?.examName || x.examModel?.name}</option>)}</select><input name="title" required placeholder="Título do laudo" className={field}/><input name="file" type="file" required className={field}/><button className="h-8 rounded bg-cyan-700 font-semibold text-white">Registrar no GED</button></form></details>
    </div>
    <div className="grid min-h-0 flex-1 gap-2 lg:grid-cols-[2fr_1fr]">
      <HealthSimpleListClient rows={orders.map(x => ({ id: x.id, cells: { patient: x.patient.person.fullName, exam: x.examRequest?.examName || x.examModel?.name || "Exame", requestUnit: x.requestUnit?.name || "-", collectionUnit: x.collectionUnit?.name || "-", schedule: x.scheduledAt?.toLocaleString("pt-BR") || "-", status: x.status, priority: x.priority } }))} columns={[{ key: "patient", label: "Paciente" }, { key: "exam", label: "Exame" }, { key: "collectionUnit", label: "Coleta", responsive: "sm" }, { key: "schedule", label: "Agenda", responsive: "md", width: "medium" }, { key: "priority", label: "Prioridade", responsive: "lg", width: "medium" }, { key: "status", label: "Etapa", width: "medium" }]} label="solicitações" searchPlaceholder="Buscar paciente, exame ou unidade" filterKey="status" filterLabel="Todas as etapas" serverPagination={{ page, total, pathname: "/app-domain/saude/laboratorio", search: q, filter, filterOptions: ["REQUESTED", "SCHEDULED", "COLLECTED", "RECEIVED", "ENTERED", "RECOLLECT", "CANCELLED"] }} />
      <div className="min-h-0 overflow-y-auto rounded border bg-white p-2"><h2 className="sticky top-0 bg-white pb-2 text-xs font-bold uppercase text-slate-500">Laudos</h2>{reports.map(report => <article key={report.id} className="mb-2 rounded border p-2 text-xs"><strong>{report.order.patient.person.fullName}</strong><p className="truncate text-slate-500">{report.document.title} · {report.status}</p><div className="mt-2 flex gap-1">{report.status === "DRAFT" && <form action={reviewReportAction}><input type="hidden" name="reportId" value={report.id}/><button className="rounded border px-2 py-1">Revisar</button></form>}{report.status === "REVIEWED" && <form action={releaseReportAction} className="flex items-center gap-1"><input type="hidden" name="reportId" value={report.id}/><label><input type="checkbox" name="publishToPatient"/> Publicar</label><button className="rounded border px-2 py-1">Liberar</button></form>}{["COLLECTED", "RECEIVED", "ENTERED"].includes(report.order.status) && <form action={recollectAction}><input type="hidden" name="orderId" value={report.order.id}/><input name="reason" required placeholder="Motivo da recoleta" className="h-7 w-28 rounded border px-1"/><button className="rounded border px-2 py-1">Recoleta</button></form>}</div></article>)}</div>
    </div>
  </PageFrame>;
}
