import { Accessibility } from "lucide-react";
import type { Prisma } from "@prisma/client";
import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { HealthSimpleListClient } from "../HealthSimpleListClient";
import { addEntryAction, createPlanAction, distributeAction, saveCatalogAction, saveQuotaAction, saveScheduleAction } from "./actions";

const field = "h-8 min-w-0 rounded border border-slate-200 bg-white px-2 text-xs";
const PAGE_SIZE = 20;
type Params = { q?: string | string[]; filter?: string | string[]; page?: string | string[] };
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const positivePage = (value: string | undefined) => value && /^\d+$/.test(value) && Number(value) > 0 ? Number(value) : 1;

export default async function SpecializedCenterPage({ searchParams }: { searchParams: Promise<Params> }) {
  const context = await getTenantContextForModule("SAUDE");
  const { prisma } = context;
  const unitIds = context.user.hasHealthAccessScope ? context.user.allowedHealthUnitIds || [] : undefined;
  const params = await searchParams;
  const q = (first(params.q) || "").trim().slice(0, 120);
  const filter = (first(params.filter) || "").trim().slice(0, 40);
  const planScope: Prisma.SpecializedTherapeuticPlanWhereInput = unitIds ? { unitId: { in: unitIds } } : {};
  const planWhere: Prisma.SpecializedTherapeuticPlanWhereInput = { ...planScope, ...(filter ? { status: filter } : {}), ...(q ? { OR: [{ patient: { person: { fullName: { contains: q, mode: "insensitive" } } } }, { unit: { name: { contains: q, mode: "insensitive" } } }, { team: { name: { contains: q, mode: "insensitive" } } }] } : {}) };
  const total = await prisma.specializedTherapeuticPlan.count({ where: planWhere });
  const page = Math.min(positivePage(first(params.page)), Math.max(1, Math.ceil(total / PAGE_SIZE)));
  const [plans, planOptions, patients, units, teams, specialties, services, materials, stocks, quotas, records] = await Promise.all([
    prisma.specializedTherapeuticPlan.findMany({ where: planWhere, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, orderBy: { startedAt: "desc" }, include: { patient: { include: { person: true } }, unit: true, team: true, entries: { orderBy: { createdAt: "desc" }, take: 1, include: { professional: { include: { employee: { include: { person: true } } } } } } } }),
    prisma.specializedTherapeuticPlan.findMany({ where: planScope, take: 500, orderBy: { startedAt: "desc" }, include: { patient: { include: { person: true } } } }),
    prisma.patient.findMany({ where: { status: "Ativo", ...(unitIds ? { referenceUnitId: { in: unitIds } } : {}) }, take: 500, orderBy: { person: { fullName: "asc" } }, include: { person: true } }),
    prisma.healthUnit.findMany({ where: { isActive: true, ...(unitIds ? { id: { in: unitIds } } : {}) }, orderBy: { name: "asc" } }),
    prisma.healthTeam.findMany({ where: { isActive: true, ...(unitIds ? { unitId: { in: unitIds } } : {}) }, orderBy: { name: "asc" } }),
    prisma.healthSpecialty.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.healthService.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.material.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.materialStock.findMany({ where: { quantity: { gt: 0 }, warehouse: { healthUnitId: unitIds ? { in: unitIds } : { not: null } } }, include: { material: true, warehouse: true }, orderBy: { expirationDate: "asc" } }),
    prisma.specializedQuota.findMany({ where: unitIds ? { patient: { referenceUnitId: { in: unitIds } } } : {}, include: { patient: { include: { person: true } }, material: true }, orderBy: { createdAt: "desc" } }),
    prisma.medicalRecord.findMany({ where: unitIds ? { unitId: { in: unitIds } } : {}, orderBy: { date: "desc" }, take: 300, include: { patient: { include: { person: true } } } }),
  ]);
  return <PageFrame className="flex h-[calc(100dvh-7.5rem)] min-h-0 flex-col gap-2 overflow-hidden px-1 py-1 md:px-2">
    <PageHeader title="Centro Especializado" icon={<Accessibility className="size-4 text-violet-700"/>}/>
    <div className="grid shrink-0 gap-2 md:grid-cols-2 xl:grid-cols-3">
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Catálogo clínico</summary><form action={saveCatalogAction} className="mt-2 grid gap-1"><select name="category" required className={field}>{["AMPUTATION","HEARING","DISABILITY","SWALLOWING","COGNITIVE","PROSTHESIS","FEEDING_ROUTE","DEPENDENCE","NUTRITION","STAGE","LANGUAGE","STAY_LOCATION","DRESSING","LOCOMOTION","KINSHIP","PERIOD","AIH_HAN_PROFILE","OSTOMY_BAG"].map(x => <option key={x}>{x}</option>)}</select><input name="code" required placeholder="Código" className={field}/><input name="name" required placeholder="Descrição" className={field}/><input name="referenceValue" type="number" min="0" step="0.01" placeholder="Valor de referência" className={field}/><select name="materialId" className={field}><option value="">Sem produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="h-8 rounded bg-violet-700 font-semibold text-white">Salvar</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Capacidade mensal</summary><form action={saveScheduleAction} className="mt-2 grid gap-1"><select name="teamId" required className={field}><option value="">Equipe</option>{teams.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="month" type="month" required className={field}/><input name="patientCapacity" type="number" min="1" required placeholder="Capacidade" className={field}/><button className="h-8 rounded bg-violet-700 font-semibold text-white">Salvar</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Plano terapêutico</summary><form action={createPlanAction} className="mt-2 grid gap-1"><select name="patientId" required className={field}><option value="">Paciente</option>{patients.map(x => <option key={x.id} value={x.id}>{x.person.fullName}</option>)}</select><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="teamId" required className={field}><option value="">Equipe</option>{teams.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="initialMedicalRecordId" className={field}><option value="">Sem prontuário inicial</option>{records.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.date.toLocaleDateString("pt-BR")}</option>)}</select><textarea name="goals" required placeholder="Objetivos definidos pela equipe" className="min-h-14 rounded border p-2"/><textarea name="carePlan" required placeholder="Plano e cuidados" className="min-h-14 rounded border p-2"/><input name="plannedConsultations" type="number" min="1" required placeholder="Consultas previstas" className={field}/><button className="h-8 rounded bg-violet-700 font-semibold text-white">Criar plano</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Parecer e evolução</summary><form action={addEntryAction} className="mt-2 grid gap-1"><select name="planId" required className={field}><option value="">Plano ativo</option>{planOptions.filter(x => x.status === "ACTIVE").map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName}</option>)}</select><select name="specialtyId" className={field}><option value="">Especialidade</option>{specialties.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="healthServiceId" className={field}><option value="">Serviço</option>{services.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="kind" className={field}><option value="OPINION">Parecer</option><option value="EVOLUTION">Evolução</option><option value="INTERCONSULTATION">Interconsulta</option><option value="OUTCOME">Desfecho</option></select><textarea name="content" required placeholder="Registro profissional" className="min-h-14 rounded border p-2"/><input name="diagnosisSummary" placeholder="Síntese diagnóstica" className={field}/><div className="grid grid-cols-2 gap-1"><input name="weight" type="number" min="0" step="0.01" placeholder="Peso kg" className={field}/><input name="height" type="number" min="0" max="3" step="0.01" placeholder="Altura m" className={field}/></div><button className="h-8 rounded bg-violet-700 font-semibold text-white">Registrar</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cota de produto</summary><form action={saveQuotaAction} className="mt-2 grid gap-1"><select name="patientId" required className={field}><option value="">Paciente</option>{patients.map(x => <option key={x.id} value={x.id}>{x.person.fullName}</option>)}</select><select name="materialId" required className={field}><option value="">Produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="period" type="month" required className={field}/><input name="allowedQuantity" type="number" min="0.001" step="0.001" required placeholder="Quantidade" className={field}/><button className="h-8 rounded bg-violet-700 font-semibold text-white">Definir cota</button></form></details>
      <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Distribuir produto</summary><form action={distributeAction} className="mt-2 grid gap-1"><select name="planId" required className={field}><option value="">Plano ativo</option>{planOptions.filter(x => x.status === "ACTIVE").map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName}</option>)}</select><select name="quotaId" className={field}><option value="">Sem cota</option>{quotas.map(x => <option key={x.id} value={x.id}>{x.patient.person.fullName} · {x.material.name} · {x.consumedQuantity}/{x.allowedQuantity}</option>)}</select><select name="warehouseId" required className={field}><option value="">Estoque</option>{[...new Map(stocks.map(x => [x.warehouse.id, x.warehouse])).values()].map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="materialId" required className={field}><option value="">Produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="batchNumber" required placeholder="Lote" className={field}/><input name="quantity" required type="number" min="0.001" step="0.001" placeholder="Quantidade" className={field}/><input name="notes" placeholder="Observação" className={field}/><button className="h-8 rounded bg-violet-700 font-semibold text-white">Confirmar entrega</button></form></details>
    </div>
    <HealthSimpleListClient rows={plans.map(x => ({ id: x.id, cells: { patient: x.patient.person.fullName, unit: x.unit.name, team: x.team.name, started: x.startedAt.toLocaleDateString("pt-BR"), progress: `${x.completedConsultations}/${x.plannedConsultations}`, lastEntry: x.entries[0] ? `${x.entries[0].professional.employee.person?.fullName || "Profissional"} · ${x.entries[0].kind}` : "-", status: x.status } }))} columns={[{ key: "patient", label: "Paciente" }, { key: "unit", label: "Unidade", responsive: "sm" }, { key: "team", label: "Equipe", responsive: "sm" }, { key: "started", label: "Início", responsive: "md", width: "medium" }, { key: "progress", label: "Consultas", align: "center", width: "medium" }, { key: "lastEntry", label: "Último registro", responsive: "lg" }, { key: "status", label: "Situação", width: "medium" }]} label="planos" searchPlaceholder="Buscar paciente, unidade ou equipe" filterKey="status" filterLabel="Todas as situações" serverPagination={{ page, total, pathname: "/app-domain/saude/centro-especializado", search: q, filter, filterOptions: ["ACTIVE", "COMPLETED", "CANCELLED"] }} />
  </PageFrame>;
}
