"use server";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";
import { advanceExecutionCase, annotateCda, createCdaVersion, createDaPortfolio, createExecutionBatch, createProtestBatch, enrollAssessmentDebt, enrollManualDebt, issueCda, issueDaGuide, openExecutionCase, refreshDaPortfolio, registerMni, registerProtestReturn, resolveProtestItem, resumeDebt, returnDebtToOrigin, runPrescription, scheduleHearing, settleDebtByGuide, signCdaInternal, suspendDebt, validateDebt, writeOffDebt } from "@/lib/tributacao/s9-service";
const path = "/tributacao/divida-ativa";
const done = (error?: unknown) => ({ error: error instanceof Error ? error.message : error ? "Não foi possível concluir a operação." : undefined });
async function ctx(operation: "create" | "update") { return getTenantContextForModuleOperation("TRIBUTACAO", operation); }
const actor = (c: Awaited<ReturnType<typeof ctx>>) => ({ usuarioId: c.user.id });
export async function enrollAssessmentAction(assessmentId: string) { try { const c = await ctx("create"); await enrollAssessmentDebt(c.prisma, actor(c), assessmentId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function enrollManualAction(input: Parameters<typeof enrollManualDebt>[2]) { try { const c = await ctx("create"); const r = await enrollManualDebt(c.prisma, actor(c), input); revalidatePath(path); return done(r.created ? undefined : "Origem já inscrita — nenhuma dívida duplicada foi criada."); } catch (e) { return done(e); } }
export async function validateDebtAction(debtId: string) { try { const c = await ctx("update"); await validateDebt(c.prisma, actor(c), debtId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function issueCdaAction(debtId: string) { try { const c = await ctx("create"); await issueCda(c.prisma, actor(c), debtId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function annotateCdaAction(input: Parameters<typeof annotateCda>[2]) { try { const c = await ctx("update"); await annotateCda(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function versionCdaAction(debtId: string) { try { const c = await ctx("create"); await createCdaVersion(c.prisma, actor(c), debtId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function signCdaAction(versionId: string) { try { const c = await ctx("update"); await signCdaInternal(c.prisma, actor(c), versionId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createDaPortfolioAction(input: Parameters<typeof createDaPortfolio>[2]) { try { const c = await ctx("create"); await createDaPortfolio(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function refreshDaPortfolioAction(portfolioId: string) { try { const c = await ctx("update"); const count = await refreshDaPortfolio(c.prisma, portfolioId); revalidatePath(path); return done(`Carteira atualizada: ${count} dívidas.`); } catch (e) { return done(e); } }
export async function issueDaGuideAction(input: { debtId: string; dueDate: string }) { try { const c = await ctx("create"); await issueDaGuide(c.prisma, actor(c), { debtId: input.debtId, dueDate: new Date(input.dueDate) }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function suspendDebtAction(input: { debtId: string; reason: string; endsAt?: string }) { try { const c = await ctx("update"); await suspendDebt(c.prisma, actor(c), { debtId: input.debtId, reason: input.reason, endsAt: input.endsAt ? new Date(input.endsAt) : undefined }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function resumeDebtAction(debtId: string) { try { const c = await ctx("update"); await resumeDebt(c.prisma, actor(c), debtId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function returnDebtToOriginAction(input: Parameters<typeof returnDebtToOrigin>[2]) { try { const c = await ctx("update"); await returnDebtToOrigin(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function settleDebtByGuideAction(input: { debtId: string; guideId: string; amount: number; paymentMethod: string }) { try { const c = await ctx("update"); await settleDebtByGuide(c.prisma, actor(c), { ...input, idempotencyKey: `DA-${input.guideId}-${Date.now()}` }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function writeOffDebtAction(input: Parameters<typeof writeOffDebt>[2]) { try { const c = await ctx("update"); await writeOffDebt(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function runPrescriptionAction(years: number) { try { const c = await ctx("update"); const r = await runPrescription(c.prisma, actor(c), years); revalidatePath(path); return done(`${r.count} dívidas baixadas por prescrição (${r.years} anos).`); } catch (e) { return done(e); } }
export async function createProtestBatchAction(debtIds: string[]) { try { const c = await ctx("create"); await createProtestBatch(c.prisma, actor(c), debtIds); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerProtestReturnAction(input: { batchId: string; itemId: string; code: string; message: string }) { try { const c = await ctx("update"); await registerProtestReturn(c.prisma, actor(c), { batchId: input.batchId, returns: [{ itemId: input.itemId, code: input.code, message: input.message }] }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function resolveProtestItemAction(input: Parameters<typeof resolveProtestItem>[2]) { try { const c = await ctx("update"); await resolveProtestItem(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createExecutionBatchAction(input: Parameters<typeof createExecutionBatch>[2]) { try { const c = await ctx("create"); await createExecutionBatch(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function openExecutionCaseAction(input: Parameters<typeof openExecutionCase>[2]) { try { const c = await ctx("create"); await openExecutionCase(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function advanceExecutionCaseAction(input: Parameters<typeof advanceExecutionCase>[2]) { try { const c = await ctx("update"); await advanceExecutionCase(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerMniAction(caseId: string) { try { const c = await ctx("update"); await registerMni(c.prisma, actor(c), caseId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function scheduleHearingAction(input: { caseId: string; date: string; notes?: string }) { try { const c = await ctx("update"); await scheduleHearing(c.prisma, actor(c), { caseId: input.caseId, date: new Date(input.date), notes: input.notes }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
