"use client";
import { useState, useTransition } from "react";
import { Banknote, FileWarning, Gavel, ScrollText } from "lucide-react";
import { advanceExecutionCaseAction, annotateCdaAction, createDaPortfolioAction, createExecutionBatchAction, createProtestBatchAction, enrollAssessmentAction, enrollManualAction, issueCdaAction, issueDaGuideAction, openExecutionCaseAction, refreshDaPortfolioAction, registerMniAction, registerProtestReturnAction, resolveProtestItemAction, resumeDebtAction, returnDebtToOriginAction, runPrescriptionAction, scheduleHearingAction, settleDebtByGuideAction, signCdaAction, suspendDebtAction, validateDebtAction, versionCdaAction, writeOffDebtAction } from "./actions";
type Debt = { id: string; cda: string; origin: string; year: number; taxpayer: string; original: number; updated: number; status: string; assessmentId: string | null; sourceKey: string | null; versions: { id: string; version: number; cda: string; annotation: string | null; signature: string; createdAt: string }[]; suspensions: { id: string; reason: string; status: string }[]; events: string[] };
type Data = { taxpayers: { id: string; name: string; document: string }[]; candidates: { id: string; number: string; taxpayerId: string; taxpayer: string; origin: string; year: number; value: number; status: string; eligible: boolean; reasons: string[]; enrolledDebtId: string | null }[]; debts: Debt[]; portfolios: { id: string; name: string; status: string; items: { id: string; debtId: string; outstanding: number }[] }[]; protestBatches: { id: string; number: string; status: string; items: { id: string; debtId: string; status: string; returnCode: string | null; returnMessage: string | null }[] }[]; executionBatches: { id: string; number: string; protocol: string; status: string; prosecutor: string | null; cases: { id: string; protocol: string; debtId: string; status: string; prosecutor: string | null; mni: string; nextHearing: string | null; events: string[] }[] }[]; guides: { id: string; number: string; debtId: string; status: string; total: number }[]; protestCandidates: { id: string; cda: string; taxpayer: string; value: number; status: string }[]; book: { id: string; year: number; cda: string; origin: string; taxpayer: string; original: number; updated: number; status: string }[] };
const input = "h-8 w-full rounded-md border border-slate-300 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-900";
const button = "inline-flex h-8 items-center justify-center rounded-md bg-amber-500 px-2.5 text-xs font-bold text-slate-950 hover:bg-amber-400 disabled:opacity-50";
const secondary = "inline-flex h-8 items-center justify-center rounded-md border px-2 text-xs font-semibold hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900";
const money = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function DividaAtivaClient({ data }: { data: Data }) {
  const [tab, setTab] = useState("inscricao");
  const [message, setMessage] = useState("");
  const [pending, start] = useTransition();
  const [taxpayerId, setTaxpayerId] = useState(data.taxpayers[0]?.id ?? "");
  const [selected, setSelected] = useState<string[]>([]);
  const run = (job: () => Promise<{ error?: string }>) => start(async () => { const r = await job(); setMessage(r.error ?? "Operação concluída."); });
  const submit = (handler: (form: FormData) => void) => (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); handler(new FormData(e.currentTarget)); };
  const toggle = (id: string) => setSelected((s) => s.includes(id) ? s.filter((x) => x !== id) : [...s, id]);
  const debtOf = (id: string) => data.debts.find((d) => d.id === id);
  return <div className="flex h-full min-h-0 flex-1 flex-col gap-2 overflow-hidden p-2 sm:p-2.5">
    <header className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="flex items-center gap-2 text-lg font-bold"><Banknote className="size-5 text-amber-500" />Dívida Ativa, Protesto e Execução</h1><p className="text-[11px] text-slate-500">Inscrição sem duplicidade, CDA versionada, remessa/retorno controlados e protocolo interno.</p></div><select className={`${input} max-w-72`} value={taxpayerId} onChange={(e) => setTaxpayerId(e.target.value)}>{data.taxpayers.map((t) => <option key={t.id} value={t.id}>{t.name} · {t.document}</option>)}</select></header>
    <nav className="flex gap-1 overflow-x-auto rounded-lg bg-slate-900 p-1 text-[11px] font-semibold text-slate-300">{[["inscricao", "Inscrição e CDA"], ["carteiras", "Carteiras"], ["protesto", "Protesto"], ["execucao", "Execução Fiscal"], ["relatorios", "Livro e Relatórios"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-md px-3 py-1.5 ${tab === id ? "bg-amber-500 text-slate-950" : "hover:bg-slate-800"}`}>{label}</button>)}</nav>
    {message && <button onClick={() => setMessage("")} className="rounded-md border border-blue-200 bg-blue-50 px-3 py-1 text-left text-xs text-blue-800">{message}</button>}
    <main className="min-h-0 flex-1 overflow-auto">
      {tab === "inscricao" && <div className="grid gap-2">
        <section className="rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><h2 className="text-sm font-bold">Débitos elegíveis → validar → inscrever</h2><div className="mt-2 grid gap-1">{data.candidates.slice(0, 30).map((c) => <div key={c.id} className="flex flex-wrap items-center gap-2 rounded border p-2 text-[11px] dark:border-slate-700"><b>{c.number}</b><span>{c.taxpayer} · {c.origin}/{c.year} · {money(c.value)}</span>{c.enrolledDebtId ? <span className="rounded bg-green-100 px-2 py-0.5 text-green-800">Inscrita (sem duplicar)</span> : c.eligible ? <button className={button} disabled={pending} onClick={() => run(() => enrollAssessmentAction(c.id))}>Inscrever</button> : <span className="text-red-700" title={c.reasons.join(" ")}>Bloqueada: {c.reasons[0]}</span>}</div>)}{!data.candidates.length && <p className="text-xs text-slate-500">Sem lançamentos pendentes de inscrição.</p>}</div></section>
        <div className="grid gap-2 xl:grid-cols-2">
          <form className="grid content-start gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => enrollManualAction({ taxpayerId, originDebtType: String(f.get("origin")), year: Number(f.get("year")), value: Number(f.get("value")), sourceKey: String(f.get("key")) })))}><h2 className="text-sm font-bold">Inscrição manual / arquivo</h2><input className={input} name="origin" placeholder="Origem (ex.: IPTU)" required /><div className="grid grid-cols-3 gap-2"><input className={input} name="year" type="number" defaultValue={2026} /><input className={input} name="value" type="number" step="0.01" placeholder="Valor" required /><input className={input} name="key" placeholder="Chave de origem" required /></div><button className={button}>Inscrever sem duplicar</button><p className="text-[10px] text-slate-500">A chave identifica a origem (arquivo+linha ou código manual); reenvio retorna a dívida atual.</p></form>
          <form className="grid content-start gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => suspendDebtAction({ debtId: String(f.get("debt")), reason: String(f.get("reason")), endsAt: String(f.get("ends")) || undefined })))}><h2 className="text-sm font-bold">Suspensão com motivo e prazo</h2><select className={input} name="debt">{data.debts.filter((d) => ["INSCRITA", "VALIDADA", "EM_COBRANCA"].includes(d.status)).map((d) => <option key={d.id} value={d.id}>{d.cda} · {money(d.updated)}</option>)}</select><input className={input} name="reason" placeholder="Motivo" required /><input className={input} name="ends" type="date" /><button className={button}>Suspender</button></form>
        </div>
        {data.debts.slice(0, 30).map((d) => <article key={d.id} className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{d.cda} · {d.taxpayer}</b><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-900">{d.status}</span><span className="ml-auto">Original {money(d.original)} · <b>Atualizado {money(d.updated)}</b></span></div>
          <div className="mt-2 flex flex-wrap gap-1">
            {d.status === "PENDENTE_DE_VALIDACAO" && <button className={button} disabled={pending} onClick={() => run(() => validateDebtAction(d.id))}>Validar</button>}
            {(d.status === "VALIDADA" || (d.status === "INSCRITA" && d.cda === "SEM CDA")) && <button className={button} disabled={pending} onClick={() => run(() => issueCdaAction(d.id))}>Emitir CDA</button>}
            {d.cda !== "SEM CDA" && <><a className={secondary} target="_blank" href={`/tributacao/divida-ativa/cda/${d.id}/pdf`}>PDF</a><button className={secondary} disabled={pending} onClick={() => run(() => versionCdaAction(d.id))}>Versionar</button><button className={secondary} disabled={pending} onClick={() => { const note = window.prompt("Anotação da CDA:"); if (note) run(() => annotateCdaAction({ debtId: d.id, annotation: note })); }}>Anotar</button></>}
            {d.status === "SUSPENSA" && <button className={secondary} disabled={pending} onClick={() => run(() => resumeDebtAction(d.id))}>Retomar</button>}
            {!["PAGA", "BAIXADA", "BAIXADA_PRESCRICAO", "DEVOLVIDA", "CANCELADA"].includes(d.status) && <><button className={secondary} disabled={pending} onClick={() => { const r = window.prompt("Justificativa da baixa manual:"); if (r) run(() => writeOffDebtAction({ debtId: d.id, reason: r })); }}>Baixa justificada</button><button className={secondary} disabled={pending} onClick={() => { const r = window.prompt("Motivo da devolução à origem:"); if (r) run(() => returnDebtToOriginAction({ debtId: d.id, reason: r })); }}>Devolver</button></>}
          </div>
          {d.versions.length > 0 && <div className="mt-2 rounded border p-2 dark:border-slate-700"><b>Versões da CDA</b>{d.versions.map((v) => <div key={v.id} className="flex flex-wrap items-center gap-2">v{v.version} · {v.signature}{v.annotation ? ` · ${v.annotation}` : ""}{v.signature === "NAO_ASSINADA" && <button className={secondary} disabled={pending} onClick={() => run(() => signCdaAction(v.id))}>Assinar internamente</button>}</div>)}</div>}
          {d.cda !== "SEM CDA" && <form className="mt-2 flex flex-wrap items-center gap-1" onSubmit={submit((f) => run(() => issueDaGuideAction({ debtId: d.id, dueDate: String(f.get("due")) })))}><input className={input} style={{ maxWidth: 150 }} name="due" type="date" defaultValue="2026-12-20" required /><button className={secondary}>Emitir DAM</button></form>}
          {data.guides.filter((g) => g.debtId === d.id).map((g) => <form key={g.id} className="mt-1 flex flex-wrap items-center gap-1" onSubmit={submit(() => run(() => settleDebtByGuideAction({ debtId: d.id, guideId: g.id, amount: g.total, paymentMethod: "Manual" })))}><span>{g.number} · {money(g.total)} · {g.status}</span><button className={secondary} disabled={pending || g.status === "Paga"}>Confirmar pagamento</button></form>)}
          {d.events.length > 0 && <details className="mt-2"><summary className="cursor-pointer text-blue-600">Histórico ({d.events.length})</summary>{d.events.map((e, i) => <div key={i}>• {e}</div>)}</details>}
        </article>)}
      </div>}
      {tab === "carteiras" && <div className="grid gap-2">
        <form className="flex flex-wrap items-center gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => createDaPortfolioAction({ name: String(f.get("name")), minValue: Number(f.get("min") || 0) })))}><input className={input} style={{ maxWidth: 260 }} name="name" placeholder="Nome da carteira" required /><input className={input} style={{ maxWidth: 130 }} name="min" type="number" step="0.01" defaultValue={500} /><button className={button}>Criar carteira</button></form>
        {data.portfolios.map((p) => <article key={p.id} className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{p.name}</b><span>{p.status} · {p.items.length} dívidas · {money(p.items.reduce((s, i) => s + i.outstanding, 0))}</span><button className={`${secondary} ml-auto`} disabled={pending} onClick={() => run(() => refreshDaPortfolioAction(p.id))}>Atualizar carteira</button></div>{p.items.slice(0, 20).map((i) => { const d = debtOf(i.debtId); return <div key={i.id}>• {d ? `${d.cda} · ${d.taxpayer}` : i.debtId} — {money(i.outstanding)}</div>; })}</article>)}
      </div>}
      {tab === "protesto" && <div className="grid gap-2">
        <section className="rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><h2 className="flex items-center gap-2 text-sm font-bold"><FileWarning className="size-4" />Seleção de CDAs para protesto</h2><p className="my-1 text-[10px] text-slate-500">Remessa interna controlada — sem convênio real, sem protesto efetivado presumido.</p><div className="grid gap-1">{data.protestCandidates.map((c) => <label key={c.id} className="flex items-center gap-2 text-[11px]"><input type="checkbox" checked={selected.includes(c.id)} onChange={() => toggle(c.id)} /><b>{c.cda}</b> · {c.taxpayer} · {money(c.value)}</label>)}</div><button className={`${button} mt-2`} disabled={pending || !selected.length} onClick={() => run(() => createProtestBatchAction(selected))}>Gerar remessa ({selected.length})</button></section>
        {data.protestBatches.map((b) => <article key={b.id} className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><b className="text-sm">{b.number} · {b.status}</b>{b.items.map((i) => { const d = debtOf(i.debtId); return <div key={i.id} className="mt-1 rounded border p-2 dark:border-slate-700"><div className="flex flex-wrap items-center gap-2"><b>{d?.cda ?? i.debtId}</b><span>{i.status}</span>{i.returnCode && <span>Retorno {i.returnCode}: {i.returnMessage}</span>}</div><div className="mt-1 flex flex-wrap gap-1">{i.status === "REMESSA_PREPARADA" && <form className="flex flex-wrap gap-1" onSubmit={submit((f) => run(() => registerProtestReturnAction({ batchId: b.id, itemId: i.id, code: String(f.get("code")), message: String(f.get("msg")) })))}><input className={input} style={{ maxWidth: 110 }} name="code" placeholder="Código" required /><input className={input} style={{ maxWidth: 220 }} name="msg" placeholder="Mensagem do retorno" required /><button className={secondary}>Registrar retorno</button></form>}{i.status === "EM_ACOMPANHAMENTO" && <><button className={secondary} disabled={pending} onClick={() => run(() => resolveProtestItemAction({ itemId: i.id, action: "BAIXAR_PAGAMENTO", reason: "Pagamento confirmado no retorno controlado." }))}>Baixar por pagamento</button><button className={secondary} disabled={pending} onClick={() => run(() => resolveProtestItemAction({ itemId: i.id, action: "CANCELAR", reason: "Desistência registrada pela área tributária." }))}>Cancelar</button><button className={secondary} disabled={pending} onClick={() => run(() => resolveProtestItemAction({ itemId: i.id, action: "ANUIR", reason: "Anuência para baixa junto ao cartório." }))}>Anuir</button></>}</div></div>; })}</article>)}
      </div>}
      {tab === "execucao" && <div className="grid gap-2">
        <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => createExecutionBatchAction({ debtIds: selected, prosecutor: String(f.get("proc")) })))}><h2 className="flex items-center gap-2 text-sm font-bold"><Gavel className="size-4" />Lote para ajuizamento (marque as dívidas na lista abaixo)</h2><input className={input} name="proc" placeholder="Procurador responsável" required /><button className={button} disabled={pending || !selected.length}>Criar lote ({selected.length})</button></form>
        <section className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><b>CDAs aptas</b><div className="grid gap-1">{data.debts.filter((d) => ["INSCRITA", "EM_COBRANCA", "EM_PROTESTO"].includes(d.status) && d.cda !== "SEM CDA").map((d) => <label key={d.id} className="flex items-center gap-2"><input type="checkbox" checked={selected.includes(d.id)} onChange={() => toggle(d.id)} /><b>{d.cda}</b> · {d.taxpayer} · {money(d.updated)} · {d.status}</label>)}</div></section>
        {data.executionBatches.map((b) => <article key={b.id} className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><b className="text-sm">{b.number} · {b.protocol} · {b.status}</b> · {b.prosecutor}{b.cases.map((c) => <div key={c.id} className="mt-1 rounded border p-2 dark:border-slate-700"><div className="flex flex-wrap items-center gap-2"><b>{c.protocol}</b><span>{c.status} · MNI: {c.mni}</span>{c.nextHearing && <span>Agenda: {new Date(c.nextHearing).toLocaleString("pt-BR")}</span>}</div><div className="mt-1 flex flex-wrap gap-1">
          {c.status === "EM_PREPARO" && <button className={secondary} disabled={pending} onClick={() => run(() => advanceExecutionCaseAction({ caseId: c.id, action: "ENVIAR_PROCURADORIA", description: "Lote enviado à Procuradoria com peças reunidas." }))}>Enviar à Procuradoria</button>}
          {c.status === "NA_PROCURADORIA" && <button className={secondary} disabled={pending} onClick={() => run(() => advanceExecutionCaseAction({ caseId: c.id, action: "REGISTRAR_PROTOCOLO", description: "Protocolo interno registrado na Procuradoria." }))}>Registrar protocolo</button>}
          {c.status === "PROTOCOLADO_INTERNO" && <><button className={secondary} disabled={pending} onClick={() => run(() => registerMniAction(c.id))}>Registrar MNI (interno)</button><button className={secondary} disabled={pending} onClick={() => run(() => advanceExecutionCaseAction({ caseId: c.id, action: "ACOMPANHAR", description: "Acompanhamento iniciado sem intercâmbio oficial." }))}>Acompanhar</button></>}
          {(c.status === "MNI_REGISTRO_INTERNO" || c.status === "EM_ACOMPANHAMENTO") && <><button className={secondary} disabled={pending} onClick={() => run(() => advanceExecutionCaseAction({ caseId: c.id, action: "REGISTRAR_RETORNO", description: "Retorno da Procuradoria registrado." }))}>Registrar retorno</button><form className="flex flex-wrap gap-1" onSubmit={submit((f) => run(() => scheduleHearingAction({ caseId: c.id, date: String(f.get("date")), notes: String(f.get("notes") || "") })))}><input className={input} style={{ maxWidth: 170 }} name="date" type="datetime-local" required /><input className={input} style={{ maxWidth: 200 }} name="notes" placeholder="Pauta" /><button className={secondary}>Agendar</button></form></>}
          {c.status === "RETORNADO" && <button className={secondary} disabled={pending} onClick={() => run(() => advanceExecutionCaseAction({ caseId: c.id, action: "ENCERRAR", description: "Caso encerrado com retorno arquivado." }))}>Encerrar</button>}
        </div>{c.events.length > 0 && <details className="mt-1"><summary className="cursor-pointer text-blue-600">Andamentos ({c.events.length})</summary>{c.events.map((e, i) => <div key={i}>• {e}</div>)}</details>}</div>)}</article>)}
        <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => openExecutionCaseAction({ debtId: String(f.get("debt")), prosecutor: String(f.get("proc")), attorneyReference: String(f.get("att") || ""), attachments: [] })))}><h2 className="text-sm font-bold">Abertura avulsa com procuração e anexos</h2><div className="grid gap-2 sm:grid-cols-3"><select className={input} name="debt">{data.debts.filter((d) => ["INSCRITA", "EM_COBRANCA", "EM_PROTESTO"].includes(d.status) && d.cda !== "SEM CDA").map((d) => <option key={d.id} value={d.id}>{d.cda}</option>)}</select><input className={input} name="proc" placeholder="Procurador" required /><input className={input} name="att" placeholder="Referência da procuração" /></div><button className={button}>Abrir caso</button></form>
      </div>}
      {tab === "relatorios" && <div className="grid gap-2">
        <section className="flex flex-wrap items-center gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><ScrollText className="size-5" /><div className="mr-auto"><b className="text-sm">Livro de dívida ativa</b><p className="text-[10px] text-slate-500">Exercício e origem, sem nova dívida duplicada.</p></div><button className={button} disabled={pending} onClick={() => run(() => runPrescriptionAction(5))}>Baixa automática por prescrição (5 anos)</button></section>
        <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-6 gap-2 border-b bg-slate-50 p-2 font-bold dark:bg-slate-900"><span>CDA</span><span>Contribuinte</span><span>Origem</span><span>Ano</span><span>Atualizado</span><span>Situação</span></div>{data.book.map((b) => <div key={b.id} className="grid grid-cols-6 gap-2 border-t p-2"><span>{b.cda}</span><span>{b.taxpayer}</span><span>{b.origin}</span><span>{b.year}</span><span>{money(b.updated)}</span><span>{b.status}</span></div>)}</section>
      </div>}
    </main>
  </div>;
}
