import { Siren } from "lucide-react";
import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { HealthSimpleListClient } from "../HealthSimpleListClient";
import { ensureRiskProtocols } from "@/lib/saude/reception-service";
import { admitBedAction, createObservationAction, createReceptionAction, dischargeBedAction, linkReceptionAction, saveBedAction, saveDestinationAction, saveProtocolAction, saveRoomAction, transitionBedAction, transitionObservationAction, transitionReceptionAction } from "./actions";
import type { Prisma } from "@prisma/client";

const field = "h-8 min-w-0 rounded border border-slate-200 bg-white px-2 text-xs";
const PAGE_SIZE = 20;
type Params = { q?: string | string[]; page?: string | string[] };
const first = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
const num = (v: string | undefined) => v && /^\d+$/.test(v) && Number(v) > 0 ? Number(v) : 1;
const waitMinutes = (since: Date) => Math.max(0, Math.round((Date.now() - since.getTime()) / 60000));

export default async function ProntoAtendimentoPage({ searchParams }: { searchParams: Promise<Params> }) {
  const context = await getTenantContextForModule("SAUDE");
  const { prisma } = context;
  const unitIds = context.user.hasHealthAccessScope ? context.user.allowedHealthUnitIds || [] : undefined;
  const params = await searchParams;
  const q = (first(params.q) || "").trim().slice(0, 120);
  await ensureRiskProtocols(context);
  const where: Prisma.HealthReceptionWhereInput = {
    ...(unitIds ? { unitId: { in: unitIds } } : {}),
    ...(q ? { OR: [{ patient: { person: { fullName: { contains: q, mode: "insensitive" } } } }, { unidentifiedName: { contains: q, mode: "insensitive" } }, { companionName: { contains: q, mode: "insensitive" } }] } : {}),
  };
  const total = await prisma.healthReception.count({ where });
  const page = Math.min(num(first(params.page)), Math.max(1, Math.ceil(total / PAGE_SIZE)));
  const [receptions, patients, units, rooms, destinations, protocols, beds, occupancies, observations] = await Promise.all([
    prisma.healthReception.findMany({ where, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, orderBy: { arrivalAt: "desc" }, include: { patient: { select: { person: { select: { fullName: true } } } }, unit: { select: { name: true } }, room: { select: { name: true } }, destination: { select: { name: true } } } }),
    prisma.patient.findMany({ where: { status: "Ativo", ...(unitIds ? { referenceUnitId: { in: unitIds } } : {}) }, take: 300, orderBy: { person: { fullName: "asc" } }, include: { person: { select: { fullName: true } } } }),
    prisma.healthUnit.findMany({ where: { isActive: true, ...(unitIds ? { id: { in: unitIds } } : {}) }, orderBy: { name: "asc" } }),
    prisma.healthRoom.findMany({ where: { isActive: true, ...(unitIds ? { unitId: { in: unitIds } } : {}) }, orderBy: { name: "asc" }, take: 200 }),
    prisma.healthDestination.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.healthRiskProtocol.findMany({ where: { isActive: true }, orderBy: { level: "asc" } }),
    prisma.healthBed.findMany({ where: unitIds ? { unitId: { in: unitIds } } : {}, orderBy: [{ unitId: "asc" }, { code: "asc" }], take: 200, include: { unit: { select: { name: true } } } }),
    prisma.healthBedOccupancy.findMany({ where: { dischargedAt: null, ...(unitIds ? { bed: { unitId: { in: unitIds } } } : {}) }, include: { bed: { include: { unit: { select: { name: true } } } }, patient: { include: { person: { select: { fullName: true } } } } }, orderBy: { admittedAt: "desc" }, take: 200 }),
    prisma.healthObservation.findMany({ where: { status: "Em observação", ...(unitIds ? { unitId: { in: unitIds } } : {}) }, include: { patient: { include: { person: { select: { fullName: true } } } }, unit: { select: { name: true } }, bed: { select: { code: true } } }, orderBy: { admittedAt: "desc" }, take: 200 }),
  ]);

  return (
    <PageFrame className="flex h-[calc(100dvh-7.5rem)] min-h-0 flex-col gap-2 overflow-hidden px-1 py-1 md:px-2">
      <PageHeader title="Pronto Atendimento" icon={<Siren className="size-4 text-rose-700" />} />
      <div className="grid shrink-0 gap-2 lg:grid-cols-4">
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Recepção</summary><form action={createReceptionAction} className="mt-2 grid gap-1"><select name="patientId" className={field}><option value="">Paciente identificado</option>{patients.map(p => <option key={p.id} value={p.id}>{p.person.fullName}</option>)}</select><input name="unidentifiedName" placeholder="Ou nome sem identificação" className={field} /><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="flex gap-2">{["GESTANTE", "IDOSO", "DEFICIENTE"].map(f => <label key={f} className="flex items-center gap-1"><input type="checkbox" name={`flag_${f}`} />{f}</label>)}</div><input name="companionName" placeholder="Acompanhante" className={field} /><div className="grid grid-cols-2 gap-1"><input name="companionKinship" placeholder="Parentesco" className={field} /><input name="companionPhone" placeholder="Fone acompanhante" className={field} /></div><select name="transportMode" className={field}><option value="">Transporte</option><option>Meios próprios</option><option>Socorro</option></select><input name="agreement" placeholder="Convênio" className={field} /><select name="roomId" className={field}><option value="">Sala</option>{rooms.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><select name="destinationId" className={field}><option value="">Destino</option>{destinations.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="h-8 rounded bg-rose-700 font-semibold text-white">Recepcionar</button></form>
          <form action={transitionReceptionAction} className="mt-2 grid gap-1 border-t pt-2"><select name="receptionId" required className={field}><option value="">Recepção</option>{receptions.filter(r => !["Concluída", "Evadiu-se", "Cancelada"].includes(r.status)).map(r => <option key={r.id} value={r.id}>{r.patient?.person.fullName || r.unidentifiedName}</option>)}</select><select name="status" required className={field}><option>Em atendimento</option><option>Concluída</option><option>Evadiu-se</option><option>Cancelada</option></select><input name="outcome" placeholder="Desfecho" className={field} /><button className="h-7 rounded border px-2">Atualizar</button></form>
          <form action={linkReceptionAction} className="mt-2 grid gap-1 border-t pt-2"><select name="receptionId" required className={field}><option value="">Sem identificação</option>{receptions.filter(r => !r.patientId).map(r => <option key={r.id} value={r.id}>{r.unidentifiedName}</option>)}</select><select name="patientId" required className={field}><option value="">Vincular paciente</option>{patients.map(p => <option key={p.id} value={p.id}>{p.person.fullName}</option>)}</select><button className="h-7 rounded border px-2">Vincular</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Risco, salas e destinos</summary>
          {protocols.map(p => <form key={p.id} action={saveProtocolAction} className="mt-1 grid grid-cols-[2rem_1fr_4rem_4rem_auto] items-center gap-1"><input type="hidden" name="level" value={p.level} /><span className="inline-block size-4 rounded" style={{ background: p.colorHex }} /><input name="label" defaultValue={p.label} required className={field} /><input name="maxWaitMinutes" type="number" min="0" defaultValue={p.maxWaitMinutes} className={field} /><input name="colorHex" defaultValue={p.colorHex} pattern="#[0-9a-fA-F]{6}" className="h-8 w-16 rounded border" /><button className="h-7 rounded border px-2">OK</button></form>)}
          <form action={saveRoomAction} className="mt-2 grid gap-1 border-t pt-2"><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><input name="name" required placeholder="Sala" className={field} /><select name="kind" className={field}><option>Atendimento</option><option>Triagem</option></select><button className="h-7 rounded border px-2">Salvar sala</button></form>
          <form action={saveDestinationAction} className="mt-2 grid gap-1 border-t pt-2"><input name="name" required placeholder="Destino" className={field} /><button className="h-7 rounded border px-2">Salvar destino</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Leitos e internação</summary>
          <form action={saveBedAction} className="mt-2 grid gap-1"><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="grid grid-cols-2 gap-1"><input name="room" placeholder="Quarto" className={field} /><input name="code" required placeholder="Leito" className={field} /></div><button className="h-7 rounded border px-2">Salvar leito</button></form>
          <form action={admitBedAction} className="mt-2 grid gap-1 border-t pt-2"><select name="bedId" required className={field}><option value="">Leito livre</option>{beds.filter(b => b.status === "Livre").map(b => <option key={b.id} value={b.id}>{b.unit.name} · {b.code}</option>)}</select><select name="patientId" required className={field}><option value="">Paciente</option>{patients.map(p => <option key={p.id} value={p.id}>{p.person.fullName}</option>)}</select><button className="h-7 rounded border px-2">Internar</button></form>
          <form action={transitionBedAction} className="mt-2 grid gap-1 border-t pt-2"><select name="bedId" required className={field}><option value="">Leito</option>{beds.map(b => <option key={b.id} value={b.id}>{b.unit.name} · {b.code} · {b.status}</option>)}</select><select name="status" required className={field}><option>Livre</option><option>Manutenção</option><option>Reservado</option><option>Limpeza</option></select><button className="h-7 rounded border px-2">Atualizar</button></form>
          <div className="mt-2 max-h-32 overflow-y-auto">{occupancies.map(o => <article key={o.id} className="mb-1 rounded border p-1"><strong>{o.patient.person.fullName}</strong><p className="text-slate-500">{o.bed.unit.name} · leito {o.bed.code}</p><form action={dischargeBedAction}><input type="hidden" name="occupancyId" value={o.id} /><button className="rounded border px-2 py-0.5">Alta do leito</button></form></article>)}</div></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Observação</summary>
          <form action={createObservationAction} className="mt-2 grid gap-1"><select name="patientId" required className={field}><option value="">Paciente</option>{patients.map(p => <option key={p.id} value={p.id}>{p.person.fullName}</option>)}</select><select name="unitId" required className={field}><option value="">Unidade</option>{units.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="bedId" className={field}><option value="">Leito</option>{beds.map(b => <option key={b.id} value={b.id}>{b.unit.name} · {b.code}</option>)}</select><input name="responsible" placeholder="Responsável" className={field} /><input name="solicitedBy" placeholder="Solicitante" className={field} /><button className="h-7 rounded border px-2">Admitir em observação</button></form>
          <div className="mt-2 max-h-32 overflow-y-auto">{observations.map(o => <article key={o.id} className="mb-1 rounded border p-1"><strong>{o.patient.person.fullName}</strong><p className="text-slate-500">{o.unit.name}{o.bed ? ` · leito ${o.bed.code}` : ""}</p><div className="flex gap-1"><form action={transitionObservationAction}><input type="hidden" name="observationId" value={o.id} /><input type="hidden" name="status" value="Alta" /><button className="rounded border px-2 py-0.5">Alta</button></form><form action={transitionObservationAction}><input type="hidden" name="observationId" value={o.id} /><input type="hidden" name="status" value="Transferido" /><button className="rounded border px-2 py-0.5">Transferir</button></form></div></article>)}</div></details>
      </div>
      <HealthSimpleListClient rows={receptions.map(r => ({ id: r.id, cells: { arrival: r.arrivalAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }), patient: r.patient?.person.fullName || r.unidentifiedName || "-", unit: r.unit.name, wait: `${waitMinutes(r.arrivalAt)} min`, flags: r.priorityFlags || "-", room: r.room?.name || "-", destination: r.destination?.name || "-", status: r.status } }))} columns={[{ key: "arrival", label: "Chegada", width: "narrow" }, { key: "patient", label: "Paciente" }, { key: "unit", label: "Unidade", responsive: "sm" }, { key: "wait", label: "Espera", width: "narrow" }, { key: "flags", label: "Prioridades", responsive: "md", width: "medium" }, { key: "room", label: "Sala", responsive: "lg", width: "medium" }, { key: "destination", label: "Destino", responsive: "lg" }, { key: "status", label: "Situação", width: "medium" }]} label="recepções" searchPlaceholder="Buscar paciente ou acompanhante" serverPagination={{ page, total, pathname: "/app-domain/saude/pronto-atendimento", search: q }} />
    </PageFrame>
  );
}
