"use client";

import Link from "next/link";
import { useState } from "react";
import { ClipboardCheck } from "lucide-react";
import { ErpPageTitle } from "@/components/app-ui/erp/ErpPageTitle";
import { createRecadastramentoCampaign, submitRecadastramentoRequest } from "./actions";

type Campaign = { id: string; code: string; title: string; data: unknown; startsAt: string; endsAt: string | null; status: string };
type RequestRow = { id: string; estateId: string; title: string; data: unknown; status: string; createdAt: string };
type Property = { id: string; label: string };
const fieldOptions = ["streetName", "number", "complement", "propertyUse", "builtArea", "landArea", "registration"];
function campaignData(data: unknown) { return data && typeof data === "object" && !Array.isArray(data) ? data as { allowedFields?: string[]; propertyCount?: number; scope?: Record<string, unknown> } : {}; }

export default function RecadastramentoClient({ campaigns, requests, properties }: { campaigns: Campaign[]; requests: RequestRow[]; properties: Property[] }) {
  const [message, setMessage] = useState("");
  async function create(formData: FormData) { const result = await createRecadastramentoCampaign({ code: String(formData.get("code") ?? ""), title: String(formData.get("title") ?? ""), startsAt: String(formData.get("startsAt") ?? ""), endsAt: String(formData.get("endsAt") ?? ""), fiscalZone: String(formData.get("fiscalZone") ?? ""), block: String(formData.get("block") ?? ""), status: String(formData.get("status") ?? ""), allowedFields: formData.getAll("allowedFields").map(String) }); setMessage(result.error ?? `Campanha criada para ${result.count} imóvel(is).`); }
  async function request(formData: FormData) { const result = await submitRecadastramentoRequest({ campaignCode: String(formData.get("campaignCode") ?? ""), estateId: String(formData.get("estateId") ?? ""), field: String(formData.get("field") ?? ""), proposedValue: String(formData.get("proposedValue") ?? "") }); setMessage(result.error ?? "Solicitação registrada e encaminhada para validação."); }
  return <div className="flex h-full min-h-0 flex-1 flex-col gap-2 overflow-hidden p-2 sm:p-2.5"><ErpPageTitle title="Recadastramento imobiliário" description="Campanhas, recortes e validação fiscal" icon={<ClipboardCheck className="size-4 text-emerald-600" />} />{message && <p className="rounded border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">{message}</p>}<div className="grid min-h-0 flex-1 gap-2 lg:grid-cols-2">
    <section className="min-h-0 overflow-auto rounded-md border border-slate-200 bg-white p-3"><h2 className="mb-2 text-xs font-bold">Nova campanha por recorte</h2><form action={create} className="grid gap-2 sm:grid-cols-2"><input name="code" required placeholder="Código" className="input" /><input name="title" required placeholder="Título" className="input" /><label className="text-[11px]">Início<input name="startsAt" required type="date" className="input mt-1" /></label><label className="text-[11px]">Encerramento<input name="endsAt" required type="date" className="input mt-1" /></label><select name="fiscalZone" className="input"><option value="">Todas as zonas</option><option>Urbana</option><option>Rural</option></select><input name="block" placeholder="Quadra opcional" className="input" /><select name="status" className="input"><option value="">Todas as situações</option><option>Regular</option><option>Pendente</option><option>Irregular</option></select><fieldset className="sm:col-span-2"><legend className="text-[11px] font-semibold">Campos permitidos ao contribuinte</legend><div className="mt-1 flex flex-wrap gap-2">{fieldOptions.map((field) => <label key={field} className="text-[10px]"><input name="allowedFields" value={field} type="checkbox" className="mr-1" />{field}</label>)}</div></fieldset><button className="h-7 rounded bg-emerald-700 px-3 text-xs font-semibold text-white sm:col-span-2">Criar campanha e aplicar recorte</button></form><div className="mt-3 space-y-1">{campaigns.map((campaign) => { const data = campaignData(campaign.data); return <div key={campaign.id} className="rounded border border-slate-100 p-2 text-[11px]"><b>{campaign.code} · {campaign.title}</b><span className="block text-slate-500">{data.propertyCount ?? 0} imóvel(is) · {data.allowedFields?.join(", ")}</span></div>; })}</div></section>
    <section className="min-h-0 overflow-auto rounded-md border border-slate-200 bg-white p-3"><h2 className="mb-2 text-xs font-bold">Solicitação do contribuinte</h2><form action={request} className="grid gap-2 sm:grid-cols-2"><select name="campaignCode" required className="input"><option value="">Campanha</option>{campaigns.map((campaign) => <option key={campaign.code} value={campaign.code}>{campaign.code} · {campaign.title}</option>)}</select><select name="estateId" required className="input"><option value="">Imóvel</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.label}</option>)}</select><select name="field" required className="input"><option value="">Campo</option>{fieldOptions.map((field) => <option key={field}>{field}</option>)}</select><input name="proposedValue" required placeholder="Valor proposto" className="input" /><button className="h-7 rounded bg-emerald-700 px-3 text-xs font-semibold text-white sm:col-span-2">Enviar para validação</button></form><div className="mt-3 space-y-1">{requests.map((item) => <div key={item.id} className="flex items-center justify-between rounded border border-slate-100 p-2 text-[11px]"><span><b>{item.title}</b><span className="block text-slate-500">{item.status.replaceAll("_", " ")} · {new Date(item.createdAt).toLocaleDateString("pt-BR")}</span></span><Link href={`/tributacao/recadastramento/protocolo/${item.id}`} target="_blank" className="font-semibold text-emerald-700 underline">Protocolo</Link></div>)}</div></section>
  </div></div>;
}
