import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import type { Prisma } from "@prisma/client";
import { Pill } from "lucide-react";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { HealthSimpleListClient } from "../HealthSimpleListClient";
import { createHealthProductAction, createHealthWarehouseAction, createPharmacyRequestAction, dispatchPharmacyIntegrationAction, dispatchTransferAction, dispenseAction, receiveStockAction, receiveTransferAction, saveDosageTemplateAction, saveMedicineInteractionAction, setStockBlockAction, toggleControlledBookAction, writeOffAction } from "./actions";

const input = "h-8 min-w-0 rounded border border-slate-200 bg-white px-2 text-xs";
const PAGE_SIZE = 20;
type Params = { q?: string | string[]; filter?: string | string[]; page?: string | string[] };
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const positivePage = (value: string | undefined) => value && /^\d+$/.test(value) && Number(value) > 0 ? Number(value) : 1;

export default async function Page({ searchParams }: { searchParams: Promise<Params> }) {
  const context = await getTenantContextForModule("SAUDE");
  const { prisma } = context;
  const unitIds = context.user.hasHealthAccessScope ? context.user.allowedHealthUnitIds || [] : undefined;
  const params = await searchParams;
  const q = (first(params.q) || "").trim().slice(0, 120);
  const filter = (first(params.filter) || "").trim().slice(0, 120);
  const stockWhere: Prisma.MaterialStockWhereInput = { material: { healthProfile: { isActive: true } }, warehouse: { healthUnitId: unitIds ? { in: unitIds } : { not: null }, ...(filter ? { name: filter } : {}) }, ...(q ? { OR: [{ material: { name: { contains: q, mode: "insensitive" } } }, { warehouse: { name: { contains: q, mode: "insensitive" } } }, { batchNumber: { contains: q, mode: "insensitive" } }] } : {}) };
  const total = await prisma.materialStock.count({ where: stockWhere });
  const page = Math.min(positivePage(first(params.page)), Math.max(1, Math.ceil(total / PAGE_SIZE)));
  const [stocks, stockOptions, warehouses, materials, suppliers, prescriptions, transfers, categories, units, medicines, patients] = await Promise.all([
    prisma.materialStock.findMany({ where: stockWhere, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, orderBy: [{ expirationDate: "asc" }, { createdAt: "desc" }], include: { material: true, warehouse: true } }),
    prisma.materialStock.findMany({ where: { material: { healthProfile: { isActive: true } }, warehouse: { healthUnitId: unitIds ? { in: unitIds } : { not: null } } }, take: 500, orderBy: [{ expirationDate: "asc" }, { createdAt: "desc" }], include: { material: true, warehouse: true } }),
    prisma.warehouse.findMany({ where: { isActive: true, healthUnitId: unitIds ? { in: unitIds } : { not: null } }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.material.findMany({ where: { isActive: true, healthProfile: { isActive: true } }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.supplier.findMany({ where: { status: "Ativo" }, take: 200, select: { id: true, person: { select: { fullName: true } }, company: { select: { corporateName: true } } } }),
    prisma.healthPrescriptionItem.findMany({ where: { medicine: { materialId: { not: null } }, ...(unitIds ? { prescription: { unitId: { in: unitIds } } } : {}) }, orderBy: { createdAt: "desc" }, take: 200, include: { prescription: { include: { patient: { include: { person: true } } } }, dispensations: true } }),
    prisma.healthStockTransfer.findMany({ where: { status: "IN_TRANSIT", ...(unitIds ? { OR: [{ originWarehouse: { healthUnitId: { in: unitIds } } }, { destinationWarehouse: { healthUnitId: { in: unitIds } } }] } : {}) }, orderBy: { createdAt: "desc" }, include: { originWarehouse: true, destinationWarehouse: true } }),
    prisma.materialCategory.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.healthUnit.findMany({ where: { isActive: true, ...(unitIds ? { id: { in: unitIds } } : {}) }, orderBy: { name: "asc" } }),
    prisma.medicine.findMany({ where: { isActive: true, materialId: { not: null } }, orderBy: { name: "asc" } }),
    prisma.patient.findMany({ where: { status: "Ativo", ...(unitIds ? { referenceUnitId: { in: unitIds } } : {}) }, orderBy: { person: { fullName: "asc" } }, take: 500, include: { person: true } }),
  ]);

  return (
    <PageFrame className="flex h-[calc(100dvh-7.5rem)] min-h-0 flex-col gap-2 overflow-hidden px-1 py-1 md:px-2">
      <PageHeader title="Farmácia Básica" icon={<Pill className="size-4 shrink-0 text-emerald-600" />} className="dark:border-gray-700 dark:bg-gray-800 dark:[&>h1]:text-white" />
      <div className="grid shrink-0 gap-2 md:grid-cols-2 xl:grid-cols-4">
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cadastrar produto</summary><form action={createHealthProductAction} className="mt-2 grid gap-1"><input name="code" required placeholder="Código único" className={input}/><input name="name" required placeholder="Nome" className={input}/><select name="categoryId" required className={input}><option value="">Grupo</option>{categories.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="productKind" required className={input}><option value="MEDICINE">Medicamento</option><option value="CONTROLLED">Controlado</option><option value="MANIPULATED">Manipulado</option><option value="CORRELATE">Correlato</option><option value="IMMUNOBIOLOGICAL">Imunobiológico</option><option value="SPECIALIZED">Produto especializado</option></select><input name="subgroup" placeholder="Subgrupo" className={input}/><input name="unitOfMeasure" defaultValue="UN" className={input}/><input name="packaging" placeholder="Apresentação/embalagem" className={input}/><input name="activePrinciple" placeholder="Princípio ativo" className={input}/><input name="concentration" placeholder="Concentração" className={input}/><input name="dcbCode" placeholder="Código DCB" className={input}/><input name="classification" placeholder="Classificação" className={input}/><input name="barcode" placeholder="Código de barras" className={input}/><button className="h-8 rounded bg-emerald-700 px-2 font-semibold text-white">Cadastrar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Cadastrar estoque</summary><form action={createHealthWarehouseAction} className="mt-2 grid gap-1"><input name="name" required placeholder="Nome do estoque" className={input}/><select name="healthUnitId" required className={input}><option value="">Unidade</option>{units.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="h-8 rounded bg-emerald-700 px-2 font-semibold text-white">Cadastrar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Receber produto</summary><form action={receiveStockAction} className="mt-2 grid gap-1"><select name="warehouseId" required className={input}><option value="">Estoque</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="materialId" required className={input}><option value="">Produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="supplierId" className={input}><option value="">Fornecedor</option>{suppliers.map(x => <option key={x.id} value={x.id}>{x.company?.corporateName || x.person?.fullName}</option>)}</select><input name="entryType" required placeholder="Tipo de entrada" className={input}/><input name="invoiceNumber" placeholder="Nota fiscal" className={input}/><input name="fundingSource" placeholder="Fonte de recurso" className={input}/><input name="batchNumber" required placeholder="Lote" className={input}/><input name="expirationDate" type="date" className={input}/><input name="productionDate" type="date" className={input}/><input name="quantity" required type="number" min="0.001" step="0.001" placeholder="Quantidade" className={input}/><input name="unitCost" required type="number" min="0" step="0.01" placeholder="Valor unitário" className={input}/><button className="h-8 rounded bg-emerald-700 px-2 font-semibold text-white">Confirmar entrada</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Dispensar receita</summary><form action={dispenseAction} className="mt-2 grid gap-1"><select name="prescriptionItemId" required className={input}><option value="">Receita eletrônica</option>{prescriptions.map(x => <option key={x.id} value={x.id}>{x.prescription.patient.person.fullName} · {x.medicineName}</option>)}</select><select name="warehouseId" required className={input}><option value="">Estoque</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="batchNumber" placeholder="Lote (vazio usa FEFO)" className={input}/><input name="quantity" required type="number" min="0.001" step="0.001" placeholder="Quantidade" className={input}/><input name="nextWithdrawalAt" type="date" className={input}/><input name="observation" placeholder="Observação" className={input}/><button className="h-8 rounded bg-emerald-700 px-2 font-semibold text-white">Dispensar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Transferir</summary><form action={dispatchTransferAction} className="mt-2 grid gap-1"><select name="originWarehouseId" required className={input}><option value="">Origem</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="destinationWarehouseId" required className={input}><option value="">Destino</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="materialId" required className={input}><option value="">Produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="batchNumber" required placeholder="Lote" className={input}/><input name="quantity" required type="number" min="0.001" step="0.001" placeholder="Quantidade" className={input}/><input name="requestNumber" placeholder="Pedido" className={input}/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Enviar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Aceitar transferência</summary><form action={receiveTransferAction} className="mt-2 grid gap-1"><select name="transferId" required className={input}><option value="">Em trânsito</option>{transfers.map(x => <option key={x.id} value={x.id}>{x.originWarehouse.name} → {x.destinationWarehouse.name}</option>)}</select><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Registrar aceite</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Baixa justificada</summary><form action={writeOffAction} className="mt-2 grid gap-1"><select name="stockId" required className={input}><option value="">Lote</option>{stockOptions.map(x => <option key={x.id} value={x.id}>{x.material.name} · {x.batchNumber}</option>)}</select><input name="quantity" required type="number" min="0.001" step="0.001" placeholder="Quantidade" className={input}/><input name="reason" required placeholder="Motivo" className={input}/><button className="h-8 rounded bg-rose-700 px-2 font-semibold text-white">Registrar baixa</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Enviar posição externa</summary><form action={dispatchPharmacyIntegrationAction} className="mt-2 grid gap-1"><select name="code" required className={input}><option value="HORUS">Hórus</option><option value="SIGAF">SIGAF</option><option value="TRANSPARENCIA_SAUDE">Portal de transparência</option></select><p className="text-[10px] text-slate-500">Exige conexão ativa e endpoint controlado nas configurações.</p><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Enviar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Interação cadastrada</summary><form action={saveMedicineInteractionAction} className="mt-2 grid gap-1"><select name="originMedicineId" required className={input}><option value="">Medicamento</option>{medicines.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="targetMedicineId" required className={input}><option value="">Interage com</option>{medicines.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="severity" placeholder="Classificação informada" className={input}/><input name="source" required placeholder="Fonte identificada" className={input}/><textarea name="description" required placeholder="Descrição informativa" className="min-h-14 rounded border p-2"/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Salvar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Modelo de posologia</summary><form action={saveDosageTemplateAction} className="mt-2 grid gap-1"><select name="medicineId" required className={input}><option value="">Medicamento</option>{medicines.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="name" required placeholder="Nome do modelo" className={input}/><input name="dose" required placeholder="Dose" className={input}/><input name="route" placeholder="Via" className={input}/><input name="frequency" required placeholder="Frequência" className={input}/><input name="duration" placeholder="Duração" className={input}/><input name="instructions" placeholder="Instruções cadastradas" className={input}/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Salvar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Solicitar produto</summary><form action={createPharmacyRequestAction} className="mt-2 grid gap-1"><select name="patientId" className={input}><option value="">Pedido entre unidades</option>{patients.map(x => <option key={x.id} value={x.id}>{x.person.fullName}</option>)}</select><select name="destinationWarehouseId" required className={input}><option value="">Estoque solicitante</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="materialId" required className={input}><option value="">Produto</option>{materials.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="quantity" type="number" min="0.001" step="0.001" required placeholder="Quantidade" className={input}/><input name="notes" placeholder="Observação" className={input}/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Registrar pedido</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Bloquear ou liberar lote</summary><form action={setStockBlockAction} className="mt-2 grid gap-1"><select name="stockId" required className={input}><option value="">Lote</option>{stockOptions.map(x => <option key={x.id} value={x.id}>{x.material.name} · {x.batchNumber}</option>)}</select><select name="blocked" className={input}><option value="true">Bloquear</option><option value="false">Liberar</option></select><input name="reason" placeholder="Motivo do bloqueio" className={input}/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Confirmar</button></form></details>
        <details className="rounded border bg-white p-2 text-xs"><summary className="cursor-pointer font-semibold">Livro de controlados</summary><form action={toggleControlledBookAction} className="mt-2 grid gap-1"><select name="warehouseId" required className={input}><option value="">Estoque</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="period" type="month" required className={input}/><select name="close" className={input}><option value="false">Abrir</option><option value="true">Fechar</option></select><input name="closingEvidence" placeholder="Evidência de fechamento" className={input}/><button className="h-8 rounded bg-slate-800 px-2 font-semibold text-white">Registrar</button></form></details>
      </div>
      <HealthSimpleListClient rows={stocks.map((item) => ({ id: item.id, cells: { medicine: item.material.name, warehouse: item.warehouse.name, batch: item.batchNumber, expiration: item.expirationDate ? item.expirationDate.toLocaleDateString("pt-BR") : "-", quantity: item.quantity.toLocaleString("pt-BR"), status: item.blockedAt ? "Bloqueado" : "Disponível" } }))} columns={[{ key: "medicine", label: "Produto" }, { key: "warehouse", label: "Estoque", responsive: "sm" }, { key: "batch", label: "Lote", responsive: "sm", width: "medium" }, { key: "expiration", label: "Validade", responsive: "md", width: "medium" }, { key: "quantity", label: "Saldo", align: "right", width: "medium" }, { key: "status", label: "Situação", responsive: "lg", width: "medium" }]} label="lotes" searchPlaceholder="Buscar produto, estoque ou lote" filterKey="warehouse" filterLabel="Todos os estoques" serverPagination={{ page, total, pathname: "/app-domain/saude/farmacia", search: q, filter, filterOptions: warehouses.map(x => x.name) }} />
    </PageFrame>
  );
}
