import { getTenantContextForModule } from "@/lib/platform/tenant-context";
export const dynamic = "force-dynamic";
const esc = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { prisma } = await getTenantContextForModule("TRIBUTACAO");
  const invoice = await prisma.invoice.findUnique({ where: { id }, include: { provider: { include: { person: true, company: true } }, taker: { include: { person: true, company: true } } } });
  const [fiscal, events, letters] = invoice ? await Promise.all([prisma.nfseInvoiceData.findUnique({ where: { invoiceId: invoice.id } }), prisma.nfseEvent.findMany({ where: { invoiceId: invoice.id }, orderBy: { createdAt: "asc" } }), prisma.nfseCorrectionLetter.findMany({ where: { invoiceId: invoice.id }, orderBy: { createdAt: "asc" } })]) : [null, [], []];
  if (!invoice || !fiscal) return new Response("NFS-e não encontrada.", { status: 404 });
  const provider = invoice.provider.company?.corporateName ?? invoice.provider.person?.fullName ?? invoice.providerId; const taker = invoice.taker?.company?.corporateName ?? invoice.taker?.person?.fullName ?? "Não informado";
  const history = events.map((event) => `<li>${esc(event.createdAt.toLocaleString("pt-BR"))} — <b>${esc(event.eventType)}</b>: ${esc(event.description)}</li>`).join("");
  const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>NFS-e ${invoice.invoiceNumber}</title><style>body{font-family:Arial;color:#172033;margin:24px}.sheet{max-width:850px;margin:auto;border:1px solid #cbd5e1;padding:24px}h1{font-size:21px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{border-bottom:1px solid #e2e8f0;padding:7px}.field b{display:block;font-size:10px;color:#64748b;text-transform:uppercase}.values{width:100%;border-collapse:collapse;margin-top:18px}.values td,.values th{border:1px solid #cbd5e1;padding:7px}.notice{margin-top:18px;padding:10px;background:#eff6ff;border:1px solid #bfdbfe;font-size:12px}.actions{text-align:right;max-width:850px;margin:auto auto 12px}@media(max-width:600px){.grid{grid-template-columns:1fr}}@media print{.actions{display:none}.sheet{border:0}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / salvar PDF</button></div><main class="sheet"><h1>Nota Fiscal Eletrônica de Serviços — NFS-e</h1><p>Nº ${invoice.invoiceNumber} · verificação <b>${esc(invoice.verificationCode)}</b> · ${esc(invoice.status)}</p><div class="grid"><div class="field"><b>Prestador</b>${esc(provider)}</div><div class="field"><b>Tomador</b>${esc(taker)}</div><div class="field"><b>Competência</b>${esc(invoice.competence)}</div><div class="field"><b>Local</b>${esc(fiscal.serviceLocation ?? "Município")}</div></div><h2>Serviço</h2><p>${esc(fiscal.serviceDescription)}</p><table class="values"><tr><th>Valor</th><th>Deduções</th><th>Base</th><th>Alíquota</th><th>ISS</th></tr><tr><td>R$ ${esc(invoice.serviceValueDecimal)}</td><td>R$ ${esc(invoice.deductionsDecimal)}</td><td>R$ ${esc(fiscal.taxableBaseDecimal)}</td><td>${esc(fiscal.rate)}%</td><td>R$ ${esc(invoice.issValueDecimal)} (${esc(fiscal.retentionType)})</td></tr></table><h2>Histórico</h2><ul>${history}</ul><p>Cartas de correção registradas: ${letters.length}</p><div class="notice">Autenticidade: ${esc(fiscal.authenticityUrl)}. Documento demonstrativo municipal. A validação oficial e assinatura ICP-Brasil dependem dos provedores homologados configurados no ambiente.</div></main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="nfse-${invoice.invoiceNumber}.html"` } });
}
