"use client";
import { useState, useTransition } from "react";
import { Cross } from "lucide-react";
import { createCemeteryAction, createGraveAction, createSectorAction, enrollCemeteryFeeInDebtAction, grantConcessionAction, issueCemeteryFeeAction, registerDeceasedAction, registerEmployeeAction, registerFuneralHomeAction, registerMovementAction } from "./actions";
type Data = { cemeteries: { id: string; code: string; name: string; address: string | null; wakePlace: string | null; sectors: { id: string; code: string; name: string; parentId: string | null }[]; employees: { id: string; name: string; role: string }[] }[]; graves: { id: string; cemeteryId: string; code: string; type: string; sector: string | null; capacity: number; occupied: number; status: string }[]; funeralHomes: { id: string; name: string }[]; causes: { id: string; code: string; description: string }[]; deceased: { id: string; name: string; deathDate: string; grave: string | null; cause: string | null; doctor: string; status: string; cemeteryId: string }[]; movements: { id: string; type: string; date: string; deceased: string | null; grave: string; from: string | null; to: string | null; feeAssessmentId: string | null }[]; concessions: { id: string; grave: string; holder: string; type: string; endsAt: string | null; status: string; feeAssessmentId: string | null }[]; taxpayers: { id: string; name: string }[]; fees: { id: string; number: string; taxpayer: string; total: number; guides: { id: string; number: string; status: string; total: number }[] }[] };
const input = "h-8 w-full rounded-md border border-slate-300 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-900";
const button = "inline-flex h-8 items-center justify-center rounded-md bg-amber-500 px-2.5 text-xs font-bold text-slate-950 hover:bg-amber-400 disabled:opacity-50";
const secondary = "inline-flex h-8 items-center justify-center rounded-md border px-2 text-xs font-semibold hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900";
const money = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function CemiteriosClient({ data }: { data: Data }) {
  const [tab, setTab] = useState("estrutura");
  const [message, setMessage] = useState("");
  const [pending, start] = useTransition();
  const [cemeteryId, setCemeteryId] = useState(data.cemeteries[0]?.id ?? "");
  const [taxpayerId, setTaxpayerId] = useState(data.taxpayers[0]?.id ?? "");
  const run = (job: () => Promise<{ error?: string }>) => start(async () => { const r = await job(); setMessage(r.error ?? "Operação concluída."); });
  const submit = (handler: (form: FormData) => void) => (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); handler(new FormData(e.currentTarget)); };
  const cemetery = data.cemeteries.find((c) => c.id === cemeteryId) ?? data.cemeteries[0];
  const graves = data.graves.filter((g) => !cemetery || g.cemeteryId === cemetery.id);
  const capacity = graves.reduce((s, g) => s + g.capacity, 0);
  const occupied = graves.reduce((s, g) => s + Math.min(g.occupied, g.capacity), 0);
  const rate = capacity ? Math.round((occupied / capacity) * 100) : 0;
  return <div className="flex h-full min-h-0 flex-1 flex-col gap-2 overflow-hidden p-2 sm:p-2.5">
    <header className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="flex items-center gap-2 text-lg font-bold"><Cross className="size-5 text-amber-500" />Cemitérios Municipais</h1><p className="text-[11px] text-slate-500">Cadastro, ocupação, movimentos e taxas pelo motor tributário.</p></div><div className="flex gap-2"><select className={`${input} max-w-64`} value={cemeteryId} onChange={(e) => setCemeteryId(e.target.value)}>{data.cemeteries.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select className={`${input} max-w-64`} value={taxpayerId} onChange={(e) => setTaxpayerId(e.target.value)}>{data.taxpayers.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div></header>
    <nav className="flex gap-1 overflow-x-auto rounded-lg bg-slate-900 p-1 text-[11px] font-semibold text-slate-300">{[["estrutura", "Estrutura e Sepulturas"], ["obitos", "Óbitos e Movimentos"], ["concessoes", "Concessões e Guias"], ["ocupacao", "Ocupação e Relatórios"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-md px-3 py-1.5 ${tab === id ? "bg-amber-500 text-slate-950" : "hover:bg-slate-800"}`}>{label}</button>)}</nav>
    {message && <button onClick={() => setMessage("")} className="rounded-md border border-blue-200 bg-blue-50 px-3 py-1 text-left text-xs text-blue-800">{message}</button>}
    <main className="min-h-0 flex-1 overflow-auto">
      {tab === "estrutura" && <div className="grid gap-2 xl:grid-cols-[330px_1fr]">
        <div className="grid content-start gap-2">
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => createCemeteryAction({ code: String(f.get("code")), name: String(f.get("name")), address: String(f.get("address") || ""), wakePlace: String(f.get("wake") || "") })))}><h2 className="text-sm font-bold">Cemitério</h2><input className={input} name="code" placeholder="Código" required /><input className={input} name="name" placeholder="Nome" required /><input className={input} name="address" placeholder="Endereço" /><input className={input} name="wake" placeholder="Local do velório" /><button className={button}>Salvar</button></form>
          {cemetery && <><form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => createSectorAction({ cemeteryId: cemetery.id, code: String(f.get("code")), name: String(f.get("name")) })))}><h2 className="text-sm font-bold">Setor / quadra</h2><div className="grid grid-cols-2 gap-2"><input className={input} name="code" placeholder="Código" required /><input className={input} name="name" placeholder="Nome" required /></div><button className={button}>Salvar setor</button></form>
            <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => createGraveAction({ cemeteryId: cemetery.id, sectorId: String(f.get("sector") || "") || undefined, code: String(f.get("code")), graveType: String(f.get("type")), capacity: Number(f.get("cap") || 1) })))}><h2 className="text-sm font-bold">Sepultura e vagas</h2><input className={input} name="code" placeholder="Identificação (ex.: Q-A-001)" required /><div className="grid grid-cols-2 gap-2"><select className={input} name="type"><option>COVA</option><option>CARNEIRA</option><option>GAVETA</option><option>JAZIGO</option><option>OSSARIO</option></select><input className={input} name="cap" type="number" min={1} defaultValue={1} /></div><select className={input} name="sector"><option value="">Sem setor</option>{cemetery.sectors.map((s) => <option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select><button className={button}>Salvar sepultura</button></form>
            <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => registerEmployeeAction({ cemeteryId: cemetery.id, name: String(f.get("name")), role: String(f.get("role")) })))}><h2 className="text-sm font-bold">Funcionário</h2><input className={input} name="name" placeholder="Nome" required /><input className={input} name="role" placeholder="Função (ex.: Coveiro)" required /><button className={button}>Salvar</button></form></>}
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => registerFuneralHomeAction({ name: String(f.get("name")), phone: String(f.get("phone") || "") })))}><h2 className="text-sm font-bold">Funerária</h2><input className={input} name="name" placeholder="Nome" required /><input className={input} name="phone" placeholder="Telefone" /><button className={button}>Salvar</button></form>
        </div>
        <div className="grid content-start gap-2">
          {cemetery && <section className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><b className="text-sm">{cemetery.name}</b><p>Setores: {cemetery.sectors.map((s) => s.code).join(", ") || "—"} · Velório: {cemetery.wakePlace ?? "—"}</p><p>Funcionários: {cemetery.employees.map((e) => `${e.name} (${e.role})`).join("; ") || "—"}</p><p>Funerárias: {data.funeralHomes.map((f) => f.name).join("; ") || "—"}</p></section>}
          <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-5 gap-2 border-b bg-slate-50 p-2 font-bold dark:bg-slate-900"><span>Sepultura</span><span>Tipo</span><span>Setor</span><span>Vagas</span><span>Situação</span></div>{graves.slice(0, 60).map((g) => <div key={g.id} className="grid grid-cols-5 gap-2 border-t p-2"><span>{g.code}</span><span>{g.type}</span><span>{g.sector ?? "—"}</span><span>{g.occupied}/{g.capacity}</span><span>{g.status}</span></div>)}</section>
        </div>
      </div>}
      {tab === "obitos" && <div className="grid gap-2 xl:grid-cols-[360px_1fr]">
        <div className="grid content-start gap-2">
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => registerDeceasedAction({ fullName: String(f.get("name")), deathDate: String(f.get("death")), cemeteryId: cemetery?.id ?? "", graveId: String(f.get("grave")), funeralHomeId: String(f.get("fh") || "") || undefined, causeId: String(f.get("cause") || "") || undefined, causeText: String(f.get("causeText") || ""), doctorName: String(f.get("doc")), doctorCrm: String(f.get("crm")), taxpayerId, groups: { sepultamento: { funeraria: data.funeralHomes.find((x) => x.id === String(f.get("fh")))?.name ?? null } } })))}><h2 className="text-sm font-bold">Óbito (11 grupos) + sepultamento</h2><input className={input} name="name" placeholder="Falecido" required /><div className="grid grid-cols-2 gap-2"><input className={input} name="death" type="date" defaultValue="2026-09-21" required /><select className={input} name="grave" required>{graves.filter((g) => g.status !== "INTERDITADA" && g.occupied < g.capacity).map((g) => <option key={g.id} value={g.id}>{g.code} ({g.occupied}/{g.capacity})</option>)}</select></div><div className="grid grid-cols-2 gap-2"><select className={input} name="fh"><option value="">Funerária (opc.)</option>{data.funeralHomes.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}</select><select className={input} name="cause"><option value="">Causa (opc.)</option>{data.causes.map((c) => <option key={c.id} value={c.id}>{c.code} — {c.description}</option>)}</select></div><input className={input} name="causeText" placeholder="Causa (texto livre, se aplicável)" /><div className="grid grid-cols-2 gap-2"><input className={input} name="doc" placeholder="Médico declarante" required /><input className={input} name="crm" placeholder="CRM" required /></div><button className={button} disabled={!cemetery}>Registrar óbito</button></form>
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => registerMovementAction({ graveId: String(f.get("from")), toGraveId: String(f.get("to") || "") || undefined, movementType: String(f.get("type")) as "EXUMACAO" | "REMOCAO" | "TRASLADO", notes: String(f.get("notes") || "") })))}><h2 className="text-sm font-bold">Exumação / remoção / traslado</h2><select className={input} name="type"><option>EXUMACAO</option><option>REMOCAO</option><option>TRASLADO</option></select><select className={input} name="from">{graves.map((g) => <option key={g.id} value={g.id}>{g.code}</option>)}</select><select className={input} name="to"><option value="">Destino (remoção/traslado)</option>{graves.map((g) => <option key={g.id} value={g.id}>{g.code}</option>)}</select><input className={input} name="notes" placeholder="Observações" /><button className={button}>Registrar movimento</button></form>
        </div>
        <div className="grid content-start gap-2">
          <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-5 gap-2 border-b bg-slate-50 p-2 font-bold dark:bg-slate-900"><span>Falecido</span><span>Óbito</span><span>Sepultura</span><span>Causa</span><span>Situação</span></div>{data.deceased.slice(0, 40).map((d) => <div key={d.id} className="grid grid-cols-5 gap-2 border-t p-2"><span>{d.name}</span><span>{d.deathDate}</span><span>{d.grave ?? "—"}</span><span>{d.cause ?? "—"}</span><span>{d.status}</span></div>)}</section>
          <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><h2 className="border-b p-2 text-sm font-bold">Movimentos</h2>{data.movements.slice(0, 40).map((m) => <div key={m.id} className="border-t p-2">• {m.type} · {m.date} · {m.deceased ?? "—"} · {m.from ? `${m.from} → ` : ""}{m.to ?? m.grave}</div>)}</section>
        </div>
      </div>}
      {tab === "concessoes" && <div className="grid gap-2 xl:grid-cols-[330px_1fr]">
        <div className="grid content-start gap-2">
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => grantConcessionAction({ graveId: String(f.get("grave")), holderName: String(f.get("holder")), taxpayerId, concessionType: String(f.get("type")) as "TEMPORARIA" | "INDETERMINADA", endsAt: String(f.get("ends") || "") || undefined })))}><h2 className="text-sm font-bold">Concessão temporária / indeterminada</h2><select className={input} name="grave">{graves.map((g) => <option key={g.id} value={g.id}>{g.code}</option>)}</select><input className={input} name="holder" placeholder="Titular" required /><div className="grid grid-cols-2 gap-2"><select className={input} name="type"><option>TEMPORARIA</option><option>INDETERMINADA</option></select><input className={input} name="ends" type="date" /></div><button className={button}>Conceder</button></form>
          <form className="grid gap-2 rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950" onSubmit={submit((f) => run(() => issueCemeteryFeeAction({ taxpayerId, amount: Number(f.get("amount")), dueDate: String(f.get("due")) })))}><h2 className="text-sm font-bold">Guia de taxa pelo motor</h2><div className="grid grid-cols-2 gap-2"><input className={input} name="amount" type="number" step="0.01" placeholder="Valor" required /><input className={input} name="due" type="date" defaultValue="2026-10-20" required /></div><button className={button} disabled={!taxpayerId}>Emitir guia</button><p className="text-[10px] text-slate-500">Lançamento e DAM gerados pelo motor financeiro/tributário existente.</p></form>
        </div>
        <div className="grid content-start gap-2">
          <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-5 gap-2 border-b bg-slate-50 p-2 font-bold dark:bg-slate-900"><span>Sepultura</span><span>Titular</span><span>Tipo</span><span>Término</span><span>Situação</span></div>{data.concessions.slice(0, 40).map((c) => <div key={c.id} className="grid grid-cols-5 gap-2 border-t p-2"><span>{c.grave}</span><span>{c.holder}</span><span>{c.type}</span><span>{c.endsAt ?? "—"}</span><span>{c.status}</span></div>)}</section>
          <section className="rounded-lg border bg-white text-[11px] dark:border-slate-800 dark:bg-slate-950"><h2 className="border-b p-2 text-sm font-bold">Guias de taxas (abertas/vencidas/pagas)</h2>{data.fees.slice(0, 20).map((a) => <div key={a.id} className="border-t p-2"><b>{a.number} · {a.taxpayer} · {money(a.total)}</b>{a.guides.map((g) => <div key={g.id}>• DAM {g.number} · {money(g.total)} · {g.status}</div>)}{!a.guides.length && <button className={secondary} disabled={pending} onClick={() => run(() => enrollCemeteryFeeInDebtAction(a.id))}>Inscrever taxa em dívida ativa</button>}</div>)}</section>
        </div>
      </div>}
      {tab === "ocupacao" && <div className="grid gap-2">
        <section className="rounded-lg border bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><h2 className="text-sm font-bold">Ocupação de vagas {cemetery ? `— ${cemetery.name}` : ""}</h2><p className="text-xs">{graves.length} sepulturas · capacidade {capacity} · ocupadas {occupied} · livres {capacity - occupied} · {rate}%</p><div className="mt-2 h-3 overflow-hidden rounded bg-slate-200 dark:bg-slate-800"><div className="h-full bg-amber-500" style={{ width: `${rate}%` }} /></div></section>
        <section className="rounded-lg border bg-white p-3 text-[11px] dark:border-slate-800 dark:bg-slate-950"><h2 className="text-sm font-bold">Movimentos por tipo</h2>{["SEPULTAMENTO", "EXUMACAO", "REMOCAO", "TRASLADO"].map((t) => <div key={t}>• {t}: {data.movements.filter((m) => m.type === t).length}</div>)}</section>
      </div>}
    </main>
  </div>;
}
