"use client";

import { useMemo, useState, useTransition } from "react";
import { Building, Calculator, FileCheck2, Search } from "lucide-react";
import { ErpPageTitle } from "@/components/app-ui/erp/ErpPageTitle";
import { ErpListFrame } from "@/components/app-ui/erp/ErpListFrame";
import { ErpPagination } from "@/components/app-ui/erp/ErpPagination";
import { ErpStatusBadge, ErpTableContainer, ErpTableTd, ErpTableTh, ErpTableThead, ErpTableTr, type ErpStatusVariant } from "@/components/app-ui/erp/ErpTable";
import { analyzeItbiAction, createItbiAction, generateItbiDocumentAction, issueItbiDamAction, transmitItbiAction } from "./actions";

type Declaration = { id: string; number: string; status: string; type: string; protocol: string | null; propertyId: string; scope: string; fraction: number; propertyValue: number; base: number; rate: number; tax: number; taxDebt: number; nonTaxDebt: number; isLeasehold: boolean; registryOffice: string | null; guideId: string | null; documentId: string | null; parties: { role: string; name: string; share: number | null; liability: string | null }[]; events: { type: string; description: string; date: string }[] };
const input = "h-8 min-w-0 rounded border border-slate-200 bg-white px-2 text-xs outline-none focus:border-emerald-500";
const button = "h-7 rounded bg-emerald-700 px-2.5 text-[11px] font-semibold text-white disabled:opacity-50";
const secondary = "h-7 rounded border border-slate-200 bg-white px-2 text-[11px] font-semibold text-slate-700 disabled:opacity-50";
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
function variant(status: string): ErpStatusVariant { return status.includes("INDEFER") ? "danger" : status.includes("APROV") || status.includes("EMITIDO") ? "success" : status === "RASCUNHO" ? "neutral" : "warning"; }

export default function ItbiClient(props: { transactionTypes: { id: string; code: string; name: string; rate: number; damStage: string; updateMode: string }[]; properties: { id: string; label: string; taxpayerId: string | null }[]; taxpayers: { id: string; name: string }[]; processes: { id: string; protocolNumber: string; status: string }[]; declarations: Declaration[] }) {
  const [tab, setTab] = useState<"jornada" | "historico" | "parametros">("jornada"); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [notice, setNotice] = useState(""); const [pending, startTransition] = useTransition(); const [selected, setSelected] = useState<Declaration | null>(null); const pageSize = 20;
  const run = (task: () => Promise<{ error?: string }>, success: string) => startTransition(async () => { const result = await task(); setNotice(result.error ?? success); if (!result.error) setSelected(null); });
  const filtered = useMemo(() => props.declarations.filter((item) => `${item.number} ${item.status} ${item.protocol ?? ""} ${item.type}`.toLowerCase().includes(search.toLowerCase())), [props.declarations, search]);
  const paged = filtered.slice((page - 1) * pageSize, page * pageSize);
  const defaultSeller = props.properties[0]?.taxpayerId ?? props.taxpayers[0]?.id ?? "";

  return <div className="flex h-full min-h-0 flex-1 flex-col gap-2 overflow-hidden p-2 sm:p-2.5">
    <ErpPageTitle title="ITBI — transmissões e foros" description="Declaração, cálculo, protocolo, análise, DAM e documento" icon={<Building className="size-4 text-emerald-600"/>}/>
    <div className="flex shrink-0 gap-1 rounded-md border border-slate-200 bg-slate-50 p-1">{([['jornada','Nova declaração'],['historico','Histórico e documentos'],['parametros','Parâmetros']] as const).map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`h-7 rounded px-3 text-xs font-semibold ${tab === id ? "bg-slate-800 text-white" : "text-slate-600"}`}>{label}</button>)}</div>
    {notice && <div className="shrink-0 rounded border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs text-amber-900">{notice}</div>}
    {tab === "jornada" && <section className="shrink-0 rounded-md border border-slate-200 bg-white p-2.5"><form action={(form) => run(() => createItbiAction({ transactionTypeId: String(form.get("transactionTypeId")), realEstateId: String(form.get("realEstateId")), processId: String(form.get("processId")), registryOffice: String(form.get("registryOffice")), transmittedFractionPercent: Number(form.get("fraction")), declaredPropertyValue: Number(form.get("propertyValue")), sellerTaxpayerId: String(form.get("seller")), buyers: [{ taxpayerId: String(form.get("buyer1")), sharePercent: Number(form.get("share1")) }, ...(form.get("buyer2") ? [{ taxpayerId: String(form.get("buyer2")), sharePercent: Number(form.get("share2")) }] : [])], responsibleTaxpayerId: String(form.get("responsible") || "") || undefined, responsibilityType: String(form.get("responsibilityType")) as "SOLIDARIO" | "SUBSIDIARIO", isLeasehold: Boolean(form.get("isLeasehold")), leaseholdDetails: String(form.get("leaseholdDetails") || ""), cadastralUpdateMode: String(form.get("cadastralUpdateMode")) as "MANUAL" | "AUTO_ON_APPROVAL" }), "Declaração calculada e salva como rascunho.")} className="grid gap-2 sm:grid-cols-4 xl:grid-cols-6">
      <select name="transactionTypeId" required className={input}>{props.transactionTypes.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.rate}%</option>)}</select><select name="realEstateId" required className={`${input} sm:col-span-2`}>{props.properties.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select name="processId" required className={input}><option value="">Protocolo</option>{props.processes.map((item) => <option key={item.id} value={item.id}>{item.protocolNumber}</option>)}</select><input name="registryOffice" required placeholder="Cartório" className={input}/><input name="propertyValue" type="number" step="0.01" defaultValue="300000" required className={input}/>
      <select name="seller" defaultValue={defaultSeller} required className={`${input} sm:col-span-2`}><option value="">Transmitente</option>{props.taxpayers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="buyer1" required className={`${input} sm:col-span-2`}><option value="">Adquirente 1</option>{props.taxpayers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="share1" type="number" step="0.000001" defaultValue="60" required placeholder="% adquirente 1" className={input}/><input name="fraction" type="number" min="0.000001" max="100" step="0.000001" defaultValue="100" required placeholder="Fração transmitida %" className={input}/>
      <select name="buyer2" className={`${input} sm:col-span-2`}><option value="">Sem segundo adquirente</option>{props.taxpayers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="share2" type="number" step="0.000001" defaultValue="40" placeholder="% adquirente 2" className={input}/><select name="responsible" className={`${input} sm:col-span-2`}><option value="">Sem responsável adicional</option>{props.taxpayers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="responsibilityType" className={input}><option value="SOLIDARIO">Solidário</option><option value="SUBSIDIARIO">Subsidiário</option></select>
      <select name="cadastralUpdateMode" className={`${input} sm:col-span-2`}><option value="MANUAL">Atualização cadastral manual</option><option value="AUTO_ON_APPROVAL">Atualizar cadastro fiscal na aprovação</option></select><label className="flex h-8 items-center gap-2 text-xs"><input name="isLeasehold" type="checkbox"/>Imóvel foreiro</label><input name="leaseholdDetails" placeholder="Foro/domínio útil" className={`${input} sm:col-span-2`}/><button disabled={pending} className={button}>Calcular e salvar</button>
      <div className="rounded bg-emerald-50 px-2 py-1 text-[10px] text-emerald-800 sm:col-span-4 xl:col-span-6"><Calculator className="mr-1 inline size-3"/>Base transmitida = valor do imóvel × fração. A divisão 60/40 reparte a mesma base e não multiplica o imposto novamente.</div>
    </form></section>}
    {tab === "parametros" && <div className="grid shrink-0 gap-2 sm:grid-cols-2">{props.transactionTypes.map((item) => <div key={item.id} className="rounded-md border bg-white p-3 text-xs"><strong>{item.name}</strong><dl className="mt-2 grid grid-cols-2 gap-1 text-slate-600"><dt>Código</dt><dd>{item.code}</dd><dt>Alíquota persistida</dt><dd>{item.rate}%</dd><dt>DAM</dt><dd>{item.damStage}</dd><dt>Atualização</dt><dd>{item.updateMode}</dd></dl></div>)}</div>}
    {tab === "historico" && selected && <div className="grid shrink-0 gap-2 rounded-md border bg-white p-2.5 lg:grid-cols-2"><div className="text-xs"><strong>{selected.number}</strong><p className="mt-1 text-slate-600">{selected.parties.map((party) => `${party.role}: ${party.name}${party.share ? ` (${party.share}%)` : ""}`).join(" · ")}</p><p className="mt-1">Cartório: {selected.registryOffice} · {selected.isLeasehold ? "Foreiro" : "Não foreiro"} · Dívida não tributária: {money(selected.nonTaxDebt)}</p></div><div className="max-h-24 overflow-y-auto text-[10px]">{selected.events.map((event) => <div key={`${event.type}-${event.date}`} className="border-b py-1"><b>{event.type}</b> · {new Date(event.date).toLocaleString("pt-BR")}<span className="block text-slate-500">{event.description}</span></div>)}</div></div>}
    <ErpListFrame toolbar={<label className="relative block"><Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Buscar declaração, protocolo ou situação" className="h-8 w-full rounded border border-slate-200 pl-8 pr-2 text-xs"/></label>} pagination={<ErpPagination page={page} total={filtered.length} pageSize={pageSize} previousHref="#" nextHref="#" label="declarações" onPageChange={setPage}/> }>
      <ErpTableContainer><ErpTableThead><tr><ErpTableTh>Declaração / imóvel</ErpTableTh><ErpTableTh className="w-[12%]">Transmissão</ErpTableTh><ErpTableTh className="w-[11%] text-right">Base</ErpTableTh><ErpTableTh className="w-[9%] text-right">ITBI</ErpTableTh><ErpTableTh className="w-[10%]">Situação</ErpTableTh><ErpTableTh className="w-[31%] text-right">Ações</ErpTableTh></tr></ErpTableThead><tbody>{paged.map((item) => <ErpTableTr key={item.id}><ErpTableTd><button onClick={() => { setSelected(item); setTab("historico"); }} className="font-semibold text-emerald-700 hover:underline">{item.number}</button><small className="block text-slate-400">{item.protocol} · {item.type}</small></ErpTableTd><ErpTableTd>{item.scope} · {item.fraction}%</ErpTableTd><ErpTableTd className="text-right tabular-nums">{money(item.base)}<small className="block text-slate-400">{item.rate}%</small></ErpTableTd><ErpTableTd className="text-right font-semibold tabular-nums">{money(item.tax)}</ErpTableTd><ErpTableTd><ErpStatusBadge variant={variant(item.status)}>{item.status}</ErpStatusBadge>{item.taxDebt > 0 && <small className="block text-rose-600">Débito {money(item.taxDebt)}</small>}</ErpTableTd><ErpTableTd className="text-right"><div className="flex flex-wrap justify-end gap-1">{item.status === "RASCUNHO" && <button disabled={pending} onClick={() => run(() => transmitItbiAction(item.id), "Declaração protocolada." )} className={secondary}>Transmitir</button>}{item.status === "PROTOCOLADA" && <><button disabled={pending} onClick={() => run(() => analyzeItbiAction({ declarationId: item.id, approved: true, notes: "Análise fiscal aprovada" }), "Declaração aprovada e lançada." )} className={button}>Aprovar</button><button disabled={pending} onClick={() => run(() => analyzeItbiAction({ declarationId: item.id, approved: false, notes: "Pendência identificada na análise" }), "Declaração indeferida." )} className={secondary}>Indeferir</button></>}{item.status === "APROVADA" && <button disabled={pending} onClick={() => run(() => issueItbiDamAction(item.id), "DAM emitido." )} className={button}>Gerar DAM</button>}{item.guideId && <a href={`/tributacao/guias/${item.guideId}`} target="_blank" className={secondary}>DAM</a>}{["APROVADA","DAM_EMITIDO","DOCUMENTO_EMITIDO"].includes(item.status) && !item.documentId && <button disabled={pending} onClick={() => run(() => generateItbiDocumentAction(item.id), "Documento registrado no GED." )} className={secondary}><FileCheck2 className="mr-1 inline size-3"/>Documento</button>}{item.documentId && <a href={`/tributacao/itbi/${item.id}/documento`} target="_blank" className={secondary}>Visualizar</a>}</div></ErpTableTd></ErpTableTr>)}</tbody></ErpTableContainer>
    </ErpListFrame>
  </div>;
}
